### ISSUE TITLE
Aura snapshot [BIP 125] - Vote FOR

### ISSUE THREAD

**Issue by hasherror** [Badger-Finance/badger-multisig#1000]
Council majority vote for graviAURA vlAURA vote to be used to vote FOR in the following snapshot.
https://snapshot.org/#/aurafinance.eth/proposal/0xba0e84ad4240bd8f9737868763a46dd5588a35d9d856d4474b6e786bc8fde638

Vote 4 Yes, 3 no votes
https://discord.com/channels/743271185751474307/842854176488161311/1047941060145467412 #

![Screenshot_20221201-192547](https://user-images.githubusercontent.com/75948305/205187208-f08223cb-f3bb-40c4-be96-fd68fb7ca109.png)

**Comment by gosuto-inzasheru** [comment]
somehow i cant seem to transfer this ticket to https://github.com/Badger-Finance/badger-voting/issues. @hasherror or @SHAKOTN can you recreate it there?

**Comment by gosuto-inzasheru** [comment]
ah and just or context @hasherror, votes such as these occur from the delegate.badgerdao.eth address, which is not a multisig. this repo cant help you :)

**Comment by hasherror** [comment]
Recreated.  Thanks!
