### ISSUE TITLE
Rari Rate Curve Changes

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-multisig#101]
Update the rate curves on all rari pools:
**Governance**:
https://discord.com/channels/743271185751474307/842854176488161311/938917357533933588
![image](https://user-images.githubusercontent.com/11885129/152888629-de94cf52-0c64-4fe6-a6e4-686d11455397.png)
Requested operation:
In the rari fuse pool 22 change the following rate curves:
 ETH and WBTC to JumpRateModel_FEI_ETH
Everything else to: to JumpRateModel_FEI_DAI

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xa81025d5ae77b22b44b22347502a1f6b2ed4a8f21cb9cb20e3daf0dffcce0ae7
