### ISSUE TITLE
Great Ape Safe Aura functions fixes

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1023]
Currently, the Convex functions imported to the Aura library are broken for BPT withdrawing (and could be for other functions). The reason for this may be that they fetch the rewardsPool from the booster based on the underlying BPT. The issue is that the booster currently holds 2 BPTs with their respective PIDs for each position and returns the first one which is now deprecated. The functions should be modified so that the correct rewards pool is utilized.

**Comment by petrovska-petro** [comment]
fixed in #1036
