### ISSUE TITLE
Approve contract access in bveCVX to voter 

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1026]
Currently voter is unable to interact with bvecvx, since it is not approved

**Comment by gosuto-inzasheru** [comment]
```
>>> from great_ape_safe import GreatApeSafe
>>> from helpers.addresses import r
>>> safe = GreatApeSafe(r.badger_wallets.dev_multisig)
>>> safe.init_badger()
>>> safe.badger.whitelist(r.badger_wallets.treasury_voter_multisig, r.treasury_tokens.bveCVX)
whitelisting 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b on 0xfd05D3C7fe2924020620A8bE4961bBaA747e6305...
Transaction sent: 0x43376d6673e4d43653af6307f59aa1d8068e0b8a3cb3c3b435f9689ef7508000
  Gas price: 0.0 gwei   Gas limit: 6721975   Nonce: 1
  ISettV4h.approveContractAccess confirmed   Block: 16187904   Gas used: 47061 (0.70%)

True
>>> safe.post_safe_tx()
```
https://dashboard.tenderly.co/gosuto/msig-sim/simulator/4481ed81-c66e-4c83-9225-2a9ca9bec4e6

**Comment by gosuto-inzasheru** [comment]
was part of this batch, but no event is emitted: https://etherscan.io/tx/0xfb815394754b7fb51c60d13eeaf8c94ba8378ad2982a2fadd6ea6e2e7f7efaf0#eventlog

<img width="359" alt="Screenshot 2022-12-15 at 12 09 06" src="https://user-images.githubusercontent.com/2835259/207790300-b39efc11-3262-499a-9220-8e75a5c3afa8.png">
