### ISSUE TITLE
wbtc big dao migration

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1031]
> joe koh, [15 Dec 2022 at 23:23:47]:
> Hi everybody!
> 
> BitGo has kicked off the claimOwnership function for the New Big DAO multisig here: https://etherscan.io/tx/0xe1a0069a37390e287ca399a4ee79036660ac235da08cb86753045fe5d9e97acc (txId: `0`)
> 
> From your NEW Big DAO address, please broadcast the following HEX DATA:
`0xc01a8c840000000000000000000000000000000000000000000000000000000000000000` 
> 
> to the Big DAO Contract Address: `0xB33f8879d4608711cEBb623F293F8Da13B8A37c5`
>
> You can verify this HEX yourselves by going to the Big DAO Contract page: https://etherscan.io/address/0xB33f8879d4608711cEBb623F293F8Da13B8A37c5#writeContract and using function “5. confirmTransaction” and input the txid `0`. See following screenshot:
>
> ![photo_2022-12-15 23 42 51](https://user-images.githubusercontent.com/2835259/207936321-16431ff5-7fc9-4be8-9c6a-91dafabaaab1.jpeg)
> 
> Please confirm once completed. We need 6 more votes (BitGo + Kyber have are in)

**Comment by gosuto-inzasheru** [comment]
queued transaction `0` on the new wbtc dao msig calls `0x4e71e0c8` (`claimOwnership`) on `0xCA06411bd7a7296d7dbdd0050DFc846E95fEBEB7`, the wbtc token controller. on that controller, the new wbtc dao msig is indeed the `pendingOwner`: 

<img width="404" alt="Screenshot 2022-12-15 at 23 51 28" src="https://user-images.githubusercontent.com/2835259/207937773-6d227ab0-afe1-43ab-a8f5-9815bbd43b55.png">

the proposed calldata signs this queued tx:
```
>>> wbtcdao = Contract('0xB33f8879d4608711cEBb623F293F8Da13B8A37c5')
>>> wbtcdao.decode_input('0xc01a8c840000000000000000000000000000000000000000000000000000000000000000')
("confirmTransaction(uint256)", [0])
```

**Comment by jalbrekt85** [comment]
```py
Events In This Transaction
--------------------------
├── MultiSigWalletWithDailyLimit (0xB33f8879d4608711cEBb623F293F8Da13B8A37c5)
│   └── Confirmation
│       ├── sender: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
│       └── transactionId: 0
│   
└── Gnosis Safe (0x86cbD0ce0c087b482782c181dA8d191De18C8275)
    └── ExecutionSuccess
        ├── txHash: 0x8eec7418a48dd0c67a0b8f3234048b2f8837e6d8913702e752249139096fdcfb
        └── payment: 0

https://dashboard.tenderly.co/jcalbrecht/project/simulator/64bd3715-d1f6-4203-8d00-8821c3759131
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x13796ac40>,
│   'safe_address': '0x86cbD0ce0c087b482782c181dA8d191De18C8275',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000007900b33f8879d4608711cebb623f293f8da13b8a37c500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024c01a8c84000000000000000000000000000000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 216872,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 431,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
```

**Comment by jalbrekt85** [comment]
https://etherscan.io/tx/0xbee7980690f0a669ac4d9f83b4688b1d4e3ecd597038f60eb312ba38e4189824
