### ISSUE TITLE
`Balancer` currently only queries legacy gauge factory

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1034]
however, some new gauges are deployed through the new factory (`0xf1665E19bc105BE4EDD3739F88315cC699cc5b65`), which, i guess, supports creating capped gauges.

best way i found to find the active gauge is to query the subgraph instead of the legacy factory (since it doesnt support `getPoolGauge` anymore:
```
{
  pools(
    where: {
      poolId: "0xe340ebfcaa544da8bb1ee9005f1a346d50ec422e000200000000000000000396"
    }
  ) {
    preferentialGauge {
      id
    }
  }
}
```
ref: https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-gauges

**Comment by shuklaayush** [comment]
Via http
```
curl -X POST https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-gauges -d '{"query":"{pools(where:{poolId:\"0xe340ebfcaa544da8bb1ee9005f1a346d50ec422e000200000000000000000396\"}) {preferentialGauge {id}}}"}'
```
