### ISSUE TITLE
execute on TCD-22 completely

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1042]
- [x] #1043
- [x] Divest 77k + 19k bveCVX to stablecoins to extend runway by ~10%
- [x] Unlock 70% of the available CVX at each unlock window
- [x] sell 5k per week at market + the remainder at +5%, +7,5%, +10% ladder orders rolling
- [x] balance out the bvecvx/cvx pool in the first week, approximately 7k cvx needed
- [x] whitelist voter into `bbveCVX_CVX_f` sett via techops

most has been implemented already in #1033

additional features being added through #1041 

ref: https://forum.badger.finance/t/22-cvx-divestment-2/5786

**Comment by petrovska-petro** [comment]
voter whitelisted in sett tx: https://etherscan.io/tx/0xda81ae63539f435bed2a7bd7c016771dab132ded74b421ae191574159a337926

**Comment by gosuto-inzasheru** [comment]
first round of ladders left `17682` cvx unsold

**Comment by gosuto-inzasheru** [comment]
looks like we will have to wait until 2023-02-09 before all bvecvx will be withdrawn, unless a big deposit comes along and we act on that.

**Comment by gosuto-inzasheru** [comment]
note: perform on flashbot rpc

**Comment by gosuto-inzasheru** [comment]
last divestment :) https://etherscan.io/tx/0x9de38947a2850a355e501b9881650d4dc6722489477367098ef2859750435f2a

**Comment by gosuto-inzasheru** [comment]
still need to post selling of last ~3k of cvx in voter to cowswap

**Comment by gosuto-inzasheru** [comment]
sold!
