### ISSUE TITLE
Update aura section in address book

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1046]
Address may have changed due to the migration

https://docs.aura.finance/developers/deployed-addresses

**Comment by gosuto-inzasheru** [comment]
is this not a part of #1038 already?

**Comment by petrovska-petro** [comment]
> is this not a part of #1038 already?


def looks like a good pr to smash this together when it moves out of draft, i see in that pr missing some other addrs update such as the latest `ClaimZap` contract . cc: @sajanrajdev

**Comment by sajanrajdev** [comment]
Good call, I can add

**Comment by petrovska-petro** [comment]
resolved in #1038
