### ISSUE TITLE
Bridge badger to arbitrum tree

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1054]
prev #810 

Currently the arb tree has a deficit of 7 weeks (weekly emissions were 852 badger). They're cancelled in #945 

Bridge a total of 852 * 7 = 5964 badger

**Comment by petrovska-petro** [comment]
safe tx: https://gnosis-safe.io/app/eth:0x042B32Ac6b453485e357938bdC38e0340d4b9276/transactions/multisig_0x042B32Ac6b453485e357938bdC38e0340d4b9276_0xcdac0adad43a4f690df32fd3c475f6421a06cb8753075190e526ce68c55b5b2d

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x8d55aa69fc969f11aba06cac79d92fcb35c15c6a70cbf700b12d3726f33d404a

**Comment by petrovska-petro** [comment]
bridging tx to arb: https://etherscan.io/tx/0x8577842fc3771ed783cba3596d50aaf20c2a115e009dcb68394ad1718d6b0db4

**Comment by petrovska-petro** [comment]
arb topup tx: https://arbiscan.io/tx/0x139df60cabf7de2fb9bf0e8fc61c469cd8f121db254a98940742fbbbd9faca5a
