### ISSUE TITLE
offboard techops signer `0x96AC69183216074dd8CFA7A380e873380445EaDc`

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-multisig#1055]
`0x96AC69183216074dd8CFA7A380e873380445EaDc` for `0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16`

Checklist

# Multisigs
### Ethereum
- [x] techops_multisig: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
- [x] treasury_vault_multisig: 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e
- [x] treasury_voter_multisig: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b

### Fantom
- [x] techops_multisig: 0x781E82D5D49042baB750efac91858cB65C6b0582

### Arbitrum
- [x] techops_multisig: 0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C
- [x] dev_multisig: 0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F
- [x] ~~dev_multisig_deprecated: 0x468A0FF843BC5D185D7B07e4619119259b03619f~~ (will be solved through #1105)

### Polygon
- [x] techops_multisig: 0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327

### Optimism
- [x] techops_multisig: 0x8D05c5DA2a3Cb4BeB4C5EB500EE9e3Aa71670733

# Access Control

see #1139 

# Gas Station
 - [x] remove from watchlist

**Comment by dapp-whisperer** [comment]
see transactions added manually via ui: https://gnosis-safe.io/app/eth:0x86cbD0ce0c087b482782c181dA8d191De18C8275/transactions/queue

**Comment by sajanrajdev** [comment]
@dapp-whisperer, address is signer in the following multisigs:

### Ethereum
```
Signer found on techops_multisig: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
Signer found on treasury_vault_multisig: 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e
Signer found on treasury_voter_multisig: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b
```
### Fantom
```
Signer found on techops_multisig: 0x781E82D5D49042baB750efac91858cB65C6b0582
```
### Arbitrum
```
Signer found on techops_multisig: 0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C
Signer found on dev_multisig: 0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F
Signer found on dev_multisig_deprecated: 0x468A0FF843BC5D185D7B07e4619119259b03619f
```
### Polygon
```
Signer found on techops_multisig: 0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327
```
### Optimism
```
Signer found on techops_multisig: 0x8D05c5DA2a3Cb4BeB4C5EB500EE9e3Aa71670733
```

**Comment by gosuto-inzasheru** [comment]
also needs to be removed from gas station

**Comment by shuklaayush** [comment]
Roles also have to be revoked from `keeperAccessControl`, `registryAccessControl` etc.

**Comment by dapp-whisperer** [comment]
Checklist

# Multisigs
### Ethereum
- [ ] techops_multisig: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
- [ ] treasury_vault_multisig: 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e
- [ ] treasury_voter_multisig: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b

### Fantom
- [ ] techops_multisig: 0x781E82D5D49042baB750efac91858cB65C6b0582

### Arbitrum
- [ ] techops_multisig: 0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C
- [ ] dev_multisig: 0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F
- [ ] dev_multisig_deprecated: 0x468A0FF843BC5D185D7B07e4619119259b03619f

### Polygon
- [ ] techops_multisig: 0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327

### Optimism
- [ ] techops_multisig: 0x8D05c5DA2a3Cb4BeB4C5EB500EE9e3Aa71670733

# Access Control

### Keeper ACL
- [ ] ETH 0x711A339c002386f9db409cA55b6A35a604aB6cF6
- [ ] FTM 0x0680b32b52C5ca8C731490c0C576337058f39337
- [ ] ARB 0x265820F3779f652f2a9857133fDEAf115b87db4B
- [ ] POLY ?
- [ ] OPT ?

### Registry ACL
- [ ] ETH 0x1233A3885b8015f369287Ca53716F66cc755651c
- [ ] FTM 0x8E2d940114f4882Acc139A84362a45C5cA4B6a0d
- [ ] ARB 0x6847a17C4AC30AFd24FDcb2422DA01207C480a79
- [ ] POLY 0x9026B950085dcc72269cAc4a8Aa8385cc8A774Cd
- [ ] OPT 0xEa8567d84E3e54B32176418B4e0C736b56378961

### Guardian ACL
(will be batched into another ticket)

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0xbbe5d53f7faaeabbb53f1976d5cf52dfa7e5ce92b92a6fc2af03d79464f28c63#eventlog
```
RemovedOwner (0x96AC69183216074dd8CFA7A380e873380445EaDc)
```

**Comment by gosuto-inzasheru** [comment]
arb1:dev_multisig_deprecated appears to be a non gnosis safe.

suggesting to sunset it instead; add dev msig as signer, set threshold to 1 and remove all other signers: #1105

**Comment by gosuto-inzasheru** [comment]
offboarded, except for from acl. see #1139 for that
