### ISSUE TITLE
Week 51 Incentives: HH Balancer 4,982 Badger on BADGER/wBTC and 11,018 BADGER on BADGER/rETH

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1059]
[Hidden Hand]
https://hiddenhand.finance/balancer?slug=balancer

[Option]
4,982 Badger to the WBTC-20% BADGER-80% pool
11,018 Badger to the rETH-50% BADGER-50% pool

[Authorization]
https://discord.com/channels/743271185751474307/842854176488161311/1050065277913681971
https://discord.com/channels/743271185751474307/1054458215703777410/1055341961818685441

**Comment by petrovska-petro** [comment]
verify prop hash against: https://hhand.xyz/proposal/balancer

```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                    balance_before               balance_after               balance_delta
symbol                                                                                    
BADGER  118,337.076135482698591090  102,337.076135482698591090  -16,000.000000000000000000
```

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x9a9222bb96b2169df0adea9ba9575ffc9ba82257d99d6ae97cb023ce03daa999
