### ISSUE TITLE
offboard techops signer `0xE8eA1D8B3a5A4CEC7E94AE330fF18E82B5D22fA6`

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1068]
### Multisigs
- [x] eth:techops_multisig - remove
  - [x] posted
  - [x] executed
- [x] eth:treasury_ops_multisig - replace with `0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16`
  - [x] posted
  - [x] executed
- [x] bsc:dev_multisig - replace with `0x54cF9dF9dCd78E470AB7CB892D7bFbE114c025fc`
  - [x] posted
  - [x] executed
- [x] poly:techops_multisig - replace with `0xE78e3E1668D42FfCa767e22e57d7d249e02B5F0e`
  - [x] posted
  - [x] executed
- [x] arbitrum:techops_multisig - replace with `0xE78e3E1668D42FfCa767e22e57d7d249e02B5F0e`
  - [x] posted
  - [x] executed
- [x] ftm:dev_multisig - replace with `0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16`
  - [x] posted
  - [x] executed
- [x] ftm:techops_multisig - replace with `0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16`
  - [x] posted
  - [x] executed
- [x] op:techops_multisig - replace with `0xE78e3E1668D42FfCa767e22e57d7d249e02B5F0e`
  - [x] posted
  - [x] executed
### Access Control
Not on Keeper nor Registry ACLs

### Gas Station
- [x] remove from watchlist

**Comment by gosuto-inzasheru** [comment]
@sajanrajdev or @petrovska-petro can you amend the access control section above with needed changes there?

**Comment by petrovska-petro** [comment]
> eth:treasury_ops_multisig - replace with 0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16

https://etherscan.io/tx/0x3688dc07b916d276eead92d007e2273ef1fdc64ecce949c123a918db6c98f063

**Comment by gosuto-inzasheru** [comment]
ftm dev exec: https://ftmscan.com/tx/0x27dfcfae0cee4267595a65f8ec99808405776eb6fa6de5210966ca6784aa1466#eventlog
