### ISSUE TITLE
offboard techops signer `0xC69Fb085481bC8C4bfF99B924076656305D9a25D`

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1070]
### Multisigs
- [x] eth:techops_multisig - replace with `0xaaE2051c2f74920C6662EF5C9B0d602C40D36DF4`
  - [x] posted
  - [x] execd
- [x] eth:treasury_ops_multisig - replace with `0xD10617AE4Da733d79eF0371aa44cd7fa74C41f6B`
  - [x] posted
  - [x] execd
- [x] bsc:dev_multisig - replace with `0xaF94D299a73c4545ff702E79D16d9fb1AB5BDAbF` and increase threshold to 3
  - [x] posted
  - [x] execd
- [x] poly:techops_multisig - replace with `0xaaE2051c2f74920C6662EF5C9B0d602C40D36DF4`
  - [x] posted
  - [x] execd
- [x] arbitrum:techops_multisig - replace with `0xaaE2051c2f74920C6662EF5C9B0d602C40D36DF4`
  - [x] posted
  - [x] execd
- [x] arbitrum:dev_multisig - replace with `0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187`
  - [x] posted
  - [x] execd
- [ ] ftm:dev_multisig - replace with `0xaaE2051c2f74920C6662EF5C9B0d602C40D36DF4`
  - [x] posted
  - [ ] execd
- [x] ftm:techops_multisig - replace with `0xaaE2051c2f74920C6662EF5C9B0d602C40D36DF4`
  - [x] posted
  - [x] execd

### Access Control
Not on Keeper nor Registry ACLs

### Gas Station
- [x] remove from watchlist

**Comment by petrovska-petro** [comment]
> eth:treasury_ops_multisig - replace with 0xD10617AE4Da733d79eF0371aa44cd7fa74C41f6B

https://etherscan.io/tx/0x3688dc07b916d276eead92d007e2273ef1fdc64ecce949c123a918db6c98f063

**Comment by gosuto-inzasheru** [comment]
arb1 dev msig: https://arbiscan.io/tx/0xb11172f429f52bdf4f4db84d87fa2545bf7aeb959b9e61643bfaa011eba2ced9#eventlog

**Comment by gosuto-inzasheru** [comment]
ftm dev misg exec: https://ftmscan.com/tx/0x27dfcfae0cee4267595a65f8ec99808405776eb6fa6de5210966ca6784aa1466#eventlog
