### ISSUE TITLE
Upkeep in bveCVX module failing - short gas limit

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1074]
Upkeep at: https://automation.chain.link/mainnet/14270489937535892760600590423564455802049459622872924518248134412357549386527

Despite that the upkeep conditions is True atm, cl registry keeper is not triggering the job. CL devs feedback is to consider bumping up the gas limit, since it will be the last trigger, safe to settle it at 1.6M

**Comment by petrovska-petro** [comment]
tx got exec succesfully https://etherscan.io/tx/0xb33b0cb47ca18e7fdd16fc7be44154e33c50455d1056f9d1b7967f8b13549e0d#ContentPlaceHolder1_collapseContent

still valuable to have the script in the repo

**Comment by gosuto-inzasheru** [comment]
so issue can be closed i guess?

**Comment by petrovska-petro** [comment]
> so issue can be closed i guess?

sure
