### ISSUE TITLE
month 2: emissions bcvxcrv?

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1090]
for month 1 see: #933

**Comment by petrovska-petro** [comment]
currently under discussion in treasury decisions

**Comment by petrovska-petro** [comment]
tcd outcome

<img width="917" alt="Screenshot 2023-02-13 at 18 18 58" src="https://user-images.githubusercontent.com/84875062/218431805-a4147e5b-592d-40d0-845e-ca329fc0eb78.png">

ref: https://discord.com/channels/1011322803414388897/1011333638044008548/1072595593794428998
