### ISSUE TITLE
Missing rebate user 0x185Ab1f85DbD952f150cD44bFE08b7eFBcc86ADE, 5 BADGER

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#11]
The user was entitled from the following addr:

https://etherscan.io/address/0xD0cf0a50568D84842A2995ef6D94577C3dA5f777

But, moved the funds via:

https://etherscan.io/tx/0x2314489d0537bc5feed3b3da5af37f068b22b95a62f858912cbfcf36a1f21e08

The queries did not catch-up his address to be included on the cycles, but the user in his defense mentioned that only wanted to migrate from MM to ledger, since we did not track transfers, but **only** direct interaction with sett, zapper etc

We are airdropping 5 BADGER to his ledger wallet directly as a custom cycle for 1 address will be a waste of gas

**Comment by petrovska-petro** [comment]
Posted nonce 198

Events:

```
Events In This Transaction
--------------------------
├── Badger (0x3472A5A71965499acd81997a54BBA8D852C6E53d)
│   └── Transfer
│       ├── from: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
│       ├── to: 0x185Ab1f85DbD952f150cD44bFE08b7eFBcc86ADE
│       └── value: 5000000000000000000
│   
└── Gnosis Safe (0x86cbD0ce0c087b482782c181dA8d191De18C8275)
    └── ExecutionSuccess
        ├── txHash: 0x23682b1dd09dc6db411d33691e723032c94c4321e5f8e78eb164f25814b095c9
        └── payment: 0
```

**Comment by jorijnsmit** [comment]
https://gnosis-safe.io/app/eth:0x86cbD0ce0c087b482782c181dA8d191De18C8275/transactions/0x02bfd27dc02bcec724e6bba775c324262c4146867e7f2b9d41f49a0a80061f63
