### ISSUE TITLE
week 7: bi-weekly direct transfer into remBADGER sett

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#112]
- Send 11,538.461538 BADGER to [remBADGER sett](https://etherscan.io/address/0x6af7377b5009d7d154f36fe9e235ae1da27aea22)

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xc600c1a297733019c8da7ce8c73521f15cd74b417015d1dec6edce0e3516dd18
