### ISSUE TITLE
week 8: harvesting strategy for convex-frax tcl

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1124]
prev #1118

**Comment by gosuto-inzasheru** [comment]
https://dashboard.tenderly.co/gosuto/msig-sims/simulator/6e96901d-195f-47b8-b9dc-efb5e29a0681

**Comment by jalbrekt85** [comment]
https://etherscan.io/tx/0x284886942d8cb291bff568e07f910ffb2887fd7f9441b8a8b59e68e159cf3b62
