### ISSUE TITLE
Infrastructure ACL Restructuring

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1139]
## Context
A new blueprint has been stablished for the distribution of permissions on the several ACL contracts across the infrastructure. These changes were decided with both security and ease of maintenance in mind. The premise is to stablish the same degree of security between ACLs and Multisigs where appropriate. ROLES must be removed, granted or swapped as needed to accomplish the following setup for each ACL on each chain:

### BadgerTree
<html>
<body>
<google-sheets-html-origin>

Role | Public Label
-- | --
DEFAULT_ADMIN_ROLE | dev_multisig
ROOT_PROPOSER_ROLE | ops_botsquad_cycle0
ROOT_VALIDATOR_ROLE | ops_root-validator_v3
PAUSER_ROLE | guardian
UNPAUSER_ROLE | dev_multisig

</body>
</html>

### Rewards Logger
<html>
<body>
<google-sheets-html-origin>

Role | Public Label
-- | --
DEFAULT_ADMIN_ROLE | dev_multisig
MANAGER_ROLE | techops_multisig

</body>
</html>

### Guardian
<html>
<body>
<google-sheets-html-origin>

Role | Public Label
-- | --
DEFAULT_ADMIN_ROLE | dev_multisig
APPROVED_ACCOUNT_ROLE | All Tech Ops signers
APPROVED_ACCOUNT_ROLE | ops_executor7 (Backup)
APPROVED_ACCOUNT_ROLE | `0x4666e94300429C6d3340449bC828E4218F360672` (Backup)
APPROVED_ACCOUNT_ROLE | `0x211b82242076792A07C7554A5B968F0DE4414938` (Backup)

</body>
</html>

### Keeper ACL
<html>
<body>
<google-sheets-html-origin>

Role | Public Label
-- | --
DEFAULT_ADMIN_ROLE | dev_multisig
EARNER_ROLE | All Tech Ops signers
HARVESTER_ROLE | All Tech Ops signers
TENDER_ROLE | All Tech Ops signers

</body>
</html>

### registryAccessControl
<html>
<body>
<google-sheets-html-origin>

Role | Public Label
-- | --
DEFAULT_ADMIN_ROLE | techops_multisig
DEVELOPER_ROLE | All Tech Ops signers

</body>
</html>

## NOTES
- Some changes are yet to be executed on a few multisigs to reflect the desired signers Blueprint, tickets for these changes have already been created. If fetching signers from the multisigs' directly via script, make sure that the signers match the desired final state for them.
- Accounts should all be from hardware wallets and should be a part of the ETH gas station to be ready to act as needed (specially for the guardian). If any TechOps signer currently has their hot wallet deployer as part of the gas station they should switch that for their hardware wallet EOA instead. These signers can then transfer ETH to their deployers as needed for deployment/testing activities as needed.
- Using the same accounts for ACLs and Multisigs will increase the ease of maintenance and monitoring on permissions all across the infra.

## Chains Checklist
- [x] Ethereum Mainnet Techops
- [x] Ethereum Mainnet Devmsig
- [x] Arbitrum Techops
- [ ] Arbitrum Devmsig
- [x] Fantom Techops
- [ ] Fantom Devmsig
- [x] Polygon Techops
- [ ] Polygon Devmsig
- [ ] Optimism Techops

**Comment by petrovska-petro** [comment]
## Notes for implementation (WIP)

- currently the `ADMIN_ROLE` in `rewardsLogger` in mainnet is `ops_multisig_old` needs to be granted to `dev_multisig` for enable atomic tx from dev

**Comment by petrovska-petro** [comment]
# Polygon reqs tx

- https://polygonscan.com/tx/0xdcc23b0583e85e6565b0104c1dac5b84376a5b42e7e429f6c5c8b7235485391d
- https://polygonscan.com/tx/0x4891dc4d53b7a8cbbbec5d1fd8db998d903405dd44145314344827d86278d966

**Comment by petrovska-petro** [comment]
posted acl config for `registryAccessControl` mainnet: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/68e83cd9-8151-4d97-84b3-e65969e41987

**Comment by petrovska-petro** [comment]
posted acl config for `registryAccessControl` arbitrum : https://dashboard.tenderly.co/public/safe/safe-apps/simulator/baf26df4-f571-443a-8c17-a36566c7f8c3

**Comment by petrovska-petro** [comment]
posted acl config for registryAccessControl ftm

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x162243e80>,
│   'safe_address': '0x781E82D5D49042baB750efac91858cB65C6b0582',
│   'to': '0x10B62CC1E8D9a9f1Ad05BCC491A7984697c19f7E',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008f7008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000e78e3e1668d42ffca767e22e57d7d249e02b5f0e008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c00000000000000000000000095c1d2014909c04202fa73820b894b45f054f25e008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000fa5bb45895cb3c0ae5b1583fe068f009a48f0187008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000000a9af7faba0d5df7a8c881e1b9cd679ee07af8a2008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000008938bf50d1a3736bda413510688834540858daea008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000ac7b5f4e631b7b5638b9b41d07f1ebed30753f16008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000aae2051c2f74920c6662ef5c9b0d602c40d36df4008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000da25ee226e534d868f0dd8a459536b03fee9079b008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000ee8b29aa52dd5ff2559da2c50b1887adee257556008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000283c857ba940a61828d9f4c09e3fcee2e7aef3f7008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000ef42d748e09a2d9ef89238c053ce0b6f00236210008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000c6a902de22b10cb176460777ce6e7a12a6b6ae5a008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000d49177c4cf4b8ccdf58475c9a155c4cd8b9f3f31008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000007140b5254d80154f9fc5f86054efb210f3a1e2c6008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000009082b0dd7a72c328833e6461965c9e91cf59a960000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 24,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

**Comment by petrovska-petro** [comment]
posted acl config for `registryAccessControl` optimism : https://dashboard.tenderly.co/public/safe/safe-apps/simulator/c92485c3-7d59-41e0-ac1d-473ea556f7f5

**Comment by petrovska-petro** [comment]
posted acl config for registryAccessControl polygon: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/ac148e16-b677-4cb8-ac4c-7e837258953b

**Comment by petrovska-petro** [comment]
> posted acl config for `registryAccessControl` mainnet: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/68e83cd9-8151-4d97-84b3-e65969e41987

https://etherscan.io/tx/0x345331a267dce5b49fdb99b602b632fb7a0e21cfce74141cdc59cca2087c7276#eventlog

**Comment by petrovska-petro** [comment]
> posted acl config for registryAccessControl polygon: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/ac148e16-b677-4cb8-ac4c-7e837258953b

https://polygonscan.com/tx/0xb5f7ef68112c6c700bd021c1a739e71a63ee47908e737f397e63a66916c5a8a8

**Comment by petrovska-petro** [comment]
> posted acl config for registryAccessControl ftm
> 
> ```
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x162243e80>,
> │   'safe_address': '0x781E82D5D49042baB750efac91858cB65C6b0582',
> │   'to': '0x10B62CC1E8D9a9f1Ad05BCC491A7984697c19f7E',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008f7008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000e78e3e1668d42ffca767e22e57d7d249e02b5f0e008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c00000000000000000000000095c1d2014909c04202fa73820b894b45f054f25e008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000fa5bb45895cb3c0ae5b1583fe068f009a48f0187008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000000a9af7faba0d5df7a8c881e1b9cd679ee07af8a2008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000008938bf50d1a3736bda413510688834540858daea008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000ac7b5f4e631b7b5638b9b41d07f1ebed30753f16008e2d940114f4882acc139a84362a45c5ca4b6a0d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000442f2ff15d4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000aae2051c2f74920c6662ef5c9b0d602c40d36df4008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000da25ee226e534d868f0dd8a459536b03fee9079b008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000ee8b29aa52dd5ff2559da2c50b1887adee257556008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000283c857ba940a61828d9f4c09e3fcee2e7aef3f7008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000ef42d748e09a2d9ef89238c053ce0b6f00236210008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000c6a902de22b10cb176460777ce6e7a12a6b6ae5a008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c000000000000000000000000d49177c4cf4b8ccdf58475c9a155c4cd8b9f3f31008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000007140b5254d80154f9fc5f86054efb210f3a1e2c6008e2d940114f4882acc139a84362a45c5ca4b6a0d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044d547741f4504b9dfd7400a1522f49a8b4a100552da9236849581fd59b7363eb48c6a474c0000000000000000000000009082b0dd7a72c328833e6461965c9e91cf59a960000000000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 0,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 24,
> │   '_safe_version': '1.3.0',
> │   '_chain_id': None
> }
> ```

https://ftmscan.com/tx/0x6d94acc70820cef5f2ce5a65920ff48e291f4ade838701d7b699e815de3df2a0/internal-transactions

**Comment by petrovska-petro** [comment]
> posted acl config for `registryAccessControl` optimism : https://dashboard.tenderly.co/public/safe/safe-apps/simulator/c92485c3-7d59-41e0-ac1d-473ea556f7f5

https://optimistic.etherscan.io/tx/0x90e1f0247f4e602d07488df2a2a74e14713fd53d1eac13a0180dfc9197a49924

**Comment by petrovska-petro** [comment]
>  **mainnet**: ADMIN_ROLE in rewardsLogger is ops_multisig_old needs to be granted to dev_multisig to enable atomic tx

https://etherscan.io/tx/0xe9cc5abe41ec0414b9a5cff007dec22485d7878df83e59dcefef49516e07975a#eventlog

**Comment by gosuto-inzasheru** [comment]
ah looks like this needs to happen before #1105 @petrovska-petro?

**Comment by petrovska-petro** [comment]
> #1105

yes, planning to start posting these ones these weeks now that the ops_msig blocking is resolved

**Comment by petrovska-petro** [comment]
acl reorg badgertree mainnet: https://dashboard.tenderly.co/testing-ape/project/simulator/ae0cbf05-8815-4d09-b566-f4e74e1e29bf

**Comment by petrovska-petro** [comment]
acl reorg rewardslogger mainnet: https://dashboard.tenderly.co/testing-ape/project/simulator/07ee723b-9381-4646-a2c7-1db044b458af

**Comment by petrovska-petro** [comment]
acl reorg guardian mainnet: https://dashboard.tenderly.co/testing-ape/project/simulator/eccff1ef-b055-4c3e-ab7b-d16eee77cd0a

**Comment by petrovska-petro** [comment]
acl reorg keeperAccessControl only `DEFAULT_ADMIN_ROLE` scope: https://dashboard.tenderly.co/testing-ape/project/simulator/f26cbde6-9397-4a6a-b82a-b6d08d169130/logs

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x2c94d9953f89533554ee53a49bd8820c8f5f2e7ac160dc90cbc43cc3e715ef89
https://etherscan.io/tx/0x7e0846f15b9232d94056d63c2e4b5d91980c45acd764e98e6d69a74572c46ddf
https://etherscan.io/tx/0x39723cfee81377b0dddf4ef658db403328165e948bef2c39bb853dc96de1d186
https://etherscan.io/tx/0x93ffc741b782c63b1d6b93556b349873ea95fb0fe413a0d077e83934d89d7808

**Comment by petrovska-petro** [comment]
Arbitrum req tx in dev_msig deprecated: https://arbiscan.io/tx/0xd21a7ea9e9c9931a0766ad00bcc4e35cd50c45fa34c1b6f6c63771353c3a54ce

```
Calldata for granting ADMIN_ROLE to dev_msig=0x2f2ff15d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b364bab258ad35dd83c7dd4e8ac78676b7aa1e9f. 
Target:0xDb0C3118ef1acA6125200139BEaCc5D675F37c9C
```

**Comment by gosuto-inzasheru** [comment]
arb1 nonce 203 exec: https://arbiscan.io/tx/0x985f896914865c1b51b7faf2e570892b58bf467f03b53b298147b27c0aac4efb#eventlog

**Comment by sajanrajdev** [comment]
Due to deprecation, and given that there's no TVL on any sidechain, it was decided to not pursue these efforts further and, instead only make the changes outlined and tracked on the following [ticket](https://github.com/Badger-Finance/badger-multisig/issues/1316).
