### ISSUE TITLE
week 8: migrate badgerreth liq to new gauge

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1145]
balancer's bip 177 (https://forum.balancer.fi/t/bip-177-great-migration-wave-1/4364) replaced the badgerreth with a new one; one where the reentrancy vuln is fixed (and thus the recovery mode is again turned off).

rewards to the old gauge end feb23.

once available, we need to unstake from aura, withdraw liq to underlying, deposit into the new style bpt and stake on the new gauge through aura again.

new gauge address pushed here: #1143 

new bpt is deployed here i believe: https://etherscan.io/tx/0x5888eabcf59da32fb9fa2afbc3a424d54b9d8b29bb747b486318f2659019a5db

**Comment by jalbrekt85** [comment]
~$30k rewards that can be claimed on migration, how should they be processed?
<img width="1055" alt="Screenshot 2023-02-19 at 5 13 23 PM" src="https://user-images.githubusercontent.com/33009898/219981123-94269da0-8d63-47f9-ac81-760bc2a05122.png">

**Comment by gosuto-inzasheru** [comment]
i would say the same as the current weekly harvest script processes them?

maybe even ignore the rewards for now and run the harvest script after that?

**Comment by gosuto-inzasheru** [comment]
posted to nonce 120: https://dashboard.tenderly.co/gosuto/msig-sims/simulator/ef7f3bf4-c875-484e-a33b-58c4078f0435

**Comment by jalbrekt85** [comment]
https://etherscan.io/tx/0x8a627dff715f1ec6d629de5917361bb2573ecccf1ee2ecd22f2069d448337894
