### ISSUE TITLE
Add DOLA and FRAX to the Rari pool

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-multisig#115]
Add the below assets to Rari Fuse (collateral + lending)
We are in conversations with Inverse and Frax to provide more liquidity to our Rari pool.  This is in preperation for the addition of bveCVX, and eventually also bibBTC and btricrypto collateral assets.

As such, we would like to add the following 2 tokens to our Rari Pool(https://app.rari.capital/fuse/pool/22)
FRAX
DOLA 

For these additions use the following settings, which are our current standards for stable coins on Rari:
Collateral Factor: 75%
Reserve Factor: 15%
Rate Curve: JumpRateModel_FEI_DAI

![image](https://user-images.githubusercontent.com/11885129/153096145-7e2321c6-8507-4ed8-811b-64d51e2eaca1.png)

https://discord.com/channels/743271185751474307/842854176488161311/940387887562756166

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xc73379940c19ecb502df63e28e84b23ece933f928722cf72cbc5802f99cbc471
