### ISSUE TITLE
week 27: top-up gas station

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1169]
prev #1050

**Comment by gosuto-inzasheru** [comment]
this is done in advance to prepare for the quarter, so week 27

**Comment by sajanrajdev** [comment]
To analyze new requirements post deprecation and transition

**Comment by sajanrajdev** [comment]
New watchlist set: https://etherscan.io/tx/0x283d102589750f0c3721990f12a013fcf568e3c5ff9dfc829550d1aaaa49635b

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0xbe71a698c381b54fe3a41420d8e8acfd394f521f7974ed1a5b302b875aa62321
