### ISSUE TITLE
FeeCollector module integration

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1198]
Module review has being [completed](https://github.com/Badger-Finance/badger-safe-modules/issues/2), ready to be integrated into trops

Steps:

- [x] Deployment
- [ ] Increase thresholds in gas st for mngr.
- [x] Script integration to enable module in trops and adds tokens fees to process
- [x] Enable module in `trops`
- [ ]  Add the module as a member in upkeep mngr

**Comment by petrovska-petro** [comment]
contract deploy at: https://etherscan.io/address/0x24a6108D1985B44130f68550C9c43d556720CF17

**Comment by petrovska-petro** [comment]
contract deploy at: https://etherscan.io/address/0x24a6108D1985B44130f68550C9c43d556720CF17

**Comment by petrovska-petro** [comment]
gas snap for `performUpkeep`

<img width="713" alt="Screenshot 2023-03-27 at 21 45 45" src="https://user-images.githubusercontent.com/84875062/227944114-2e6ffbe2-a0bb-4368-a878-55a392fc4bdf.png">

rounding towards 1.3M for four tokens: 2 aura vaults and 2 curve lps

**Comment by gosuto-inzasheru** [comment]
i would add more gas in case more lps or tokens get added

**Comment by gosuto-inzasheru** [comment]
i would add more gas in case more lps or tokens get added

**Comment by petrovska-petro** [comment]
add module and config module adding fee tokens tx: https://dashboard.tenderly.co/testing-ape/project/simulator/9e7d2c7b-7aa3-4c21-9787-ef95489f5c43

**Comment by petrovska-petro** [comment]
> add module and config module adding fee tokens tx: https://dashboard.tenderly.co/testing-ape/project/simulator/9e7d2c7b-7aa3-4c21-9787-ef95489f5c43

https://etherscan.io/tx/0xfe826eeb8db82cbb7174ba5a429c0fdf04c8c138042a202a45265f2997fa5291

**Comment by petrovska-petro** [comment]
gas st list update:

```
                                                            addrs      min_bals   min_top_ups
ops_deployer           0xDA25ee226E534d868f0Dd8a459536b03fEE9079b  5.000000e+18  5.000000e+17
ops_deployer2          0xeE8b29AA52dD5fF2559da2C50b1887ADee257556  2.000000e+18  5.000000e+17
ops_deployer3          0x283C857BA940A61828d9F4c09e3fceE2e7aEF3f7  2.000000e+18  5.000000e+17
ops_deployer4          0xef42D748e09A2d9eF89238c053CE0B6f00236210  2.000000e+18  5.000000e+17
ops_deployer8          0x9082b0dD7A72c328833e6461965C9E91Cf59a960  2.000000e+18  5.000000e+17
ops_executor6          0x66496eBB9d848C6A8F19612a6Dd10E09954532D0  1.000000e+18  5.000000e+17
ops_executor13         0x95c1D2014909c04202fa73820B894b45F054F25e  1.000000e+18  5.000000e+17
ops_executor14         0xE78e3E1668D42FfCa767e22e57d7d249e02B5F0e  1.000000e+18  5.000000e+17
ops_executor15         0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16  1.000000e+18  5.000000e+17
ops_root-validator_v3  0xcA63a374ec5f41dA402dD17b6d90DddFea3d64C4  2.000000e+18  5.000000e+17
ops_botsquad           0xF8dbb94608E72A3C4cEeAB4ad495ac51210a341e  5.000000e+18  5.000000e+17
ops_botsquad_cycle0    0x1a6D6D120a7e3F71B084b4023a518c72F1a93EE9  2.000000e+18  5.000000e+17
upkeep_manager         0x4c02f0160Dc0387b13bCb5e1728C780649E109Ac  5.000000e+18  4.000000e+18
```

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x93fc3aee8633b134ed2ad5d3c54ab26d3dcedf8cd559546415fec16e5a12cd42

**Comment by petrovska-petro** [comment]
1st upkeep tx: https://etherscan.io/tx/0x8f4656fefc1ad5306f487fd8cbf1107e7726a23e812f8bc894254218d098a328
