### ISSUE TITLE
Avatars Integration (Aura & Convex)

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1207]
Code for [aura-avatar](https://github.com/Badger-Finance/badger-avatars/tree/main/src/aura) and [convex-avatar](https://github.com/Badger-Finance/badger-avatars/tree/main/src/convex) reached a solid state to enter into a testing phase program

Integration steps:

- [x] Avatar deployments with trops as owner
- [x] Scripting seeding and emerg. wds
- [x] Mirror final setup - test all operations in trops phase in actual mainnet, have multiple aura positions (grab small amounts from treasury if needed)
- [x] Upkeep mngr. upkeep registration
- [x] Update `sellBpsAuraToUsdc` via [set](https://etherscan.io/address/0xc4035528fd975f68efff5d0a726fdc6975a57ba4#code#F16#L240) (#1236) 
- [x] Emerg. wd test run
- [x] Deposit 1/10 funds of aura vault positions in the ecosystems to the aura avatar
- [x] Transfer ownership
- [x] Avatar pid migration (pid: 18 and 19)
- [ ] second independent audit of the avatar contracts
- [ ] deposit of 9/10 of deposits of the funds into the aura avatar 
- [ ] deposit all convex position into the convex avatar as final step

**Comment by petrovska-petro** [comment]
aura avatar: https://etherscan.io/address/0x1ab341f6b71721a25ac092fd41480299843be7fa
convex avatar: https://etherscan.io/address/0x21a940194bdfea81c7802da85e5fcb56dffe0739

**Comment by petrovska-petro** [comment]
replicate locally by running `forge test --gas-report` in [main](https://github.com/Badger-Finance/badger-avatars)

<img width="1007" alt="Screenshot 2023-03-30 at 21 30 14" src="https://user-images.githubusercontent.com/84875062/228836771-02b9efaa-1d6d-42ed-9103-991f296556e7.png">

<img width="946" alt="Screenshot 2023-03-30 at 21 30 35" src="https://user-images.githubusercontent.com/84875062/228836804-d056c6ba-aabe-42af-a283-b8897ce839a7.png">

**Comment by petrovska-petro** [comment]
```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                    balance_before               balance_after               balance_delta
symbol                                                                                    
BADGER  122,982.666934232015207430  110,525.919529387725069126  -12,456.747404844290138304
WBTC          7.315455060000000000        6.520121030000000000       -0.795334030000000000
WETH         24.177862869926418600       18.817365681668008104       -5.360497188258410496
USDC     70,919.902738000000000000   60,919.902738000000000000  -10,000.000000000000000000 
```

https://dashboard.tenderly.co/testing-ape/project/simulator/829af37d-80f7-4e12-9bfe-d64f7578675a

**Comment by gosuto-inzasheru** [comment]
upkeep registrations: https://etherscan.io/tx/0xe188174f51410d8058c20ae89987e0a6fd194a05ce1976df7d1e9772961bb9ea

**Comment by petrovska-petro** [comment]
setting aura sell to usdc 100%: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/024c655c-cd5d-427b-ad3f-1b0de70c1d52

**Comment by petrovska-petro** [comment]
> setting aura sell to usdc 100%: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/024c655c-cd5d-427b-ad3f-1b0de70c1d52

https://etherscan.io/tx/0xe3cda93f3364566cb1ad4e4e97e031344d9e9cf1928a45a6c1bcd76164d62f24

**Comment by petrovska-petro** [comment]
emerg. wd snap:

```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                                   balance_before             balance_after             balance_delta
symbol                                                                                               
20WBTC-80BADGER             26.162120351642551540  1,308.106017582123551540  1,281.943897230481000000
50rETH-50BADGER              5.223425614551673620    261.171280727583353620    255.947855113031680000
40WBTC-40DIGG-20graviAURA    0.174995704695160060      8.749785234757974060      8.574789530062814000
BADGERFRAX-f               117.167510038614241229  5,858.381597286568241229  5,741.214087247954000000 
```

**Comment by petrovska-petro** [comment]
> https://dashboard.tenderly.co/public/safe/safe-apps/simulator/66fcec6a-645b-40bc-ae44-a320aedef6c9/logs
> 
> emerg. wd snap:
> 
> ```
> snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
>                                    balance_before             balance_after             balance_delta
> symbol                                                                                               
> 20WBTC-80BADGER             26.162120351642551540  1,308.106017582123551540  1,281.943897230481000000
> 50rETH-50BADGER              5.223425614551673620    261.171280727583353620    255.947855113031680000
> 40WBTC-40DIGG-20graviAURA    0.174995704695160060      8.749785234757974060      8.574789530062814000
> BADGERFRAX-f               117.167510038614241229  5,858.381597286568241229  5,741.214087247954000000 
> ```

https://etherscan.io/tx/0x216f8240a0fca2f65b056c9e1dea415310f97c715d0a0f3cb44bf7f51eaf6f9a

**Comment by petrovska-petro** [comment]
> https://dashboard.tenderly.co/public/safe/safe-apps/simulator/66fcec6a-645b-40bc-ae44-a320aedef6c9/logs
> 
> emerg. wd snap:
> 
> ```
> snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
>                                    balance_before             balance_after             balance_delta
> symbol                                                                                               
> 20WBTC-80BADGER             26.162120351642551540  1,308.106017582123551540  1,281.943897230481000000
> 50rETH-50BADGER              5.223425614551673620    261.171280727583353620    255.947855113031680000
> 40WBTC-40DIGG-20graviAURA    0.174995704695160060      8.749785234757974060      8.574789530062814000
> BADGERFRAX-f               117.167510038614241229  5,858.381597286568241229  5,741.214087247954000000 
> ```

deposit back into avatars: https://etherscan.io/tx/0xad92ee194c5086e1353dfd09759e9340c31fc7a6c7e3e10e0c3cc7d255721b08

**Comment by petrovska-petro** [comment]
snap in trops of receiving 1/3 of funds: 

```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                                 balance_before              balance_after              balance_delta
symbol                                                                                               
20WBTC-80BADGER            0.000000000000000000  57,821.899911405475000000  57,821.899911405475000000
50rETH-50BADGER            0.000000000000000000  22,710.680714808530000000  22,710.680714808530000000
40WBTC-40DIGG-20graviAURA  0.000000000000000000     188.796276235718070000     188.796276235718070000
```

**Comment by petrovska-petro** [comment]
1/10 aura tcl funds transfer to trops tx: https://etherscan.io/tx/0x75bb4cad9f7e1490dd0feca3989500d8a687c602f6747f9623d455838af36551

**Comment by petrovska-petro** [comment]
> 1/10 aura tcl funds transfer to trops tx: https://etherscan.io/tx/0x75bb4cad9f7e1490dd0feca3989500d8a687c602f6747f9623d455838af36551

depositing 1/10 in the aura avatar tx: https://etherscan.io/tx/0x77d1cb507d3f104390c3384a579cb18c9291bebb95fe61436181cde89ca6a018

**Comment by petrovska-petro** [comment]
ownership transfer tx: https://etherscan.io/tx/0x8ce2dd9501c548d0eeea05a3b6b0849ba7f44fdf2d31d174415d1ed9f76ca72f#eventlog

**Comment by petrovska-petro** [comment]
avatar aura migration tx: https://etherscan.io/tx/0x929f60b8b6a0c5a8f92ea200ea8b455783306891bf92d6185289a2595987bb47

**Comment by petrovska-petro** [comment]
closing in favor of #1338
