### ISSUE TITLE
Voter msig requires claiming back `BADGER`

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1284]
Last round we voted on badgerwbtc with VP and also there was incentive in that gauge, it will require to be claim back

**Comment by gosuto-inzasheru** [comment]
id recommend waiting with this until there are clearer plans from influence on this situation. it might occur again; better to batch then imo.

**Comment by petrovska-petro** [comment]
trops snap after transfering:

```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
                   balance_before              balance_after             balance_delta
symbol                                                                                
USDC    92,761.503241000000000000  94,820.322207000000000000  2,058.818966000000000000
BADGER  14,661.756813947164740714  18,144.211195373303089109  3,482.454381426138348395 
```

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x5d3483b35851b10676fc2977df254bf20b6ba4a88210923080b807d96c655a4c
