### ISSUE TITLE
review implications of setting gov to timelock for setts v1.5

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1291]
there are some second thoughts around changing the governance of the 1.5 vaults to a timelocked process.

due to the architecture of the v1.5 vaults, if governance is indeed changed to the timelock, _all_ actions on the vault will need to go through timelock. can this introduce unnecessary complications?

- ticket: https://github.com/Badger-Finance/badger-multisig/issues/634
- script: https://github.com/Badger-Finance/badger-multisig/pull/1007

providing this ticket for @dapp-whisperer to do a review and start a convo

@GalloDaSballo it would be great if you could give your thoughts as well

**Comment by sajanrajdev** [comment]
@gosuto-inzasheru given the deprecation plan, and the burning of keys in the near future I think we should close this ticket.
