### ISSUE TITLE
migrate treasury balancer positions to new pids

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1298]
should all be possible to script atomically, except for the ownership transfer:
> - upgrade the avatar to support the new pids
> - (move ownership of avatar from trops to vault)
> - withdraw badgerwbtc and wbtcdiggaura from old pids for both vault and avatar
> - deposit 100% of both positions into the upgraded avatar, which will deposit both into their new pids

ref: https://github.com/Badger-Finance/Badger-Project-Planning/issues/137#issuecomment-1580884476

related to avatar integration ticket: #1207

**Comment by gosuto-inzasheru** [comment]
note: wait for dd on reason for new pids

also not migrate through avatars, stick to 90/10 split

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0xcb9ffe61e4dd2c224418e18077c72103a86e87a7b2b11ad20c4da1c8fd981762
