### ISSUE TITLE
week3: process expired unlocks on bvecvx vault

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#13]
1: https://github.com/GalloDaSballo/vested-cvx/blob/b475e7fab0913f89d8406b02b8f1caaf5afc3f37/tests/test_roleplay_unlock.py#L84
2: `strat_proxy.manualSendCVXToVault({"from": governance})`

-> Earn every Wednesday at 23:47 -> All funds in vault are locked
-> Unlock on Thursday (manual operation may not be able to estimate by the minute) -> All funds unlocked are sent to vault
-> This means we give the 6 days + unlock window we agreed on with users

**Comment by jorijnsmit** [comment]
think deadline is next week thursday, but having the script tested and reviewed would be nice to have this week.

**Comment by jorijnsmit** [comment]
posted nonce 987, https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/0x0c0ef1b818633a5958dc8ea6dad3e0b79d0fa1524bdc78c3a67435829e6eb84b :
```
snapshot result for 0xfd05D3C7fe2924020620A8bE4961bBaA747e6305:
              balance_before              balance_after              balance_delta
symbol                                                                            
CVX     0.006295640935761957  70,778.570845258333457529  70,778.564549617397695572 
```

**Comment by Tritium-VLK** [comment]
**Note that this ticket should happen at a predictable time.  @wasabiboat should put out comms in the necxt hour stating this will happen between Noon and 1PM EST on Friday.**

Please try to ensure it happens at this time.  I am working with @GalloDaSballo to reduce the security requirements on calling this function, but for now we will need to time this to happen predictably at the same time each week (fridays at noon for now)

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x2f8351174a10f19156b88b6674c7030336b5f4cf49a947aaca7836fb6e4f6ad9
