### ISSUE TITLE
Deploy fDOLA-22/fFRAX-22 tokens so that they can be added to Rari pool

### ISSUE THREAD

**Issue by jalbrekt85** [Badger-Finance/badger-multisig#133]
In order to add DOLA/FRAX to the Badger Fuse pool for #115 , fDOLA-22 & fFRAX-22 contracts must be deployed. Deployment and parameters can be done [here](https://rari-git-allow-deploys-rari-capital.vercel.app/fuse/pool/22/edit )

I will be able to move funds to my EOA wallet tomorrow to cover deployment costs if needed. Here are the parameters to double check. `Admin` on both are [`dev_multisig`](https://etherscan.io/address/0xB65cef03b9B89f99517643226d76e286ee999e77)

- <img width="250" alt="Screen Shot 2022-02-15 at 4 11 19 PM" src="https://user-images.githubusercontent.com/33009898/154158411-045ce79b-cbb3-444c-9f1c-63d9f32e0ad1.png">
- <img width="250" alt="Screen Shot 2022-02-15 at 4 16 52 PM" src="https://user-images.githubusercontent.com/33009898/154158972-252763e7-59ce-49be-b803-0c1231716245.png">

**Comment by mitche50** [comment]
@petrovska-petro - did you have any luck in generating this transaction?

**Comment by petrovska-petro** [comment]
> @petrovska-petro - did you have any luck in generating this transaction?

Passed the message to ape pod, I do not have access to my deployer at the moment

**Comment by jorijnsmit** [comment]
quoting from #141:
> _**closes #133**_ so that assets can be added to our fuse pool. deployment is execed via my mm wallet: [jcalb.eth](https://etherscan.io/address/0xa0c60a3bf0934869f03955f3431e044059b03e62)
> ### Addresses
> 
> **fFRAX-22:**
>     * deployment tx - https://etherscan.io/tx/0xd460d0caaa634b325acfbdcc70005d730a7a89e67edab1818e5ad4fa4eba200e
>     * contract -  https://etherscan.io/address/0x60fb6aecf861e3f16f7a4dcaddf8d8820244a1cd
> 
> **fDOLA-22 :**
>     * deployment tx - https://etherscan.io/tx/0x63d5b37a0533ad9124293e6805e772fd706854a3449ea94a3a8850a8232e877b
>     * contract - https://etherscan.io/address/0x5117d9453cc9be8c3fbfba4ae3b858d18fe45903

hereby confirming deployed contracts:
- were deployed by jcalb.eth
- have correct settings by running a for loop over all attributes and comparing to fbadger22
- have correct underlying (dola and frax)

@petrovska-petro wanna do a quick check as well before we close this one?

**Comment by petrovska-petro** [comment]
> https://etherscan.io/address/0x5117d9453cc9be8c3fbfba4ae3b858d18fe45903

Config looks good. CF factor pendant of setting up via #143 

<img width="992" alt="Screenshot 2022-02-17 at 13 52 00" src="https://user-images.githubusercontent.com/84875062/154485540-e614fb6a-70da-4af7-bc9b-cead2e050f61.png">

Underlying checks out:

[DOLA](https://etherscan.io/address/0x865377367054516e17014CcdED1e7d814EDC9ce4)
[FRAX](https://etherscan.io/address/0x853d955aCEf822Db058eb8505911ED77F175b99e)

**Comment by jorijnsmit** [comment]
```
"fFRAX-22": "0x60fb6aecf861e3f16f7a4dcaddf8d8820244a1cd",
"fDOLA-22": "0x5117D9453cC9Be8c3fBFbA4aE3B858D18fe45903",
```
