### ISSUE TITLE
Deprecate Treasury Avatars

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1338]
It has been decided to deprecate the avatars in favor of a reduction in cadance for TCL harvesting
- [x] Migrate liquidity back to treasury Vault
- [x] Adjust upkeep manager to stop automation

**Comment by petrovska-petro** [comment]
upkeep cancelation sim: https://dashboard.tenderly.co/testing-ape/project/simulator/ca70ea10-265f-47a2-8c6c-f335292e85a7

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x8ed0e6809e2bf458c1d02ba170faf20e136201f847f0c1dcf3352bbb1da22bf3#eventlog
