### ISSUE TITLE
HH Balancer Incentives: 2023 Week 30 Closing July 26 

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1348]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
16,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
![image](https://github.com/Badger-Finance/badger-multisig/assets/113713830/0d04427e-1138-423e-b420-46737adea948)

**Comment by sajanrajdev** [comment]
Executed: https://etherscan.io/tx/0xb39a80f48dfa5fac2a8a385b5094fcbb4da38d66128c6580032be73eb5f695e2
