### ISSUE TITLE
Buy 200K BADGER with up to 500K USDT

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1364]
As per TCD 35

**Comment by petrovska-petro** [comment]
1st order filled: https://explorer.cow.fi/orders/0x0b9c16045eddab19bc3f5f588860e1722110652790313b78541768740e047199d0a7a8b98957b9cd3cfb9c0425abe44551158e9e64dbf533?tab=overview

**Comment by sajanrajdev** [comment]
Laddered orders filled: 

![Image](https://github.com/Badger-Finance/badger-multisig/assets/25463788/b5a8c553-003d-472b-a3c5-a5f2a7b93edb)

https://explorer.cow.fi/orders/0xb5ffb11f4dc524aa74e79a90185dafa1a7f1c6b5f47bda82fd7992cd0d39de7cd0a7a8b98957b9cd3cfb9c0425abe44551158e9e64e757d6
https://explorer.cow.fi/orders/0x98fe1dd535ade1ae2445ffb431c597110fe727dc6c899107927e04aec8019e7ad0a7a8b98957b9cd3cfb9c0425abe44551158e9e64e757d8
https://explorer.cow.fi/orders/0xeeb6812b731858b01ad05b22d5ab143e4385c60dbe54835a05d72db067ec5febd0a7a8b98957b9cd3cfb9c0425abe44551158e9e64e757da

**Comment by sajanrajdev** [comment]
Result: 45,596.765 + 47,285.7247 + 47,549.5357 + 64,151.1085 = 204583.1339 BADGER for 450K USDT
