### ISSUE TITLE
HH Balancer Incentives: 2023 Week 34 Closing Aug. 23rd

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1371]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
16,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
Standing council allocation

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x55297c1208a17d850e3992956bd78de323302e3cb11c8035e44e78d7a89766a8

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x55297c1208a17d850e3992956bd78de323302e3cb11c8035e44e78d7a89766a8
