### ISSUE TITLE
HH Balancer Incentives: 2023 Week 36 Closing Sept. 6

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1384]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
12,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
Standing council allocation

**Comment by sajanrajdev** [comment]
https://etherscan.io/address/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
