### ISSUE TITLE
HH Balancer Incentives: 2023 Week 38 Closing Sept. 20 

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1398]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
12,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
Standing council allocation

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0xf7574b2f1caa490147cad89981d98443fa44f24c2fd095e904a705129548e1c5
