### ISSUE TITLE
HH Balancer Incentives: 2023 Week 40 Closing Oct. 4

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1409]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
10,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
https://discord.com/channels/743271185751474307/842854176488161311/1156730235241365544

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0xfbf0cd2ab979fb31b5ec4e29f9d9e266e5fc4c4a6ab25ac14369d42cfcd46f45
