### ISSUE TITLE
Deployment: fFRAX-22 & fDOLA-22 Rari Fuse assets

### ISSUE THREAD

**Issue by jalbrekt85** [Badger-Finance/badger-multisig#141]
***closes #133*** so that assets can be added to our fuse pool. deployment is execed via my mm wallet: [jcalb.eth](https://etherscan.io/address/0xa0c60a3bf0934869f03955f3431e044059b03e62)

### Addresses

**fFRAX-22:**

- deployment tx - https://etherscan.io/tx/0xd460d0caaa634b325acfbdcc70005d730a7a89e67edab1818e5ad4fa4eba200e
- contract -  https://etherscan.io/address/0x60fb6aecf861e3f16f7a4dcaddf8d8820244a1cd 

**fDOLA-22 :**

- deployment tx - https://etherscan.io/tx/0x63d5b37a0533ad9124293e6805e772fd706854a3449ea94a3a8850a8232e877b
- contract - https://etherscan.io/address/0x5117d9453cc9be8c3fbfba4ae3b858d18fe45903

**Comment by jorijnsmit** [comment]
closing due to duplicating issue in #133; discussion continues [there](https://github.com/Badger-Finance/badger-multisig/issues/133#issuecomment-1042714048).
