### ISSUE TITLE
Modify Payments multisig signers

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1425]

**Comment by ICEBADGER** [comment]
@sajanrajdev 

<html>
<body>


ACTION | CURRENT | END STATE
-- | -- | --
SWAP | 0xe7bab002A39f9672a1bD0E949d3128eeBd883575 | 0x54cF9dF9dCd78E470AB7CB892D7bFbE114c025fc
SWAP | 0xe24b6bF43d4624B2E146D3F871e19b7ECb811208 | 0x6dd1e005c90cedbea99909fa9ff82497e2424357
ADD ALTERNATE | N/A | 0xD10617AE4Da733d79eF0371aa44cd7fa74C41f6B
  |   |  
KEEP | 0x5A6a00d4fCE5DdF1a14868bb27340b542421EDe5 | 0x5A6a00d4fCE5DdF1a14868bb27340b542421EDe5
KEEP | 0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16 | 0xaC7B5f4E631b7b5638B9b41d07f1eBED30753f16
KEEP | 0x66496eBB9d848C6A8F19612a6Dd10E09954532D0 | 0x66496eBB9d848C6A8F19612a6Dd10E09954532D0


</body>
</html>

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x0850f3fda48cd8a3f2ab4216278e026b882971285e9a1c23b7a974c56f8de7c9
