### ISSUE TITLE
HH Balancer Incentives: 2023 Week 42 Closing Oct. 18

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1428]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
8,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
https://discord.com/channels/743271185751474307/842854176488161311/1161301925187309762

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x63b143f013c3242bf04f827765cbff3ba10f1d9203089c8b87f67cded907bc2f
