### ISSUE TITLE
week 43: incentives Paladin Liquis

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1432]
Prev #1429 

Requires opening a quest at: https://app.warden.vote/quest/

To be posted using the traditional: `brownie run scripts/badger/bribe_ecosystems`

Params for this round will be:

```
    badger_bribe_in_liquis=600,
    duration_paladin_quest=1
    reward_per_vote_liquis=0.00025
```

**Comment by petrovska-petro** [comment]
[ref](https://docs.google.com/spreadsheets/d/136NQDQP5WrSSGUd3gM0xeaHlCwDPsoamwypmAMqqm1w/edit#gid=1470184092) to params

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x7b2e23b0d3363cb2ea05d7e2ccad7ce9499f523329da32fa5e8ef199d039929c



![Image](https://github.com/Badger-Finance/badger-multisig/assets/25463788/6afc7061-7d62-4d4b-8b73-349199c76ccf)
