### ISSUE TITLE
HH Balancer Incentives: 2023 Week 44 Closing Nov. 1

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#1438]
[Hidden Hand]
https://hiddenhand.finance/balancer

[Option]
6,000 Badger to the rETH-50% BADGER-50% pool

[Authorization]
https://discord.com/channels/743271185751474307/842854176488161311/1167081043422105658

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x8e80954c88f85af529eca682759d1a7a442dfa5d5481f05d167043c631ca02e7
