### ISSUE TITLE
Execute on TCD-40 - LPs Divestment

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1456]
Following our discussions in the Treasury call the yield on the Badger/rETH and Badger/USDC/FRAX has declined and our market sentiment has changed. The funds should be withdrawn from the LPs and the assets will remain in the Treasury vault until further decisions are made.

 Full proposal: 
https://docs.google.com/document/d/1SZgTMXEbYvICjGWCXaceARKlE0d2F5v9qD3eL148rzU/edit?usp=sharing

 Reward: Decrease Treasury protocol risk, reduce IL, exposure to favorable market conditions, extend stablecoin and BADGER runways

 Risk: A reduction in onchain liquidity, increase in overall market risk of Treasury portfolio

**Comment by sajanrajdev** [comment]
BADGER/rETH withdrawal executed; https://etherscan.io/tx/0xb41320e076de83d51e5a01c24427364183011f74647b41a4c815f3067de97a23

**Comment by petrovska-petro** [comment]
```
snapshot result for 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e:
                      balance_before                 balance_after               balance_delta
symbol                                                                                        
BADGER  1,820,000.611850437924064689  1,978,169.783550234216851975  158,169.171699796292787286
FXS             0.801190044181349960        246.119076540011479589      245.317886495830129629
USDC       42,433.728164000000000000    209,859.885959000000000000  167,426.157795000000000000
FRAX            0.000000000000000000    373,468.718097621733052893  373,468.718097621733052893 
```

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x581cd27abc25235f4e54002b646aaf4a00172cc7af595a9ab44740e54c63589c
