### ISSUE TITLE
Transfer `LIQ` from vault to trops

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1462]
After discussions with the influence pod, team agreed to use as incentives `LIQ` token in the liquis HH marketplace moving forward instead of $badger

[discussion](https://discord.com/channels/1011322803414388897/1037746924511576114/1180120143779610654)

Todo:

- move at least $10k equivalent of $liq to trops msig

**Comment by sajanrajdev** [comment]
Will handle via UI on signing day before the incentives are posted.

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x1b5c627199dea26974cd02412498d738ae15d768624a3115c77a5801d40a79a6
