### ISSUE TITLE
trops $liq top-up from vault

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1485]
For handling incentives tickets #1480 & #1481 requires an injection of $liq capital 

currently the balance sits at 60k and for liquis marketplace alone we will need at least ~78k as per [gsheet](https://docs.google.com/spreadsheets/d/136NQDQP5WrSSGUd3gM0xeaHlCwDPsoamwypmAMqqm1w/edit#gid=1343908694)

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0xa1ff2c9bf17a7ccc25753ad8aaa79587d4fea5bf5080acd3e23069d4ac85e2d6
