### ISSUE TITLE
Send 6,603.2083 BADGER to techops

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#154]
As per #153 send refund from vault to techops to have usual backup badger balance ready over there for either bridging to Arb or similar ops

**Comment by petrovska-petro** [comment]
@jorijnsmit should do we add this transfer into a week 8 csv file together with emissions or addendum to the week_6_7 csv file to handle everything on it?

**Comment by jorijnsmit** [comment]
yes, guess we will have a week_6_7_8 airdrop :)

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xc600c1a297733019c8da7ce8c73521f15cd74b417015d1dec6edce0e3516dd18
