### ISSUE TITLE
set up ebtc limit buy order at .99

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1549]
this is for the migration of the last wbtc/badger tranche; currently at 28.87wbtc/9badger

cow swap limit order details:
- limit price: `.99`
- receive at least: 28.87 / 2 = `14.435ebtc`
- expiry: 6 months
- set approval to relayer for `15wbtc`

<img width="868" alt="Screenshot 2024-07-22 at 09 33 47" src="https://github.com/user-attachments/assets/02d23558-c1a2-489c-ae96-7cf5b6249326">

**Comment by sajanrajdev** [comment]
https://explorer.cow.fi/orders/0x1653df3c22815780d6d4ea44ee60960898807fb558eb1fb45063e54a8fc5ff7ad0a7a8b98957b9cd3cfb9c0425abe44551158e9e679c43d0?tab=overview
