### ISSUE TITLE
transfer grants budget to gitcoin treasury

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#1551]
250k usdc to `0xde21F729137C5Af1b01d73aF1dC21eFfa2B8a0d6`

address can be verified as such on etherscan

**Comment by sajanrajdev** [comment]
Extra confirmation: https://manual.gitcoin.co/introduction-and-overview/dao-finances

**Comment by sajanrajdev** [comment]
https://etherscan.io/tx/0x35dd42f04cf61fed196ff341cd15dacb65be4ed074fe76b57bb537ca816c5fc4
