### ISSUE TITLE
Fork ETH gas refill script for FTM

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-multisig#157]
With the launch of FTM imminent we will need to maintain and refill a number of keepers on FTM which has gas costs associated with it.  In order to do so, we will need to fork the ETH gas refill script to function on FTM and refill keepers as necessary.

Identifiable tasks:
- [ ] - Create forked script from [eth gas script](https://github.com/Badger-Finance/badger-multisig/blob/main/scripts/badger/refill_gas.py)
- [ ] - Set prefix to identify FTM specific operational addresses
- [ ] - Identify msig funds will be coming from
- [ ] - Set minimum amount of FTM addresses should have

**Comment by jorijnsmit** [comment]
solved through #173
