### ISSUE TITLE
change fuse pool's $dola cf from 75% to 85%

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-multisig#178]
Inverse has requested that we make their token unusable as collateral in our Rari pool.  It seems they just want people to borrow against their provided liquidity, not for people to be using it as collateral:

![image](https://user-images.githubusercontent.com/11885129/155592169-e1fe9505-d33b-4cdb-810c-2a106c3fc242.png)

Requested by @GalloDaSballo and confirmed by @hmmmason who are both in contact with Inverse.

@hmmmason would be awesome to get inverse to comment on this ticket confirming this request.

**Comment by patbInverse** [comment]
Hi @Tritium-VLK patb here from Inverse ... we'd actually prefer to set CF at 85%. Thanks!

**Comment by jorijnsmit** [comment]
posted nonce 1010: https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/0x591bc7e90311d394096bffd1cfd852561adb1de40128f3b30f288d598645923b
```
Events In This Transaction
--------------------------
├── IRariComptroller (0xe3952d770FB26CC61877CD34Fbc3A3750881e9A1)
│   └── NewCollateralFactor
│       ├── cToken: 0x5117D9453cC9Be8c3fBFbA4aE3B858D18fe45903
│       ├── oldCollateralFactorMantissa: 750000000000000000
│       └── newCollateralFactorMantissa: 850000000000000000
│   
└── Gnosis Safe (0xB65cef03b9B89f99517643226d76e286ee999e77)
    └── ExecutionSuccess
        ├── txHash: 0x859d69992dba8db38fd73d627ed901522ddf055e137c9beb486bd98cab55774d
        └── payment: 0

{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x121519cd0>,
│   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000009900e3952d770fb26cc61877cd34fbc3a3750881e9a100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044e4028eee0000000000000000000000005117d9453cc9be8c3fbfba4ae3b858d18fe459030000000000000000000000000000000000000000000000000bcbce7f1b15000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 161630,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 1010,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
```

**Comment by Tritium-VLK** [comment]
It seems like there is no clear consensus/reason for this and it was more just some random requests from random people that changed.  Adivse closing this ticket as not done.  If the CF can be 0 or 85% the current 75% that is our standard is fine until someone can provide some sort of a slightly better justification for why it can change.

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x05c548e7cbfc311385c5e88f84319b7afecd7d0bfbb711ee15ecb1a7b31885b6#eventlog

todo: compare to other pools and come up with a policy as to what cf to use for what type of asset.
