### ISSUE TITLE
catch up on bcvxcrv deficit in tree

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#185]
still some deficit left after #109; `-57952.796688766975` according to check_claimable script.

treasury ops should have enough after running #56

**Comment by petrovska-petro** [comment]
ref, last checked on 26th Feb:https://docs.google.com/spreadsheets/d/1zhtFontkfP6HfqIR6CM4UZIUulceixw7DXPwHzRPZl4/edit#gid=0

**Comment by petrovska-petro** [comment]
covered deficit for now

tx: https://etherscan.io/tx/0x09788201f141ca9ddf0af7cfde3f2c5e9678646ae304b29d4dfbbbdf94bba4c3

will become again a issue by the 10th March ~991 deficit
