### ISSUE TITLE
confirm we can claim rewards and unstake $work on polygon

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#188]
eg https://polygonscan.com/tx/0xf5aa3f15a65e266ac868905e48539f4ce1ab066c589b11015de6053249213698

**Comment by jorijnsmit** [comment]
suggesting to reduce the scope of this ticket to unstaking only (1 $work). claiming will need more documentation from opolis.

**Comment by jalbrekt85** [comment]
> suggesting to reduce the scope of this ticket to unstaking only (1 $work). claiming will need more documentation from opolis.

agreed

**Comment by jorijnsmit** [comment]
https://polygonscan.com/tx/0x8819e00a19713b0b67148233997829aa2e40dc3d25291a4d865ec4af896a6aee
