### ISSUE TITLE
bridge 1100 badger to arbitrum for last bit of q1 emissions

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#191]
We need *1100.4016999999994* in techops for covering [emissions Q1](https://github.com/Badger-Finance/badger-multisig/issues/189#issuecomment-1055343229) in Arbitrum, but always is good to have slightly more over there for any quick operation that may arise as techops promptness is faster

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x74435d0ba26960f05826cce26041170e27d87ef78780803773ed5300f1ddf3a7
