### ISSUE TITLE
deploy a multisig on fantom; starting with treasury_ops

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#20]
fantom foundation has forked gnosis safe and is providing multisigs on their network: https://fantom.foundation/blog/fantom-safe-multisig-wallet-now-available/

gnosis-safe is not planning on supporting this chain in the next couple of months due to workload. we need it before that.

deploy treasury_ops_multisig on fantom, using the same signers.

**Comment by Hal69k** [comment]
Deployed 

Public address : 0x337a32FA07eD51Aae1a7923427063B299A2307bd

https://safe.fantom.network/#/safes/0x337a32FA07eD51Aae1a7923427063B299A2307bd/balances

same signers as treasury_ops_multisig
