### ISSUE TITLE
Refill Arb Cycle Bot

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-multisig#201]
Send 0.5e to address `0x1a6D6D120a7e3F71B084b4023a518c72F1a93EE9` to refill the Arbitrum cycle bot

**Comment by mitche50** [comment]
Submitted nonce 28

**Comment by jorijnsmit** [comment]
https://arbiscan.io/tx/0xc2529d6b80c341f731c217c472baf5a8460f7b1551f31fcf02038d6ededf6447
