### ISSUE TITLE
send enough btc to trops to finalise lowest univ3 range

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#205]

**Comment by petrovska-petro** [comment]
- From processing got `10.265788774908901127 bibbtc` [tx](https://etherscan.io/tx/0x367d42bd81945f5f2b391faf7efcc091f98f8fdbc755572496865135492ef8e3). ~ 10.337 wbtc

- Minted NFT with `30.46831914 wbtc`

- Missing still  `16.934680860000004 wbtc` to handle #32

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x74435d0ba26960f05826cce26041170e27d87ef78780803773ed5300f1ddf3a7
