### ISSUE TITLE
Include signing & exec methods using hardware wallet in greatape

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#216]
- [x] Test in rinkeby safe flow

- [x] Include sign with frame in great ape and posting signature

- [x] Exec method thru frame

**Comment by petrovska-petro** [comment]
Comments:

- Signing from brownie/frame was smooth. Only caveat is that if signing occurs after the tx posting, we will need to specify in `multisend_from_receipts` method the **safe nonce**, so it produces the same safe tx hash and points to the right one [here](https://github.com/banteg/ape-safe/blob/master/ape_safe.py#L253)

- Exec was getting stuck with `GS020`. Ref: https://github.com/gnosis/safe-contracts/blob/main/docs/error_codes.md#general-signature-validation-related . Despite of being able to exec with MM and two owners signatures being correct. Likely related with the gas estimation for the thru this [method](https://github.com/banteg/ape-safe/blob/master/ape_safe.py#L350). Workaround for the payload...?

Txs rinkeby, 2/2 policy:

- https://rinkeby.etherscan.io/tx/0xe6543e4111293add22062b96c3cf6b3f0eac1be0d3af765e4d37521a01b493d5

**Comment by jorijnsmit** [comment]
solved in #220
