### ISSUE TITLE
Add bveCVX into rari pool

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#226]
- [x] Deploy fbveCVX-22 with reserve factor 0%, admin fee 0%, admin as dev_msig and interest model jumpratemodel_fei_dai

- [x] Include the following check-up/changes on the methods in rari class to [enable](https://github.com/Badger-Finance/badger-multisig/blob/main/great_ape_safe/ape_api/rari.py#L19)/[disable](https://github.com/Badger-Finance/badger-multisig/blob/main/great_ape_safe/ape_api/rari.py#L24) borrowing of an asset

Add an extra check-up that if an asset whenever is going to be switch from disable to enable that the reserve factor is set to default to 15%  (but allow to pass this as arg), but on the case of going from enable to disable to set the reserve factor to 0%. Since, it does not make sense to have a reserve factor > 0, while an asset is not borrowable as nothing will accrue in the reserve.

- [x] Support the market and set CF to 50%, in this occasion atomically disable borrowing thru [controller](https://etherscan.io/address/0x94b2200d28932679def4a7d08596a229553a994e#code#F8#L1207). `fbveCVX-22`should **not** be borrowable

**Comment by petrovska-petro** [comment]
safe tx: https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/0x407d4c2babf671323d177d76b153af973c37f2e29224f2eca2d0389b161e6ef1

**Comment by jorijnsmit** [comment]
fyi this got rejected because dev msig had to execute on setting cf for $dola to 0.

**Comment by jorijnsmit** [comment]
```
Events In This Transaction
--------------------------
├── IRariComptroller (0xe3952d770FB26CC61877CD34Fbc3A3750881e9A1)
│   └── ActionPaused
│       ├── cToken: 0x26F6F27fDBc3B9cDe4b1943b1c07606CAF2c4C6C
│       ├── action: Borrow
│       └── pauseState: True
│   
├── Badger Pool Badger Vested Escrow Convex Token (0x26F6F27fDBc3B9cDe4b1943b1c07606CAF2c4C6C)
│   ├── AccrueInterest
│   │   ├── cashPrior: 0
│   │   ├── interestAccumulated: 0
│   │   ├── borrowIndex: 1000000000000000000
│   │   └── totalBorrows: 0
│   └── Failure
│       ├── error: 10
│       ├── info: 84
│       └── detail: 0
│   
└── Gnosis Safe (0xB65cef03b9B89f99517643226d76e286ee999e77)
    └── ExecutionSuccess
        ├── txHash: 0x69f7c55e6274a956db7d0215c5f90d72f9e9ee923a28c074986440fcc04e10d5
        └── payment: 0

{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x10a6b95e0>,
│   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000011200e3952d770fb26cc61877cd34fbc3a3750881e9a10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004418c882a500000000000000000000000026f6f27fdbc3b9cde4b1943b1c07606caf2c4c6c00000000000000000000000000000000000000000000000000000000000000010026f6f27fdbc3b9cde4b1943b1c07606caf2c4c6c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002491dd36c600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 236621,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 1033,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
```

**Comment by petrovska-petro** [comment]
market creation: https://etherscan.io/tx/0xd09662f129686fbe814fa5f8889385afc39f03072dc50f63090a269b496e9641

disable borrowing: https://etherscan.io/tx/0xc6902bcd08e2475b4c44065431b206de07f96afb6be4af2f2277ab7655e673c8
