### ISSUE TITLE
add GAC to registry key value store

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-multisig#229]
globalAccessControl  = `0x9c58B0D88578cd75154Bdb7C8B013f7157bae35a`

**Comment by sajanrajdev** [comment]
Exeucted: https://etherscan.io/tx/0x59613995ea9cf73877c516bce09833add66784a76112ff616889fb188765ed1f

![image](https://user-images.githubusercontent.com/25463788/165136790-a232675b-8035-4f6b-ad95-0df5300b2c74.png)
