### ISSUE TITLE
Swipe PNT and BOR from deprecated and live strats

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#247]
### Context ###

The pBTC and oBTC strats received, on top of their regular rewards PNT and BOR, respectively, in small amounts. This amounts accumulated to more than 100k in value all together. It should be a good time swipe these off of the strategies, specially the deprecated ones so that these can be fully disregarded. 

### Technical Details ###

Deprecated strats:
pBTC: https://etherscan.io/address/0x1c1fd689103bbfd701b3b7d41a3807f12814033d#readProxyContract
oBTC: https://etherscan.io/address/0x2bb864cdb4856ab2d148c5ca52dd7ccec126d138#readProxyContract

Live strats:
pBTC: https://etherscan.io/address/0xA9A646668Df5Cec5344941646F5c6b269551e53D
oBTC: https://etherscan.io/address/0x5dd69c6D81f0a403c03b99C5a44Ef2D49b66d388

The following functions can be called on their respective controllers to swipe these assets:
```
    function inCaseTokensGetStuck(address _token, uint256 _amount) public {
        _onlyGovernanceOrStrategist();
        IERC20Upgradeable(_token).safeTransfer(msg.sender, _amount);
    }

    /// @dev Transfer an amount of the specified token from the controller to the sender.
    /// @dev Token balance are never meant to exist in the controller, this is purely a safeguard.
    function inCaseStrategyTokenGetStuck(address _strategy, address _token)
        public
    {
        _onlyGovernanceOrStrategist();
        IStrategy(_strategy).withdrawOther(_token);
    }
```    

Governance on the controllers is the Timelock but the strategist is the devMulti who should be able to call these.

### Notes ###
Further discussion is required as to what to do with these tokens. Will bring it up on the next core-tech meeting.

**Comment by jorijnsmit** [comment]
strat diagrams dont show we took these into account or promised them to users: https://docs.badger.com/badger-finance/setts/sett-user-guides-ethereum/convex-pbtc

current suggestion is to swipe them to treasury ops (or another multisig), sell them for badger and emit to users. there were some concerns around slippage, atm this appears to be a bit over -6% for the whole lot.

the exact emission schedule for those acquired badger however is still unclear to me.

**Comment by jorijnsmit** [comment]
for both $pnt and $boring all liq is on univ2, for $bor it is on sushi.

**Comment by btcookies** [comment]
PR https://github.com/Badger-Finance/badger-multisig/pull/490

**Comment by jorijnsmit** [comment]
ran oog: https://etherscan.io/address/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D

**Comment by btcookies** [comment]
sweep to tech ops executed https://etherscan.io/tx/0xc31aa0bf86b734782ede903308d352e565e5a62a6b2a18befdd9a9faea160179

**Comment by btcookies** [comment]
Events for BORING sell to badger
```
Events In This Transaction
--------------------------
├── IGPv2Settlement (0x9008D19f58AAbD9eD0D60971565AA8510560ab41)
│   └── PreSignature
│       ├── owner: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
│       ├── orderUid: 0xfe4559c761aefb39081c8b0f6d0eb2997934c06eeeed3030bf0c55e4935c496586cbd0ce0c087b482782c181da8d191de18c827562dab3c1
│       └── signed: True
│   
└── Gnosis Safe (0x86cbD0ce0c087b482782c181dA8d191De18C8275)
    └── ExecutionSuccess
        ├── txHash: 0x85ee0e964252364fb9596f23b0ad25ae8de038dcdd2e5627755dbe0ad8ce7fa0
        └── payment: 0
```

**Comment by btcookies** [comment]
Events for sending badger to obtc and pbtc
```
Events In This Transaction
--------------------------
├── IHarvestForwarder (0xA84B663837D94ec41B0f99903f37e1d69af9Ed3E)
│   ├── TreeDistribution
│   │   ├── token: 0x3472A5A71965499acd81997a54BBA8D852C6E53d
│   │   ├── amount: 4687163255922803867648
│   │   ├── block_number: 15180786
│   │   ├── block_timestamp: 1658337368
│   │   └── beneficiary: 0xf349c0faA80fC1870306Ac093f75934078e28991
│   └── TreeDistribution
│       ├── token: 0x3472A5A71965499acd81997a54BBA8D852C6E53d
│       ├── amount: 6844625286372733747200
│       ├── block_number: 15180786
│       ├── block_timestamp: 1658337368
│       └── beneficiary: 0x55912D0Cf83B75c492E761932ABc4DB4a5CB1b17
│   
└── Gnosis Safe (0x86cbD0ce0c087b482782c181dA8d191De18C8275)
    └── ExecutionSuccess
        ├── txHash: 0xfae1d1d3c2f921000720c138810702683d207038192b3975131eacd19ccf0283
        └── payment: 0
```

**Comment by petrovska-petro** [comment]
tx sending the tokens to tree to be emitted to vault and fee taken: https://dashboard.tenderly.co/tx/mainnet/0x951178fcb284a0bdbc35d6301f001ee9f7a085b24d3ed1c591d8dc2946c2d05b
