### ISSUE TITLE
Replace Politician Multisig Signers

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-multisig#248]
Premise: Require >= 1 dev multi signer to execute processing of bribes while maintaining 3/X consensus for increased security, due to scale of bribe rewards.

Current Signers
```
eth:0x10C7a2ca16116E5C998Bfa3BC9CEF464475B18ff
eth:0x8938bf50d1a3736bdA413510688834540858dAEA
eth:0xBB2281cA5B4d07263112604D1F182AD0Ab26a252
eth:0xC69Fb085481bC8C4bfF99B924076656305D9a25D
eth:0xcf4fF1e03830D692F52EB094c52A5A6A2181Ab3F
eth:0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187
```

Add Signers from Dev
```
eth:0x15b8Fe651C268cfb5b519cC7E98bd45C162313C2
eth:0x54cF9dF9dCd78E470AB7CB892D7bFbE114c025fc
```

Remove signers to ensure at least one dev multi signature is required
```
eth:0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187
eth:0xBB2281cA5B4d07263112604D1F182AD0Ab26a252
eth:0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187
eth:0xC69Fb085481bC8C4bfF99B924076656305D9a25D
```

**Comment by jorijnsmit** [comment]
@petrovska-petro @sajanrajdev could one of you resubmit the tx to remove `0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187`?

**Comment by petrovska-petro** [comment]
removing 0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187: https://gnosis-safe.io/app/eth:0x6F76C6A1059093E21D8B1C13C4e20D8335e2909F/transactions/0x25b553a8e9e72c52688497bba6132dd584a197345e4a0f4be799ad11e4fe5f97

**Comment by petrovska-petro** [comment]
remove `0xfA5bb45895Cb3C0aE5B1583Fe068f009A48F0187 ` tx: https://etherscan.io/tx/0x9a7538617941c96d764089ee70bf24e321755a75da2d4123c45c0dd699930207
