### ISSUE TITLE
Update claim_all method in Convex class

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#249]
Currently the [method](https://github.com/Badger-Finance/badger-multisig/blob/main/great_ape_safe/ape_api/convex.py#L92) is only grabbing the claimable tokens from the base reward pool, but for some of them it may occur that there is claimable also in an extra reward contract, it can be inspected on the `extraRewardsLength` of the base reward pool and the address in [extraRewards](https://etherscan.io/address/0x4a9b7eDD67f58654a2c33B587f98c5709AC7d482#code#L793)

In the vault_msig scenario, it will not claim the `ANGLE` token, which there is a little amount claimable at the moment. [zapper](https://zapper.fi/account/0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e)

- [ ] Include the logic to allow claiming the extra rewards

**Comment by petrovska-petro** [comment]
Oh nvm, did not notice that the claim already passes the boolean as true to claim the extras 😮 

https://github.com/convex-eth/platform/blob/main/contracts/contracts/ClaimZap.sol#L120

**Comment by jorijnsmit** [comment]
yea already included
```
snapshot result for 0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e:
              balance_before           balance_after           balance_delta
symbol                                                                      
CVX     0.000000000000000000  455.134227320926698690  455.134227320926698690
ANGLE   0.000000000000000000  998.055965481894287971  998.055965481894287971
```
