### ISSUE TITLE
run prepareWithdrawAll() on old bveCVX strat to allow migration

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-multisig#259]
the funds have all been moved from the old strategy to the vault, however the locker still tracks the strategy as having a deposited balance due to shutdown. This causes the _withdrawAll() inner function to fail which is called during migration

<img width="753" alt="image" src="https://user-images.githubusercontent.com/69157701/158463106-bb7ac26b-ff69-46eb-b12f-d39f3f7c273e.png">

`VirtualMachineError: revert: You have to wait for unlock or have to manually rebalance out of it`

calling `prepareWithdrawAll()` manually allows us to complete migration process

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x7c3713be747c90304570b857ff8eafb38279652320acf3ef880806c5e39e6a49
