### ISSUE TITLE
approveContractAccess on bcvxCRV for new BADGER/wBTC strat

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#274]
Run the following to approveContractAccess to the new BADGER/wBTC strat on bcvxCRV:
```
brownie run badger/whitelist single_sett 0x1905FD2D2D09792eE058C2b46a05F11630a1EcA1 0x2B5455aac8d64C14786c3a29858E43b5945819C0
```

Additionally, add the new contracts for this strat to Address.py as well as the new vestedCVX strat for future references.

**Comment by sajanrajdev** [comment]
@jorijnsmit @shuklaayush @petrovska-petro @Tritium-VLK, could I get a couple of reviews on the above tx. Will upload afterwards.

**Comment by jorijnsmit** [comment]
tbh i dont think you need reviews from msig ops members for this if the script used is already merged in main. only check to make here is the addresses which is done (and being reviewed) in #275.

i say upload and let signers perform last check :)

**Comment by sajanrajdev** [comment]
Uploaded at nonce [1028](https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/queue)

**Comment by sajanrajdev** [comment]
Executed: https://etherscan.io/tx/0xe5acb46dd22ad30a6d6e1881dfdbe7ec1d2985a2906d6114f93adeabfcd85b21
