### ISSUE TITLE
final claim ibbtc rewards

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#276]
month 3 was #29

**Comment by jorijnsmit** [comment]
wait until ibbtc peak contract has been swept before claiming one last time

**Comment by gosuto-inzasheru** [comment]
claim: https://etherscan.io/tx/0x7104e7c270c03e06cba249a5bbe0b772bdd22b7b56483ed93c685709ae7292b2

rewards keep on accruing though due to bvecvx and bcvxcrv holdings

**Comment by sajanrajdev** [comment]
Waiting on incentives strategy for eBTC. Rewards will be sold for such incentives.

**Comment by sajanrajdev** [comment]
As per [TCD 37](https://docs.google.com/document/d/16Df5trssRKcbqJNEXIyO53T226X1LBQ_Qok1w6GBSyQ/edit) we will sell all CVX and cvxCRV rewards for ETH and keep all BADGER.

**Comment by sajanrajdev** [comment]
https://etherscan.io/address/0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
