### ISSUE TITLE
Send DIGG to rewards manager to enable bDIGG harvests

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#308]
The rewards manager contact https://etherscan.io/address/0x5B60952481Eb42B66bdfFC3E049025AC5b91c127#readProxyContract has ~0.155 DIGG in it. Need to distribute 1.069878859 to bDIGG depositors for last 24 days of rewards.

**Comment by jorijnsmit** [comment]
@petrovska-petro i think this topup should also go on the dripper contract, is that possible?

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xf23b3816026d2ad41243b3f229534344b0a1fd000c48b01c7d90fd72a543ce21

**Comment by btcookies** [comment]
Contract needs another 1 DIGG. As of 3/30 need 1.348977691 DIGG to harvest, contract only has 1.155 https://etherscan.io/address/0x5B60952481Eb42B66bdfFC3E049025AC5b91c127#readProxyContract

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x3fd5c5ad4f3b9d706e798e1478cb4c47ea5da4bda29406b4d0685f759ef6134a
