### ISSUE TITLE
Swapr staking contracts migration

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-multisig#314]
New staking contracts

#### SWPR-WETH strategy: [0x85386C3cE0679b035a9F8F17f531C076d0b35954](https://arbiscan.io/address/0x85386C3cE0679b035a9F8F17f531C076d0b35954)
New staking contract: [0xD9A998f2998Bc4810A0303B603a7d4ad312fdCb2](https://swapr.eth.link/#/rewards/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0xdE903E2712288A1dA82942DDdF2c20529565aC30/0xD9A998f2998Bc4810A0303B603a7d4ad312fdCb2?chainId=42161)

#### WBTC-WETH strategy: [0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46](https://arbiscan.io/address/0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46)
New staking contract: [0x28f2a93d9e41C703b5199007c3E22692A2D335eF](https://swapr.eth.link/#/rewards/0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0x28f2a93d9e41C703b5199007c3E22692A2D335eF?chainId=42161)

#### BADGER-WETH strategy: [0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46](https://arbiscan.io/address/0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46)
New staking contract: [0x56EEa3787EfA7D3a78E3c3D047dd9186aC1Ab801](https://swapr.eth.link/#/rewards/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0xBfa641051Ba0a0Ad1b0AcF549a89536A0D76472E/0x56EEa3787EfA7D3a78E3c3D047dd9186aC1Ab801?chainId=42161)

#### ibBTC-WETH strategy: [0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c](https://arbiscan.io/address/0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c)
New staking contract: [0x6E8807E0d108269D017A8958aae36634FA75742B](https://swapr.eth.link/#/rewards/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0x9Ab3FD50FcAe73A1AEDa959468FD0D662c881b42/0x6E8807E0d108269D017A8958aae36634FA75742B?chainId=42161)

**Comment by shuklaayush** [comment]
Posted on nonces 134-137
https://arbiscan.io/tx/0x69126228baa8df20d6ddb71daf54ea0fd85ffb5a0437237a0bdea2b66f48504e
https://arbiscan.io/tx/0x1731a462e5e90730df9030c79ee444bcd7570f2f20ead3bc0408b5bff754ebb6
https://arbiscan.io/tx/0x561e5264e44f571875b7b55f7c1716a21c814596bf3e2cce9f5bdd75c519c2a7
https://arbiscan.io/tx/0x9cccb0a008dd99f5638bad3672e7a709aadb29964f5cfe8d1dbee60881385ce5

**Comment by Tritium-VLK** [comment]
Signed, looks like there were already 2 signers so everythign has executed.
