### ISSUE TITLE
week 13: schedules Mainnet 31-March to 7-April 2022

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-multisig#316]

**Comment by Tritium-VLK** [comment]
Eth Nounce 239: 
`Total emissions during 31-03-22 : badger=19143.0, digg=2.89480223093290494584945128492933302915533E+74 and bcvxCrv=0
Transaction sent: 0x187874a0de84a6c5e23a8207e4bac45af074e9604bf241ea9152133afad07111
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 28
  Gnosis Safe.approveHash confirmed   Block: 14483915   Gas used: 46206 (0.39%)

Transaction sent: 0xaef8c10a3339d16769d716c0299bb2e1d2b074b6a7da69060587013d2eaa000f
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 13
  Gnosis Safe.approveHash confirmed   Block: 14483916   Gas used: 46206 (0.39%)

Transaction sent: 0x1dd67792d6726c14fbceda576920d2d97771d27ef7d262a220dc605d9b85063c
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 234
  Gnosis Safe.approveHash confirmed   Block: 14483917   Gas used: 46206 (0.39%)

Transaction sent: 0xa85dd05cebc90f80e79b9e7298b1ed3ce626f537aadd799787b30638b4ef0e31
  Gas price: 0.0 gwei   Gas limit: 502107   Nonce: 29
  Gnosis Safe.execTransaction confirmed   Block: 14483918   Gas used: 445439 (88.71%)

Transaction was Mined 
---------------------
Tx Hash: 0xa85dd05cebc90f80e79b9e7298b1ed3ce626f537aadd799787b30638b4ef0e31
From: 0x10C7a2ca16116E5C998Bfa3BC9CEF464475B18ff
To: 0x86cbD0ce0c087b482782c181dA8d191De18C8275
Value: 0
Function: Gnosis Safe.execTransaction
Block: 14483918
Gas Used: 445439 / 502107 (88.7%)

Events In This Transaction
--------------------------
├── AdminUpgradeabilityProxy (0x0A4F4e92C3334821EbB523324D09E321a6B0d8ec)
│   ├── UnlockScheduleSet
│   │   ├── beneficiary: 0xaE96fF08771a109dc6650a1BdCa62F2d558E40af
│   │   ├── token: 0x3472A5A71965499acd81997a54BBA8D852C6E53d
│   │   ├── totalAmount: 17591000000000000000000
│   │   ├── start: 1648684800
│   │   ├── end: 1649289600
│   │   ├── duration: 604800
│   │   ├── timestamp: 14483918
│   │   └── blockNumber: 1648594223
│   ├── UnlockScheduleSet
│   │   ├── beneficiary: 0x2B5455aac8d64C14786c3a29858E43b5945819C0
│   │   ├── token: 0x3472A5A71965499acd81997a54BBA8D852C6E53d
│   │   ├── totalAmount: 1552000000000000000000
│   │   ├── start: 1648684800
│   │   ├── end: 1649289600
│   │   ├── duration: 604800
│   │   ├── timestamp: 14483918
│   │   └── blockNumber: 1648594223
│   └── UnlockScheduleSet
│       ├── beneficiary: 0x88128580ACdD9c04Ce47AFcE196875747bF2A9f6
│       ├── token: 0x798D1bE841a82a273720CE31c822C61a67a601C3
│       ├── totalAmount: 289480223093290494584945128492933302915532807943461169556905186705255956480
│       ├── start: 1648684800
│       ├── end: 1649289600
│       ├── duration: 604800
│       ├── timestamp: 14483918
│       └── blockNumber: 1648594223
│   
└── Gnosis Safe (0x86cbD0ce0c087b482782c181dA8d191De18C8275)
    └── ExecutionSuccess
        ├── txHash: 0xf4d88aee9c95bab74933834754613c919d21589d74dd85274f760d96573e878f
        └── payment: 0

{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x120b4ba60>,
│   'safe_address': '0x86cbD0ce0c087b482782c181dA8d191De18C8275',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000034b000a4f4e92c3334821ebb523324d09e321a6b0d8ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f000000000000000000000000ae96ff08771a109dc6650a1bdca62f2d558e40af0000000000000000000000003472a5a71965499acd81997a54bba8d852c6e53d0000000000000000000000000000000000000000000003b99c2a52e3387c0000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a80000a4f4e92c3334821ebb523324d09e321a6b0d8ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f0000000000000000000000002b5455aac8d64c14786c3a29858e43b5945819c00000000000000000000000003472a5a71965499acd81997a54bba8d852c6e53d0000000000000000000000000000000000000000000000542253a126ce400000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a80000a4f4e92c3334821ebb523324d09e321a6b0d8ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f00000000000000000000000088128580acdd9c04ce47afce196875747bf2a9f6000000000000000000000000798d1be841a82a273720ce31c822c61a67a601c300a3d70a3d70a3d8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a80000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 714513,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 239,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
`

**Comment by Tritium-VLK** [comment]
**Arb Nounce 37:**
```Total emissions during 31-03-22 : badger=857.0
Transaction sent: 0x5f3cb0a537b604ce47931c11981687b44b02f933258d2747e103098314e11be8
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 7
  Gnosis Safe.approveHash confirmed   Block: 8857678   Gas used: 46184 (0.23%)

Transaction sent: 0x8486fab809dc0edb9c51d011ae080e74fb1ea7dbfbedd86b0c35ac16e1ed5b2a
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 4
  Gnosis Safe.approveHash confirmed   Block: 8857679   Gas used: 46184 (0.23%)

Transaction sent: 0x30c9391094c053f3f3a0766523e2ae831fcfe4c7cc2105eabd7ccf13eb03882f
  Gas price: 0.0 gwei   Gas limit: 20000000   Nonce: 26
  Gnosis Safe.approveHash confirmed   Block: 8857680   Gas used: 46184 (0.23%)

Transaction sent: 0xfe13ac762d16bf7bc5841fbf80293e8cf517bc9e01232cfe082c6936fdb182a7
  Gas price: 0.0 gwei   Gas limit: 356486   Nonce: 8
  Gnosis Safe.execTransaction confirmed   Block: 8857681   Gas used: 341601 (95.82%)

Transaction was Mined 
---------------------
Tx Hash: 0xfe13ac762d16bf7bc5841fbf80293e8cf517bc9e01232cfe082c6936fdb182a7
From: 0x10C7a2ca16116E5C998Bfa3BC9CEF464475B18ff
To: 0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C
Value: 0
Function: Gnosis Safe.execTransaction
Block: 8857681
Gas Used: 341601 / 356486 (95.8%)

Events In This Transaction
--------------------------
├── Gnosis Safe (0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C)
│   └── SafeMultiSigTransaction
│       ├── to: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D
│       ├── value: 0
│       ├── data: 0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000002320085e1cacae9a63429394d68db59e14af74143c61c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f000000000000000000000000ba418cddd91111f5c1d1ac2777fa8cea28d71843000000000000000000000000bfa641051ba0a0ad1b0acf549a89536a0d76472e000000000000000000000000000000000000000000000019cdd3b60b3df00000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a800085e1cacae9a63429394d68db59e14af74143c61c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f000000000000000000000000e9c12f06f8affd8719263fe4a81671453220389c000000000000000000000000bfa641051ba0a0ad1b0acf549a89536a0d76472e000000000000000000000000000000000000000000000014a76fe9601fd40000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a800000000000000000000000000000
│       ├── operation: 1
│       ├── safeTxGas: 0
│       ├── baseGas: 0
│       ├── gasPrice: 0
│       ├── gasToken: 0x0000000000000000000000000000000000000000
│       ├── refundReceiver: 0x0000000000000000000000000000000000000000
│       ├── signatures: 0x00000000000000000000000010c7a2ca16116e5c998bfa3bc9cef464475b18ff0000000000000000000000000000000000000000000000000000000000000000010000000000000000000000008938bf50d1a3736bda413510688834540858daea000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bb2281ca5b4d07263112604d1f182ad0ab26a252000000000000000000000000000000000000000000000000000000000000000001
│       └── additionalInfo: 0x000000000000000000000000000000000000000000000000000000000000002300000000000000000000000010c7a2ca16116e5c998bfa3bc9cef464475b18ff0000000000000000000000000000000000000000000000000000000000000003
│   
├── AdminUpgradeabilityProxy (0x85E1cACAe9a63429394d68Db59E14af74143c61c)
│   ├── UnlockScheduleSet
│   │   ├── beneficiary: 0xBA418CDdd91111F5c1D1Ac2777Fa8CEa28D71843
│   │   ├── token: 0xBfa641051Ba0a0Ad1b0AcF549a89536A0D76472E
│   │   ├── totalAmount: 476000000000000000000
│   │   ├── start: 1648684800
│   │   ├── end: 1649289600
│   │   ├── duration: 604800
│   │   ├── timestamp: 8857681
│   │   └── blockNumber: 1648594716
│   └── UnlockScheduleSet
│       ├── beneficiary: 0xE9C12F06F8AFFD8719263FE4a81671453220389c
│       ├── token: 0xBfa641051Ba0a0Ad1b0AcF549a89536A0D76472E
│       ├── totalAmount: 381000000000000000000
│       ├── start: 1648684800
│       ├── end: 1649289600
│       ├── duration: 604800
│       ├── timestamp: 8857681
│       └── blockNumber: 1648594716
│   
└── Gnosis Safe (0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C)
    └── ExecutionSuccess
        ├── txHash: 0xac27112b3d6fdc26c9968d71e7d679aa013a18a136a3daa1999cadbd0927d246
        └── payment: 0

{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x127efa0a0>,
│   'safe_address': '0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000002320085e1cacae9a63429394d68db59e14af74143c61c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f000000000000000000000000ba418cddd91111f5c1d1ac2777fa8cea28d71843000000000000000000000000bfa641051ba0a0ad1b0acf549a89536a0d76472e000000000000000000000000000000000000000000000019cdd3b60b3df00000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a800085e1cacae9a63429394d68db59e14af74143c61c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c4768f304f000000000000000000000000e9c12f06f8affd8719263fe4a81671453220389c000000000000000000000000bfa641051ba0a0ad1b0acf549a89536a0d76472e000000000000000000000000000000000000000000000014a76fe9601fd40000000000000000000000000000000000000000000000000000000000006244ef0000000000000000000000000000000000000000000000000000000000624e29800000000000000000000000000000000000000000000000000000000000093a800000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 37,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xe0edbfd0da0dadb982031f67fcde1cbcf726d04f78375eb01dfe3e737e308b9a
https://arbiscan.io/tx/0x9eac1d4a5bd199752e71915fb480777845f1410532660669b441214650627581
