### ISSUE TITLE
Fix bveOXD parameters and return collected fees to Trops

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#366]
bveOXD was launched and delegated with its Strategist and Treasury addresses pointing to Ops Deployer 6. For this reason, all of the fees collected so far (denominated on bveOXD) have been directed to this deployer. The following is necessary to remediate: 

- `bveOXD.setTreasury(Treasury_ops)`
- `bveOXD.setStrategist(Tech-Ops)`
- `bveOXD.transfer(Treasury_ops, deployer balance of bveOXD, {"from": Ops_deployer_6})`

Where,
```
treasuryOps: 0xf109c50684EFa12d4dfBF501eD4858F25A4300B3
TechOps: 0x781E82D5D49042baB750efac91858cB65C6b0582
Ops_deployer_6: 0x7c1D678685B9d2F65F1909b9f2E544786807d46C
```

bveOXD: https://ftmscan.com/address/0x96d4dBdc91Bef716eb407e415c9987a9fAfb8906#readProxyContract

**Comment by sajanrajdev** [comment]
Tx executed: https://ftmscan.com/tx/0x2e57b2f913fcdb9a6c4dcf6711f2360963b7d534265e5891b70a6cddab6c9a5b

**Comment by shuklaayush** [comment]
Transferred all bveOxd fees:
https://ftmscan.com/tx/0x15d97220770da770302fff4acae7301289aafb4f7ab6a5e9624f530a74cfe66e
