### ISSUE TITLE
Upgrade vestedCVX strategy to include BribesProcessor

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#406]
Upgrade the vestedCVX strategy logic to the latest as per the badger-strategies [issue](https://github.com/Badger-Finance/badger-strategies/issues/51). This new logic, soon to be deployed, includes redirection of bribes to the new Processor contract, as well as notification of doing so when claiming bribes.

**Comment by sajanrajdev** [comment]
New logic: https://etherscan.io/address/0x57961a757ba249e616c1940548401b7cdf83a849#code

**Comment by sajanrajdev** [comment]
Confirmed logic to match the latest release, except for comment:
![image](https://user-images.githubusercontent.com/25463788/165577669-c9155c38-33af-42b5-a9cd-f1e8d674e293.png)

LGTM

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x61bb23f1a5d1ed2ec042aa83c32bae63cdf9fe5bb2c5278b6f3d19060069491d
