### ISSUE TITLE
add balancer to great_ape_safe

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#412]
we need our standard deposit and withdraw functions, not sure of the technicalities but preferably something as close to the convex functions as possible.

most important ones for now:
- `deposit_and_stake(self, underlying, mantissa)`
- `claim_all(self)`
- `unstake_all_and_withdraw_all(self, underlying, claim=1)`

**Comment by petrovska-petro** [comment]
for dev ref: https://dev.balancer.fi/resources/joins-and-exits
