### ISSUE TITLE
stable farm rebalance q2

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#413]
treasury pod came up with the following new allocations:
- AAVE - USDC: $614,746
- AAVE - USDT: $614,746
- AAVE - FEI: $307,373
- Balancer - 3pool: $307,373 [depends on Badger-Finance/badger-multisig/issues/412]
- Compound - DAI: $614,746
- Convex - ust-(wormhole): $307,373
- GMX - GLP: $307,373 [this will take some r&d, can be left for a later script]

possible required preparation:
- [ ] send all 3pool from trops to vault

im thinking the following steps in one script:
- [x] withdraw all stables from convex to 3pool or eurs
- [x] swap 3pool to 614_746 usdc
- [x] swap 3pool to 614_746 usdt
- [x] swap 3pool to 307_373 fei
- [x] swap 3pool to 307_373 ust
- [x] swap all eurs to >614_746 dai
- [x] deposit (and stake) into aave
- [x] deposit (and stake) into balancer
- [x] deposit (and stake) into compound
- [x] deposit (and stake) into convex

this can then be left for another time:
- [ ] deposit (and stake?) into gmx

**Comment by jorijnsmit** [comment]
suggesting to wait with the 3pool deposit on balancer; there will be a new contract deployed for it in the next couple of weeks due to a bug: https://forum.balancer.fi/t/vulnerability-disclosure/3179

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x780b8ec118eb57bdef2cfa446f65e08bc83807f7b44d1d4544a90d71a4a2ac92

**Comment by gosuto-inzasheru** [comment]
bpt_3pool deposit and aura stake: https://etherscan.io/tx/0xebe14af59a85197b8bd6ae9ec9f0e52cbc42ff4a5ccb6b085d74cc5a679e233b
