### ISSUE TITLE
Swapr staking contracts migration (May)

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-multisig#458]
New staking contracts

#### SWPR-WETH strategy: [0x85386C3cE0679b035a9F8F17f531C076d0b35954](https://arbiscan.io/address/0x85386C3cE0679b035a9F8F17f531C076d0b35954)
New staking contract: [0x0934e27Eea82f720166eC37214C07e6777511D27](https://swapr.eth.link/#/rewards/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0xdE903E2712288A1dA82942DDdF2c20529565aC30/0x0934e27Eea82f720166eC37214C07e6777511D27?chainId=42161)

#### WBTC-WETH strategy: [0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46](https://arbiscan.io/address/0x43942cEae98CC7485B48a37fBB1aa5035e1c8B46)
New staking contract: [0x7d5Fb4C81df4115B2e4bB84e36cda8bE7aDF9B4F](https://swapr.eth.link/#/rewards/0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0x7d5Fb4C81df4115B2e4bB84e36cda8bE7aDF9B4F?chainId=42161)

#### BADGER-WETH strategy: [0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46](https://arbiscan.io/address/0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46)
New staking contract: [0x42EcF352216b4Be82331123dbCee60447c91b70F](https://swapr.eth.link/#/rewards/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0xBfa641051Ba0a0Ad1b0AcF549a89536A0D76472E/0x42EcF352216b4Be82331123dbCee60447c91b70F?chainId=42161)

#### ibBTC-WETH strategy: [0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c](https://arbiscan.io/address/0x4AeC063BB5322c9d4c1f46572f432aaE3b78b87c)
New staking contract: [0x13a22d37Dee5D6C99D4a36F50C2fD274F73Df21c](https://swapr.eth.link/#/rewards/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1/0x9Ab3FD50FcAe73A1AEDa959468FD0D662c881b42/0x13a22d37Dee5D6C99D4a36F50C2fD274F73Df21c?chainId=42161)

**Comment by jorijnsmit** [comment]
https://arbiscan.io/tx/0xbd019af213ff3f72ce2435a1ca0fa05cd6b60292c2f60b2edd2234ad461199b7
