### ISSUE TITLE
Upgrade arb curve strategies to use univ3

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-multisig#474]
Currently routing selling of CRV rewards through SWAPR which has $24k of liquidity in CRV/ETH pool. UniV3 has much deeper liquidity ($100k+) and should be used.

**Comment by GalloDaSballo** [comment]
[ ] Alex Review
[ ] Watchpug Review
[ ] Another Solidity Dev Review

**Comment by GalloDaSballo** [comment]
LGTM
https://github.com/GalloDaSballo/arbitrum-ren-wbtc-curve-strat/releases/tag/1.1

**Comment by btcookies** [comment]
tricrypto here https://github.com/GalloDaSballo/arbitrum-tricrypto-curve-strat/pull/2

**Comment by gosuto-inzasheru** [comment]
closing due to #946
