### ISSUE TITLE
airdrop $digg 1:1 to $remdigg holders

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#484]
as per bip92:
> remDIGG Exit Strategy: Provide exit strategy for remDIGG holders
>
>    The treasury will mint enough DIGG to allow for the 1:1 exchange of remDIGG (~53) for DIGG
    DIGG will be airdropped to remDIGG holders 1:1
    After the airdrop, support/boost for remDIGG will end

#481 takes care of the minting, although for now the liquidity for airdropping will be provided by withdrawing tcl (#482)

task: generate a csv that airdrops $digg from trops exactly 1:1 to $remdigg holders.

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0xeb3381d0e9a60a634230cb9768995a4e245bbc4873e714b06c40139752d01575
