### ISSUE TITLE
Transfer additional BADGER to payments multisig to cover May and estimated June costs.

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-multisig#503]
Request: 30,000 BADGER for Remainder of May and upcoming April Payroll

Shortfall = -831.34797 BADGER
24,201.68398 BADGER @$5.94 = $143,758.00

95% Confidence Floor @$5.17

27,806 for next month + 832 May = 28,638 + ~5% buffer = 30,000

At best sent today to: 0x30a9c1D258F6c2D23005e6450E72bDD42C541105

**Comment by jorijnsmit** [comment]
posted as nonce 95: https://gnosis-safe.io/app/eth:0x042B32Ac6b453485e357938bdC38e0340d4b9276/transactions/multisig_0x042B32Ac6b453485e357938bdC38e0340d4b9276_0xe9443f67a5d2b4ff0cea9e7a2d1cab4025d6d2e4a4935f400ce682ef00b4ffe0

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x32d7aa79074580d451ccb01f7e7e3259cfb3963c06d67da22db19a03995b5ff2
