### ISSUE TITLE
Upgrade DIGG Proxy

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-multisig#520]
Upgrade DIGG Proxy using new logic deployed here: https://etherscan.io/address/0x020eb84309243ed4b8e6c197af145125dde4afda#code#L727

Reference PR: https://github.com/Badger-Finance/badger-system/pull/267

**Comment by sajanrajdev** [comment]
Upgrade queue to Timelock data:
```
{
    "data": "000000000000000000000000798d1be841a82a273720ce31c822c61a67a601c3000000000000000000000000020eb84309243ed4b8e6c197af145125dde4afda",
    "eta": 1654526146,
    "eth": 0,
    "signature": "upgrade(address,address)",
    "target": "0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF"
}
```

**Comment by sajanrajdev** [comment]
Executed: https://etherscan.io/tx/0xd99b539b452504119d34b1693a952ba6435dcbdc582dd97c59d9dbbb22d8abd4
