### ISSUE TITLE
investigate nitro upgrade for arb1 and its (breaking) effect on our codebase

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#530]
https://github.com/OffchainLabs/nitro/blob/838ba2193e84f54df316a5ea6b0bd3ed4d0fdb37/docs/migration/dapp_migration.md

**Comment by petrovska-petro** [comment]
no multi-chain expansion or deps so far (specially after deprecations). worth closing for now and re-eval later if needs arises
