### ISSUE TITLE
open 1.5x btc long

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#533]
https://forum.badger.finance/t/1-5x-btc-long-using-5-treasury-btc-and-oasis/5693

**Comment by gosuto-inzasheru** [comment]
testing script with 1btc. plan is to leave open for a week or two, monitor and then test closing again.
```
Events In This Transaction
--------------------------
├── Wrapped BTC (0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599)
│   └── Approval
│       ├── owner: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── spender: 0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9
│       └── value: 100000000
│   
├── Aave interest bearing WBTC (0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│   │   └── value: 35142
│   └── Mint
│       ├── from: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│       ├── value: 35142
│       └── index: 1002449659105953542280035001
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── ReserveDataUpdated
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── liquidityRate: 247419749277288490345269
│       ├── stableBorrowRate: 37625895729359523968843211
│       ├── variableBorrowRate: 6100716583487619175074569
│       ├── liquidityIndex: 1002449659105953542280035001
│       └── variableBorrowIndex: 1010971538682397617093127628
│   
├── Wrapped BTC (0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599)
│   └── Transfer
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── to: 0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656
│       └── value: 100000000
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0xd784927Ff2f95ba542BfC824c8a8a98F3495f6b5)
│   └── UserIndexUpdated
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── asset: 0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656
│       └── index: 11662401115697509330390822416
│   
├── Aave interest bearing WBTC (0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   └── value: 100000000
│   └── Mint
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── value: 100000000
│       └── index: 1002449659105953542280035001
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   ├── ReserveUsedAsCollateralEnabled
│   │   ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│   │   └── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   └── Deposit
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amount: 100000000
│       └── referral: 0
│   
├── Aave interest bearing USDC (0xBcca60bB61934080951369a648Fb03DF4F96263C)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│   │   └── value: 6341175
│   └── Mint
│       ├── from: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│       ├── value: 6341175
│       └── index: 1076535732612021310640882304
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0xd784927Ff2f95ba542BfC824c8a8a98F3495f6b5)
│   └── UserIndexUpdated
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── asset: 0x619beb58998eD2278e08620f97007e1116D5D25b
│       └── index: 65175764165010256747171615
│   
├── Aave variable debt bearing USDC (0x619beb58998eD2278e08620f97007e1116D5D25b)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   └── value: 9927378690
│   └── Mint
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── value: 9927378690
│       └── index: 1108930599313334528091214758
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── ReserveDataUpdated
│       ├── reserve: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
│       ├── liquidityRate: 4536320727282182477239604
│       ├── stableBorrowRate: 97305422111395901252228234
│       ├── variableBorrowRate: 14610844222791802504456467
│       ├── liquidityIndex: 1076535732612021310640882304
│       └── variableBorrowIndex: 1108930599313334528091214758
│   
├── USD Coin (0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48)
│   └── Transfer
│       ├── from: 0xBcca60bB61934080951369a648Fb03DF4F96263C
│       ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       └── value: 9927378690
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── Borrow
│       ├── reserve: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amount: 9927378690
│       ├── borrowRateMode: 2
│       ├── borrowRate: 14610844222791802504456467
│       └── referral: 0
│   
├── USD Coin (0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48)
│   ├── Approval
│   │   ├── owner: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   ├── spender: 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
│   │   └── value: 9927378690
│   └── Transfer
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── to: 0x397FF1542f962076d0BFE58eA045FfA2d347ACa0
│       └── value: 9927378690
│   
├── Wrapped Ether (0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
│   └── (unknown)
│       ├── topic1: 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
│       ├── topic2: 0x000000000000000000000000397ff1542f962076d0bfe58ea045ffa2d347aca0
│       ├── topic3: 0x000000000000000000000000ceff51756c56ceffca006cd410b03ffc46dd3a58
│       └── data: 0x0000000000000000000000000000000000000000000000007b8790871b9c18c0
│   
├── SushiSwap LP Token (0x397FF1542f962076d0BFE58eA045FfA2d347ACa0)
│   ├── Sync
│   │   ├── reserve0: 20688696423505
│   │   └── reserve1: 18597113810761529712335
│   └── Swap
│       ├── sender: 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
│       ├── amount0In: 9927378690
│       ├── amount1In: 0
│       ├── amount0Out: 0
│       ├── amount1Out: 8901242098479274176
│       └── to: 0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58
│   
├── Wrapped BTC (0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599)
│   └── Transfer
│       ├── from: 0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58
│       ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       └── value: 49621370
│   
├── SushiSwap LP Token (0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58)
│   ├── Sync
│   │   ├── reserve0: 46238911951
│   │   └── reserve1: 8278503597631405764276
│   └── Swap
│       ├── sender: 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
│       ├── amount0In: 0
│       ├── amount1In: 8901242098479274176
│       ├── amount0Out: 49621370
│       ├── amount1Out: 0
│       └── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   
├── Wrapped BTC (0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599)
│   └── Approval
│       ├── owner: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── spender: 0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9
│       └── value: 49621370
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── ReserveDataUpdated
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── liquidityRate: 247412944738063597024066
│       ├── stableBorrowRate: 37625789428716729720360651
│       ├── variableBorrowRate: 6100631542973383776288520
│       ├── liquidityIndex: 1002449659105953542280035001
│       └── variableBorrowIndex: 1010971538682397617093127628
│   
├── Wrapped BTC (0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599)
│   └── Transfer
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── to: 0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656
│       └── value: 49621370
│   
├── Aave interest bearing WBTC (0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   └── value: 49621370
│   └── Mint
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── value: 49621370
│       └── index: 1002449659105953542280035001
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── Deposit
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amount: 49621370
│       └── referral: 0
│   
└── Gnosis Safe (0x042B32Ac6b453485e357938bdC38e0340d4b9276)
    └── ExecutionSuccess
        ├── txHash: 0x5a0f42c546faa67eb46b42323c99dcb2ffb80a011778998e7aa0f3adc8c73869
        └── payment: 0
```
```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x108c37a00>,
│   'safe_address': '0x042B32Ac6b453485e357938bdC38e0340d4b9276',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000005ef002260fac5e5542a773aa44fbcfedf7c193bc2c59900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000007d2768de32b0b80b7a3454c06bdac94a69ddc7a90000000000000000000000000000000000000000000000000000000005f5e100007d2768de32b0b80b7a3454c06bdac94a69ddc7a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084e8eda9df0000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c5990000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b92760000000000000000000000000000000000000000000000000000000000000000007d2768de32b0b80b7a3454c06bdac94a69ddc7a9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4a415bcad000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000000000000000000000000000000000024fb7c70200000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b927600a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000d9e1ce17f2641f24ae83637ab66a2cca9c378b9f000000000000000000000000000000000000000000000000000000024fb7c70200d9e1ce17f2641f24ae83637ab66a2cca9c378b9f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012438ed1739000000000000000000000000000000000000000000000000000000024fb7c7020000000000000000000000000000000000000000000000000000000002e604ce00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b92760000000000000000000000000000000000000000000000000000000062c52e780000000000000000000000000000000000000000000000000000000000000003000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599002260fac5e5542a773aa44fbcfedf7c193bc2c59900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000007d2768de32b0b80b7a3454c06bdac94a69ddc7a90000000000000000000000000000000000000000000000000000000002f5297a007d2768de32b0b80b7a3454c06bdac94a69ddc7a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084e8eda9df0000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c5990000000000000000000000000000000000000000000000000000000002f5297a000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b927600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 115,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```
```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
               balance_before          balance_after          balance_delta
symbol                                                                     
WBTC    17.761158160000000000  16.761158160000000000  -1.000000000000000000
aWBTC    0.000000000000000000   1.496213710000000000   1.496213710000000000
```

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0xa110f7610cc04fdd16a438ed694cef9ab025c611fb3233e847dfd75a5bcd03bf

**Comment by rayeaster** [comment]
> https://etherscan.io/tx/0x6059ad1cc64de7aaa6b4f4878d1b06e1d46dd3c5f3db1ca86b630b3878afd9dc

https://debank.com/profile/0x042B32Ac6b453485e357938bdC38e0340d4b9276/history
https://zapper.fi/account/0x042b32ac6b453485e357938bdc38e0340d4b9276?tab=history

**Comment by gosuto-inzasheru** [comment]
Events In This Transaction
--------------------------
├── Aave interest bearing WBTC (0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│   │   └── value: 2619
│   └── Mint
│       ├── from: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│       ├── value: 2619
│       └── index: 1002452974545365700421950496
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── ReserveDataUpdated
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── liquidityRate: 148208004692693547007658
│       ├── stableBorrowRate: 35828581130942184234552979
│       ├── variableBorrowRate: 4662864904753747387642383
│       ├── liquidityIndex: 1002452974545365700421950496
│       └── variableBorrowIndex: 1011052480971092838935723922
│   
├── Aave interest bearing WBTC (0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   └── value: 500000000
│   └── Mint
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── value: 500000000
│       └── index: 1002452974545365700421950496
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   ├── ReserveUsedAsCollateralEnabled
│   │   ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│   │   └── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   └── Deposit
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amount: 500000000
│       └── referral: 0
│   
├── Aave interest bearing USDC (0xBcca60bB61934080951369a648Fb03DF4F96263C)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│   │   └── value: 10875278
│   └── Mint
│       ├── from: 0x464C71f6c2F760DdA6093dCB91C24c39e5d6e18c
│       ├── value: 10875278
│       └── index: 1076632519946556844864491487
│   
├── Aave variable debt bearing USDC (0x619beb58998eD2278e08620f97007e1116D5D25b)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   └── value: 51588411122
│   └── Mint
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── value: 51588411122
│       └── index: 1109208773800343763021192196
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   ├── ReserveDataUpdated
│   │   ├── reserve: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
│   │   ├── liquidityRate: 5885630766705468741735281
│   │   ├── stableBorrowRate: 98307660817210055223533172
│   │   ├── variableBorrowRate: 16615321634420110447066344
│   │   ├── liquidityIndex: 1076632519946556844864491487
│   │   └── variableBorrowIndex: 1109208773800343763021192196
│   └── Borrow
│       ├── reserve: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amount: 51588411122
│       ├── borrowRateMode: 2
│       ├── borrowRate: 16615321634420110447066344
│       └── referral: 0
│   
├── Wrapped Ether (0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
│   └── Transfer
│       ├── src: 0x397FF1542f962076d0BFE58eA045FfA2d347ACa0
│       ├── dst: 0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58
│       └── wad: 44753961220530057577
│   
├── SushiSwap LP Token (0x397FF1542f962076d0BFE58eA045FfA2d347ACa0)
│   ├── Sync
│   │   ├── reserve0: 21095823914764
│   │   └── reserve1: 18311221834923843900078
│   └── Swap
│       ├── sender: 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
│       ├── amount0In: 51588411122
│       ├── amount1In: 0
│       ├── amount0Out: 0
│       ├── amount1Out: 44753961220530057577
│       └── to: 0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58
│   
├── SushiSwap LP Token (0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58)
│   ├── Sync
│   │   ├── reserve0: 45984342327
│   │   └── reserve1: 8319998011649296726575
│   └── Swap
│       ├── sender: 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
│       ├── amount0In: 0
│       ├── amount1In: 44753961220530057577
│       ├── amount0Out: 247945258
│       ├── amount1Out: 0
│       └── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── ReserveDataUpdated
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── liquidityRate: 148184038889060217246804
│       ├── stableBorrowRate: 35828096847101310778671693
│       ├── variableBorrowRate: 4662477477681048622937354
│       ├── liquidityIndex: 1002452974545365700421950496
│       └── variableBorrowIndex: 1011052480971092838935723922
│   
├── Aave interest bearing WBTC (0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656)
│   ├── Transfer
│   │   ├── from: 0x0000000000000000000000000000000000000000
│   │   ├── to: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│   │   └── value: 247945258
│   └── Mint
│       ├── from: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── value: 247945258
│       └── index: 1002452974545365700421950496
│   
├── InitializableImmutableAdminUpgradeabilityProxy (0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9)
│   └── Deposit
│       ├── reserve: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
│       ├── user: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── onBehalfOf: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amount: 247945258
│       └── referral: 0
│   
└── Gnosis Safe (0x042B32Ac6b453485e357938bdC38e0340d4b9276)
    └── ExecutionSuccess
        ├── txHash: 0x765bb845becf12d874a120123daeae5a73846d97db551881ef22a1019efa57f2
        └── payment: 0
```
```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x11538af10>,
│   'safe_address': '0x042B32Ac6b453485e357938bdC38e0340d4b9276',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000005ef002260fac5e5542a773aa44fbcfedf7c193bc2c59900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000007d2768de32b0b80b7a3454c06bdac94a69ddc7a9000000000000000000000000000000000000000000000000000000001dcd6500007d2768de32b0b80b7a3454c06bdac94a69ddc7a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084e8eda9df0000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599000000000000000000000000000000000000000000000000000000001dcd6500000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b92760000000000000000000000000000000000000000000000000000000000000000007d2768de32b0b80b7a3454c06bdac94a69ddc7a9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4a415bcad000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000c02e8aef200000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b927600a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000d9e1ce17f2641f24ae83637ab66a2cca9c378b9f0000000000000000000000000000000000000000000000000000000c02e8aef200d9e1ce17f2641f24ae83637ab66a2cca9c378b9f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012438ed17390000000000000000000000000000000000000000000000000000000c02e8aef2000000000000000000000000000000000000000000000000000000000e7bad7000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b92760000000000000000000000000000000000000000000000000000000062ccb37a0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599002260fac5e5542a773aa44fbcfedf7c193bc2c59900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000007d2768de32b0b80b7a3454c06bdac94a69ddc7a9000000000000000000000000000000000000000000000000000000000ec7582a007d2768de32b0b80b7a3454c06bdac94a69ddc7a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084e8eda9df0000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599000000000000000000000000000000000000000000000000000000000ec7582a000000000000000000000000042b32ac6b453485e357938bdc38e0340d4b927600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 119,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```
```
snapshot result for 0x042B32Ac6b453485e357938bdC38e0340d4b9276:
               balance_before          balance_after          balance_delta
symbol                                                                     
WBTC    17.772466550000000000  12.772466550000000000  -5.000000000000000000
aWBTC    0.000000000000000000   7.479452580000000000   7.479452580000000000 
```

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x52b76fb6f90df24eaa23d2793e3aef3d35a7f0f5ed2e95b6f8fed6f488b8c77b
