### ISSUE TITLE
Discontinue all FTM Setts except for bveOXD

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#541]
Non of the FTM Setts meet the policy requirements to make a business case out of them and, hence, should be discontinued. The only exception for now should be bveOXD as all of its want is locked for the next 14 weeks.

In order to discontinue, once the Registry 2.0 is wired to the UI, we can submit a tx for each vault to chance its status from 3 to 0. This will handle the discontinuation on the UI.

Additionally, @btcookies will stop all earning/harvesting on these.

**Comment by btcookies** [comment]
keeper ops stopped
