### ISSUE TITLE
[FTM] Upgrade Sett1.5-rewards to Sett1.5-noRewards

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-multisig#543]
On the FTM Network

Upgrade this contract
https://ftmscan.com/address/0x5dA75c76565B69A5cDC5F2195E31362CEA00CD14#readProxyContract

To use this Logic:
https://ftmscan.com/address/0xef919733eeb7326c5389f4a5d7337cdf078b0db9#code

Via the Proxy Admin:
`0x20dce41acca85e8222d6861aa6d23b6c941777bf`

**Comment by GalloDaSballo** [comment]
See Upgrade Test:
https://github.com/GalloDaSballo/fantom-generic-solidex-dca/blob/main/tests/emergency/test_undo_tree_upgrade.py

**Comment by GalloDaSballo** [comment]
Urgency: Not too urgent

**Comment by sajanrajdev** [comment]
Note: devProxyAdmin on FTM is owned by the devMultisig - No need for Timelock.

**Comment by sajanrajdev** [comment]
Upgrade executed: https://ftmscan.com/tx/0x510743fa908e90dd3f08561ddf31119a9f8aa2dade2dd1b1588393e42ef4ec62
