### ISSUE TITLE
claim all aura airdrops

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#561]
2.53k on treasury voter: `0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b`
771 on ibbtc msig: `0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8`
677 on ibbtc peak (todo: redirect): `0x41671BA1abcbA387b9b2B752c205e22e916BE6e3`
197 on trops: `0x042B32Ac6b453485e357938bdC38e0340d4b9276`
77 vault: `0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e`

**Comment by petrovska-petro** [comment]
## claim voter msig

```
Events In This Transaction
--------------------------
├── Vote Locked Aura (0x3Fa73f1E5d8A792C80F426fc8F84FBF7Ce9bBCAC)
│   ├── DelegateCheckpointed
│   │   └── delegate: 0x14F83fF95D4Ec5E8812DDf42DA1232b0ba1015e6
│   └── Staked
│       ├── _user: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b
│       ├── _paidAmount: 2823416919731828329532
│       └── _lockedAmount: 2823416919731828329532
│   
├── IAuraMerkleDrop (0x45EB1A004373b1D8457134A2C04a42d69D287724)
│   └── Claimed
│       ├── addr: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b
│       ├── amt: 2823416919731828329532
│       └── locked: True
│   
└── Gnosis Safe (0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b)
    └── ExecutionSuccess
        ├── txHash: 0x574318bd3a9ebaed8dbe0cac6ad10c2e40d1a9f460c9f2b1bf31a5bdc411fae9
        └── payment: 0
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7fc839a02610>,
│   'safe_address': '0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000002790045eb1a004373b1d8457134a2c04a42d69d2877240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022453210b3900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000990ec7e96463368c3c0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000d9e8877002d3cb8238d5e9d2907dda81993caf6488e6e14d3af506e56fb90a2de40209d4c49e1a65dd7538137b3ced1377ff7267b656dbf12ea5a502d38d09d8baa3f2c7a3f18ec46b9c629eb3d09427bad58ff904db91b3e1c6ad3b3b2b39fdb690080e948a48bb7cf3885245108e71bce0851e1c98f33ecdc6ad5cf6f9dee8a450b8acf854463c1a4acddcc1bf0c4eecc30c3e6f6a704ee71c56b2961d3dd011fc6e923dc55733ff60440b8f32949d3dd361300b9ce97fb1069e2df930001bb97ac9df39d45ef46579988e10f735f1a9b17f11c1c5309c4eb0ce754740dd5c74e6f38e4023fef66d619432ca43c3eb9c6edb83bc56cb54da09a0ef374246366347434aa51fbad2403b155aaa397c91ce086edb9ba15eb4c7bec7e1313966118b5c73efa1e3ddc49a5d715f66d2f8d5c043ea36a74ff7e732cbd6cd3fd870ec50c0e6a2faf6e94d0b5a1cd49e92c1a400c5f8715cc0ba7f8d72a6674700e1860c3d849f7a9528b1c7a94b37fa96daddd882b85442a136fd1a2a89b9785392b03885f3b9b64e16f0a6490c275896092c04f932fd1a484ba7049c7ae632e301a2300000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 5,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

**Comment by petrovska-petro** [comment]
## claim trops msig

```
snapshot result for 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b:
              balance_before           balance_after           balance_delta
symbol                                                                      
AURA    0.000000000000000000  136.699592021343281090  136.699592021343281090
```

```
Events In This Transaction
--------------------------
├── IAuraMerkleDrop (0x45EB1A004373b1D8457134A2C04a42d69D287724)
│   └── Claimed
│       ├── addr: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
│       ├── amt: 195285131459061830128
│       └── locked: False
│   
└── Gnosis Safe (0x042B32Ac6b453485e357938bdC38e0340d4b9276)
    └── ExecutionSuccess
        ├── txHash: 0xcb61dd5c2f6b5eefc0bc64ca75089b0e5d92ac16ecf582c65d373933a6fddec6
        └── payment: 0
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7fe4d68c45b0>,
│   'safe_address': '0x042B32Ac6b453485e357938bdC38e0340d4b9276',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000003120045eb1a004373b1d8457134a2c04a42d69d2877240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022453210b39000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000a96202865a4d751f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d9ca972ec88cfbc78627eed74f7d33ba6c4a670bedcf51301ab08d33af70827e834044e08e022a6905b6053a6e23f8a8169099b98b623b1ff0017ff6fdaa9fa51314dd7d636884e529b0fd4064bc850433d037250946d277ffafb3d3ca2ada8391422b0f8cb7dc79b2fc5898e7fbfc6241f8e8445d63f057f5073c81e8183861fa89d8fdd0667ef7d327a3b4e6c6da2c6512424a1520da005e46f74502f8d2e01910436d8bed66823462721368bc5529307b1ebab7388005d524c99dd012dcb3e9acb6682ff8cca14b02b7c63caba15db3880b161542e6ebb7e5fcb672267c05f9bbf458787d26a4d62d3d6d446b85b411e5f7d745fa1fcb81ae0bc22e93b3018347434aa51fbad2403b155aaa397c91ce086edb9ba15eb4c7bec7e1313966118b5c73efa1e3ddc49a5d715f66d2f8d5c043ea36a74ff7e732cbd6cd3fd870ec50c0e6a2faf6e94d0b5a1cd49e92c1a400c5f8715cc0ba7f8d72a6674700e1860c3d849f7a9528b1c7a94b37fa96daddd882b85442a136fd1a2a89b9785392b03885f3b9b64e16f0a6490c275896092c04f932fd1a484ba7049c7ae632e301a2300c0c293ce456ff0ed870add98a0828dd4d2903dbf00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000a9ed98b5fb8428d68664f3c5027c62a10d45826b000000000000000000000000000000000000000000000007691682ad8cfd1fc20000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 109,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

**Comment by petrovska-petro** [comment]
## claim ibbtc msig 

```
snapshot result for 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b:
              balance_before           balance_after           balance_delta
symbol                                                                      
AURA    0.000000000000000000  534.768293654481976773  534.768293654481976773
```

```
Events In This Transaction
--------------------------
├── IAuraMerkleDrop (0x45EB1A004373b1D8457134A2C04a42d69D287724)
│   └── Claimed
│       ├── addr: 0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8
│       ├── amt: 763954705220688538247
│       └── locked: False
│   
└── Gnosis Safe (0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8)
    └── ExecutionSuccess
        ├── txHash: 0x430df31531535affa76bee3d90334ad5af2bec3b8a29587e2e5bb67eba6b4626
        └── payment: 0
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f9766fe0400>,
│   'safe_address': '0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000002f20045eb1a004373b1d8457134a2c04a42d69d2877240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020453210b3900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000296a0054caef65ea870000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000cbb98c242988522e315a63d2955287d264b45d07b11d526a8b9fb4bd1dd6f35b5564276df69898d7dce3b293d064afcd1fec9936d38d855398917fdf129d4396569e997b500b0a0e4f8c9b493ca4d3eb06cb5bb274623a1cf5d024362db6549681ffb085df6682b967218714a520e68b28e9c1e5c63febc1266db8ab9528e5a5462114cb6364c435c6be061a9a04a21264da3166df3dae573052f3ef0205a330657c49e0db3df7e985e44c6560354fae7396119595645c259e224ed0723bbd7d71ee78309381142af3b95766efb21c99a1621edc02c647e91dd3312cb90b99ae9b982c35cc7147fd124f54f38322eb3ab453bf7c54998a7c737288f17aaddb33b93a2345e5aed41e13f19184f396df84bdb7343893ac6da9ab1a7517594de963dd2ddeff9c84b16e6a8055da6dd8b4efe289184b60c83d2a3cca08707d3532b96c956d31b7d2625ccd552ccd900e6184cfa4629d168eb8ac3f4e0411bd08cee4366f5cde9ed8c57a0eec9fad4191975a11199fc07a748d3d95b06285b78a6b42500c0c293ce456ff0ed870add98a0828dd4d2903dbf00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000a9ed98b5fb8428d68664f3c5027c62a10d45826b00000000000000000000000000000000000000000000001cfd66a1c1412dbdc50000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 8,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

**Comment by jorijnsmit** [comment]
claim and transfer on trops: https://etherscan.io/tx/0x7bb851ff7fa61317e314aa297095a40bab2304ca450f6ce0d0cf45eef9dc360c

**Comment by petrovska-petro** [comment]
> ## claim trops msig
> ```
> snapshot result for 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b:
>               balance_before           balance_after           balance_delta
> symbol                                                                      
> AURA    0.000000000000000000  136.699592021343281090  136.699592021343281090
> ```
> 
> ```
> Events In This Transaction
> --------------------------
> ├── IAuraMerkleDrop (0x45EB1A004373b1D8457134A2C04a42d69D287724)
> │   └── Claimed
> │       ├── addr: 0x042B32Ac6b453485e357938bdC38e0340d4b9276
> │       ├── amt: 195285131459061830128
> │       └── locked: False
> │   
> └── Gnosis Safe (0x042B32Ac6b453485e357938bdC38e0340d4b9276)
>     └── ExecutionSuccess
>         ├── txHash: 0xcb61dd5c2f6b5eefc0bc64ca75089b0e5d92ac16ecf582c65d373933a6fddec6
>         └── payment: 0
> ```
> 
> ```
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7fe4d68c45b0>,
> │   'safe_address': '0x042B32Ac6b453485e357938bdC38e0340d4b9276',
> │   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000003120045eb1a004373b1d8457134a2c04a42d69d2877240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022453210b39000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000a96202865a4d751f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d9ca972ec88cfbc78627eed74f7d33ba6c4a670bedcf51301ab08d33af70827e834044e08e022a6905b6053a6e23f8a8169099b98b623b1ff0017ff6fdaa9fa51314dd7d636884e529b0fd4064bc850433d037250946d277ffafb3d3ca2ada8391422b0f8cb7dc79b2fc5898e7fbfc6241f8e8445d63f057f5073c81e8183861fa89d8fdd0667ef7d327a3b4e6c6da2c6512424a1520da005e46f74502f8d2e01910436d8bed66823462721368bc5529307b1ebab7388005d524c99dd012dcb3e9acb6682ff8cca14b02b7c63caba15db3880b161542e6ebb7e5fcb672267c05f9bbf458787d26a4d62d3d6d446b85b411e5f7d745fa1fcb81ae0bc22e93b3018347434aa51fbad2403b155aaa397c91ce086edb9ba15eb4c7bec7e1313966118b5c73efa1e3ddc49a5d715f66d2f8d5c043ea36a74ff7e732cbd6cd3fd870ec50c0e6a2faf6e94d0b5a1cd49e92c1a400c5f8715cc0ba7f8d72a6674700e1860c3d849f7a9528b1c7a94b37fa96daddd882b85442a136fd1a2a89b9785392b03885f3b9b64e16f0a6490c275896092c04f932fd1a484ba7049c7ae632e301a2300c0c293ce456ff0ed870add98a0828dd4d2903dbf00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044a9059cbb000000000000000000000000a9ed98b5fb8428d68664f3c5027c62a10d45826b000000000000000000000000000000000000000000000007691682ad8cfd1fc20000000000000000000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 0,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 109,
> │   '_safe_version': '1.3.0',
> │   '_chain_id': None
> }
> ```

https://etherscan.io/tx/0x7bb851ff7fa61317e314aa297095a40bab2304ca450f6ce0d0cf45eef9dc360c

**Comment by sajanrajdev** [comment]
Claimed and transferred to trops from ibBTC multisig: https://etherscan.io/tx/0xb668f0a7d8333230b0da54a51531e5bc9b66958657086431957b81f24fe7086d

**Comment by petrovska-petro** [comment]
> ## claim voter msig
> ```
> Events In This Transaction
> --------------------------
> ├── Vote Locked Aura (0x3Fa73f1E5d8A792C80F426fc8F84FBF7Ce9bBCAC)
> │   ├── DelegateCheckpointed
> │   │   └── delegate: 0x14F83fF95D4Ec5E8812DDf42DA1232b0ba1015e6
> │   └── Staked
> │       ├── _user: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b
> │       ├── _paidAmount: 2823416919731828329532
> │       └── _lockedAmount: 2823416919731828329532
> │   
> ├── IAuraMerkleDrop (0x45EB1A004373b1D8457134A2C04a42d69D287724)
> │   └── Claimed
> │       ├── addr: 0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b
> │       ├── amt: 2823416919731828329532
> │       └── locked: True
> │   
> └── Gnosis Safe (0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b)
>     └── ExecutionSuccess
>         ├── txHash: 0x574318bd3a9ebaed8dbe0cac6ad10c2e40d1a9f460c9f2b1bf31a5bdc411fae9
>         └── payment: 0
> ```
> 
> ```
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7fc839a02610>,
> │   'safe_address': '0xA9ed98B5Fb8428d68664f3C5027c62A10d45826b',
> │   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000002790045eb1a004373b1d8457134a2c04a42d69d2877240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022453210b3900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000990ec7e96463368c3c0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000d9e8877002d3cb8238d5e9d2907dda81993caf6488e6e14d3af506e56fb90a2de40209d4c49e1a65dd7538137b3ced1377ff7267b656dbf12ea5a502d38d09d8baa3f2c7a3f18ec46b9c629eb3d09427bad58ff904db91b3e1c6ad3b3b2b39fdb690080e948a48bb7cf3885245108e71bce0851e1c98f33ecdc6ad5cf6f9dee8a450b8acf854463c1a4acddcc1bf0c4eecc30c3e6f6a704ee71c56b2961d3dd011fc6e923dc55733ff60440b8f32949d3dd361300b9ce97fb1069e2df930001bb97ac9df39d45ef46579988e10f735f1a9b17f11c1c5309c4eb0ce754740dd5c74e6f38e4023fef66d619432ca43c3eb9c6edb83bc56cb54da09a0ef374246366347434aa51fbad2403b155aaa397c91ce086edb9ba15eb4c7bec7e1313966118b5c73efa1e3ddc49a5d715f66d2f8d5c043ea36a74ff7e732cbd6cd3fd870ec50c0e6a2faf6e94d0b5a1cd49e92c1a400c5f8715cc0ba7f8d72a6674700e1860c3d849f7a9528b1c7a94b37fa96daddd882b85442a136fd1a2a89b9785392b03885f3b9b64e16f0a6490c275896092c04f932fd1a484ba7049c7ae632e301a2300000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 0,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 5,
> │   '_safe_version': '1.3.0',
> │   '_chain_id': None
> }
> ```

https://etherscan.io/tx/0x50463265c64747922e1c2e12669c2bfc84f98ea0701fc6228091efca9c196fcf
