### ISSUE TITLE
fees reroute to treasury ops

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#57]
both performance and withdrawal fees should go to treasury ops instead of dev msig

**Comment by sajanrajdev** [comment]
Tx loaded at nonce [993](https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/queue)

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x9f5922482844136f5c75c64d300088cb2055bbdacaf299444fba6aa3b5eebd9c

**Comment by sajanrajdev** [comment]
> https://etherscan.io/tx/0x9f5922482844136f5c75c64d300088cb2055bbdacaf299444fba6aa3b5eebd9c

Tx changed the reward address for the ibBTC-sBTC-f and bveCVX/CVX-f controllers and queued the change for the native, experimental and harvest controller.

**Comment by jorijnsmit** [comment]
ah sorry didnt think about timelock

**Comment by sajanrajdev** [comment]
Executions for native, experimental and harvest controllers were added at nonce [1002](https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/queue)

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0x5aa158cec707a18a93bae0f4dca146d7ce3d2c64c42b44b99f20a3d8b048d8c5

**Comment by jorijnsmit** [comment]
@sajanrajdev here still a wd fee coming in to dev; coming from the byvwbtc vault.

https://etherscan.io/tx/0x035bb07f68403af02e8a9552f151c99ddb91dd13c165a251f4a7319bb8243f0f

**Comment by sajanrajdev** [comment]
> @sajanrajdev here still a wd fee coming in to dev; coming from the byvwbtc vault.
> 
> https://etherscan.io/tx/0x035bb07f68403af02e8a9552f151c99ddb91dd13c165a251f4a7319bb8243f0f

@jorijnsmit Ah, good catch! Once again I missed this special case. byvWBTC doesn't route fees through a controller but, rather, it transfers them directly.

I just reviewed the contract and I don't think we will be able to change the destination of these fees unfortunately. The wd fees are transferred to the `affiliate` (aka governance - devMulti) and this can't be changed to Trops: https://etherscan.io/address/0xc0a972a3cf8e52167589694d135abb66409f9b30#code#L1651. PerformanceFees are charged at the strategies' level which are managed by Yearn directly, we have even less access to these. I guess we could talk to them and ask them to direct them to Trops, but I am not sure how the strats are setup.
