### ISSUE TITLE
Migrate swapr staking contracts (june)

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-multisig#571]
WIP

**Comment by btcookies** [comment]
BADGER/WETH: 0x3EF4dA485057ef9A87CEcc5e75Ab0b7c696FE857
WBTC/WETH: 0xb9A5A0099dD9BB2173ABc78E8420dcFac893d85f
IBBTC/WETH: 0xbCC96f1f9fcd34Ed3795D7a721fA7083f1A93808
