### ISSUE TITLE
Add back keeper_ACL to graviAura

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#574]
The keeper was set to AddressZero on graviAura to avoid automatic harvests to run while the strategy's harvest function is patched with C4 findings. Once ready, the Keeper ACL address should added once more to enable regular operations.

Call:
```
graviAura.setKeeper(keeperACL.address)
```

From the vault's governance, which is currently TechOps.

**Comment by shuklaayush** [comment]
Yes, should be fine

**Comment by sajanrajdev** [comment]
In order to remove any room for error, we will avoid adding back the keeper until the strategy is ready.

Earn() will be called manually from TechOps this week and as required until further notice.

@Tritium-VLK @btcookies @shuklaayush

**Comment by sajanrajdev** [comment]
Earn called manually from TechOps: https://etherscan.io/tx/0x497dfa4da3601ae1595fbc796fe0bca537b9a933d9ce8097023469c049d5e8b4

**Comment by petrovska-petro** [comment]
2nd earn: https://etherscan.io/tx/0x4fec066fda3119ce84d1ec57a8e0042ef3cdbf1ce6e9f20259bda5086010f4ee

**Comment by jorijnsmit** [comment]
3rd: https://etherscan.io/tx/0xf341282e4484644310eaff6218c9f8f68af74f3825da3deb5d7d9be0d89c18b6

**Comment by sajanrajdev** [comment]
Keeper added back: https://etherscan.io/tx/0xc86d1dc52dddb8cb08b9ea42cc88dce1142565574c2fe9072c37583c7b1c6297
