### ISSUE TITLE
Upgrade graviAura to 1.1

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-multisig#577]
Code (wip): https://github.com/Badger-Finance/vested-aura/blob/1.1-rc.1/contracts/MyStrategy.sol

**Comment by jorijnsmit** [comment]
queued in timelock: https://etherscan.io/tx/0xe58d04985a87cd2a53d1492b8d93b94cfe114813a60dbf61bba8125455cdabb1

**Comment by sajanrajdev** [comment]
Executed: https://etherscan.io/tx/0x942d9a3c3a1bdca22da5dadad474768ab449cc4509366b6b8361c8a397e2af3f
