### ISSUE TITLE
Add new signer to TechOps

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#603]
As discussed in core-decisions, a new signer will be added from the core tech team to the TechOps multisig in order to improve the geographical distribution.

The new signer should be added to the repo's registry.

**Comment by sajanrajdev** [comment]
The new executor's address is: `0x95c1D2014909c04202fa73820B894b45F054F25e`

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x4b032e4a41587a63b4eb22f1a70764b54ea98ad25a9791504b5fde0ad218b118#eventlog

**Comment by petrovska-petro** [comment]
proof of ownership stept 1: https://etherscan.io/tx/0x0dcd08fcb3c79c280569f4e6131ebc1461b3372bde75dba6c82bf5f94172150f

**Comment by sajanrajdev** [comment]
Adding new signer to TechOps on Arbitrum, Fantom and Polygon

**Comment by sajanrajdev** [comment]
Fantom: https://ftmscan.com/tx/0xf5a10aebcee1b188b59cd1cc3350f6d4397bbe00931fd9aba765f3d1da3bc1ff/internal-transactions
