### ISSUE TITLE
Add claim zapper in aura class

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#627]
Address: https://etherscan.io/address/0x623B83755a39B12161A63748f3f595A530917Ab2

Facilitate claiming of vault positions

**Comment by gosuto-inzasheru** [comment]
will that help solve #626?

**Comment by gosuto-inzasheru** [comment]
there is another aura claim possible on the voter msig from the initial locking;
<img width="1172" alt="Screenshot 2022-07-07 at 14 01 15" src="https://user-images.githubusercontent.com/2835259/177768454-ca185fa9-a238-4e26-98ec-c3c72806d156.png">

would be nice if this can be included as well. voter msig could then call it on the next chance.
