### ISSUE TITLE
Payment to Llama Airforce

### ISSUE THREAD

**Issue by Hal69k** [Badger-Finance/badger-multisig#649]
This core decision : https://discord.com/channels/785315893960900629/897912027278868490/988912876959977472 passed and requests that 3000 Badger and 3000 GTC are sent to Llama Airforce.

Here is the donation address:

0x9Bc7c6ad7E7Cf3A6fCB58fb21e27752AC1e53f99

**Comment by gosuto-inzasheru** [comment]
https://gnosis-safe.io/app/eth:0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e/transactions/multisig_0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e_0xbfaaa774832496cdf9bb48c3ccdf5f4c02fd4afcf46de8a525675f80b230c7b1

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0xe273ec96bb7fd1f2ac7d3eed26a78d20dbfd3cbaf357fb01342fee795211c9c6
