### ISSUE TITLE
[bveAURA] Set Bribes Processor 

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-multisig#663]
Set Bribes Processor to
https://etherscan.io/address/0x0b6198b324e12a002b60162f8a130d6aedabd04c#readContract

Before:
- [x] Final Security Signoff by @sajanrajdev @shuklaayush @dapp-whisperer 
- [x] Set Manager to TechOps @gosuto-inzasheru 
- [ ] Dev Multisig sets Processor

**Comment by GalloDaSballo** [comment]
Script will be sent shortly

**Comment by GalloDaSballo** [comment]
Sent Script, see above

**Comment by gosuto-inzasheru** [comment]
@GalloDaSballo i believe the only one that can set the manager is the existing manager? in that case that means that the current manager (the deployer; `0x283C857BA940A61828d9F4c09e3fceE2e7aEF3f7`) has to `AuraBribesProcessor.setManager(techops)`.

**Comment by GalloDaSballo** [comment]
> @GalloDaSballo i believe the only one that can set the manager is the existing manager? in that case that means that the current manager (the deployer; `0x283C857BA940A61828d9F4c09e3fceE2e7aEF3f7`) has to `AuraBribesProcessor.setManager(techops)`.

Yes I have to manually delegate, waiting on final security reviews

**Comment by GalloDaSballo** [comment]
@sajanrajdev @shuklaayush @dapp-whisperer
Lmk if the Processor LG and will delegate to techops

**Comment by sajanrajdev** [comment]
@GalloDaSballo, I dropped my review on the issue: https://github.com/Badger-Finance/badger-strategies/issues/57#issuecomment-1184475727

Logic matches latest version, swap path through graviAURA/WETH/AURA pool confirmed to work locally and most tests are passing (with the exception of SD and FDT as expected). The tests on the `tests/on_chain_pricer/test_swap_exec_on_chain.py` suite are failing for me for what seems to be a local env issue, looking into it.

Regardless of these tests, I couldn't find any other vulnerabilities and the tests that verify the Processor's changes are passing. It would be great if somebody could share a SC of all tests passing while I figure whats going on with my setup.

Other than this, things LGTM

**Comment by shuklaayush** [comment]
Processor LGTM and aura-relevant tests are passing (am getting a timeout on one but that's probably an rpc issue). Still checking out the pricer

**Comment by sajanrajdev** [comment]
Indeed tests also passed for me when running independently (except for `tests/on_chain_pricer/test_swap_exec_on_chain.py::test_swap_in_balancer_batch` that timesout).  Looking more into the pricer.

**Comment by GalloDaSballo** [comment]
Will delegate to TechOps tomorrow unless Vetoed by any security peer reviewer

**Comment by sajanrajdev** [comment]
Changes to the Pricer LGTM. Review dropped on issue: https://github.com/Badger-Finance/badger-strategies/issues/57#issuecomment-1184918072

**Comment by petrovska-petro** [comment]
set managet to techops: https://ethtx.info/mainnet/0xbdbf222009fdbd87e79c2c9d6a5319de1c7d03fb095004e85574e540b0f48133/

**Comment by GalloDaSballo** [comment]
See PR #682

**Comment by GalloDaSballo** [comment]
Code was ported over with manual changes that broke it, see fixes above to make the setup work

**Comment by petrovska-petro** [comment]
```
Events In This Transaction
--------------------------
└── Gnosis Safe (0xB65cef03b9B89f99517643226d76e286ee999e77)
    └── ExecutionSuccess
        ├── txHash: 0xa726b6f3b7f6ad99550ec0a54b29489f6644ac467d3ddffad739db221ce5eebf
        └── payment: 0
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7fce7f03da60>,
│   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000079003c0989ef27e3e3fab87a2d7c38b35880c90e63b500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024b326440b0000000000000000000000000b6198b324e12a002b60162f8a130d6aedabd04c00000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 107946,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 1062,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
```

**Comment by petrovska-petro** [comment]
https://ethtx.info/mainnet/0xb36de612a34507140022433cf65519919233eb4ff5a7605162c7d968d55798bc/
