### ISSUE TITLE
Add scripts to process HH aura bribes and handle bribes

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#684]
- [x] Script review and merged

- [x] Claim bribes 

- [x] Process bribes for weth

- [x] Process weth into 25% badger and 75% aura

- [ ] Emit tokens

**Comment by sajanrajdev** [comment]
Bribes claimed and sold for wETH: https://etherscan.io/tx/0xcdbf8d7a59de812a874e6d8ba8391f83cf7dfb93bc832e54292cd28a6cf2fc15

Order: https://explorer.cow.fi/orders/0xbc10e041d28206fcd1e4fc6132c6f6ee6e65559157035f247de23f3cfdfafc6bc66c9f87d847ddc964724b789d3113885b08efcf62eae4f4

**Comment by sajanrajdev** [comment]
Process WETH into BADGER and AURA: https://etherscan.io/tx/0x9f64cdd0a605c64286a3d8e97913b1f362de59d3e14f2cf391603acec37b6f32

Orders: 
a) BADGER: https://explorer.cow.fi/orders/0xbc6cfbaaad70aa4f8384472ba1c5df4e156d9126c046609c0ab0a588ed146056c66c9f87d847ddc964724b789d3113885b08efcf62eaf829
b) AURA: https://explorer.cow.fi/orders/0x5d4040f549b0adbb1cfcc2177e0e91532f16b704d3bd8f67449010f26f02428cc66c9f87d847ddc964724b789d3113885b08efcf62eaf82d

**Comment by sajanrajdev** [comment]
Reposted wETH -> AURA as the previous one expired: https://etherscan.io/tx/0xe5d439e30152aabf16c468c4fb28bfc9e93b86aa89419f4abaf42983a90cd69b
https://explorer.cow.fi/orders/0xe471737ce06190234d4b82ced24f5eedfcea1c119c98aecdac524eff7cb35ba7c66c9f87d847ddc964724b789d3113885b08efcf62ebfbd0

**Comment by sajanrajdev** [comment]
Badger distributed: https://etherscan.io/tx/0xa925367cebccaa81d34ff52ea1b9d58c02e35ed22b90f91667b09006a8b22c97

**Comment by petrovska-petro** [comment]
the final portion from this round, which was in the processor has bent sent over to governance, details on #739. 

continuation will be for round 3 when new pricer is set to process that amount of aura. closing
