### ISSUE TITLE
Switch AuraBribesProcessor to fixed version

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#698]
Aura's BribesProcessor was redeployed due to an issue with the flattened logic of the previous one. It must be set on graviAura for Bribes to be processed promptly.

New logic: https://etherscan.io/address/0xc66c9f87d847ddc964724b789d3113885b08efcf

**Comment by GalloDaSballo** [comment]
Requires Signoff, see: https://github.com/Badger-Finance/badger-strategies/issues/57#issuecomment-1201385939

- [ ] @sajanrajdev 
- [ ] @shuklaayush 
- [ ] @camotelli

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x383472bbcd56f53baca321ca93f0c0f3578f60e44645670f9245d427b1fb8b8b
