### ISSUE TITLE
Wire up remDIGG to the restitution controller

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#72]
This relates to issue [35](https://github.com/Badger-Finance/badger-strategies/issues/35) of the badger-strategies repo.

The new remDIGG vault and strategy must be wired to the restitution controller via de devMultisig prior to launching.

Urgency
High - to be launched on Thursday/Friday

**Comment by sajanrajdev** [comment]
Uploaded at nonce [994](https://gnosis-safe.io/app/eth:0xB65cef03b9B89f99517643226d76e286ee999e77/transactions/queue)

**Comment by jorijnsmit** [comment]
https://etherscan.io/tx/0xd7f4c7873f24b2e8dd5c70cc1dc17b705d1a477bd124591833b48d4eb6f5fc37
