### ISSUE TITLE
Change bBB-A-USD wd fees and remove helper status

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#723]
Due to bauraBAL's upgrade, bBB-a-USD won't be emitted anymore as a helper and, hence, its metatdata should change to reflect a "none" type and its withdrawal fees should go to 0.1% in compliance with the token type fees structure.

The metadata can be changed from the registry (through techOps) and the fees must be changed from devMulti.

**Comment by sajanrajdev** [comment]
Vault type changed on Registry: https://etherscan.io/tx/0x3729b736e284f2d9ea06197727a068b4e3fe7fb0c991ff20dec6008d8e32a113

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x91a1ec1efb481519123a80a7cc729d04dec73037ccc3301eec1ba75c639f2f03#eventlog
