### ISSUE TITLE
Update Script for BribesProcessor to Handle AURA / graviAURA via cowswap

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-multisig#735]
Update:
https://github.com/Badger-Finance/badger-multisig/blob/main/scripts/badger/process_bribes_graviaura.py

To handle the new functionality

**Comment by GalloDaSballo** [comment]
NOTE:
If WETH -> AURA -> graviAURA is cheaper then: use Cowswap to get AURA
if WETH -> graviAURA is cheaper then: use Cowswap to get graviAURA

**Comment by shuklaayush** [comment]
Deployed updated processor
https://etherscan.io/address/0x8abd28e4d69bd3953b96dd9ed63533765adb9965#readContract

**Comment by gosuto-inzasheru** [comment]
closed by #736
