### ISSUE TITLE
Grant contract access to Treasury multisigs on ibBTC

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#78]
## Overview

Grant contract access to the Treasury Ops and Treasury Vault multisigs on all ibBTC peaks to enable minting. This needs to be done from the Peak owner multi (dualGovernance).

## Technical Details

Call:
`peak.approveContractAccess(multi_address)`

From: dualGovernance: 0xCF7346A5E41b0821b80D5B3fdc385EEB6Dc59F44

## Urgency and reason

Allow these multisig to perform operations with ibBTC directly without the need to delegate these steps to other multisigs. Mid priority,

**Comment by gosuto-inzasheru** [comment]
nonce 25: https://etherscan.io/tx/0xea96d23f87051163e102bbd85f7e09fd69437c3262ecd99fc9f997b5b66dc6bb
nonce 26: https://etherscan.io/tx/0xe6832e0ca172bf747c31753f5dc91382db42d1c1d582994ab0a7b2ae78870aca
