### ISSUE TITLE
deprecate arbitrum swapr vaults

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-multisig#791]
# Summary

fixes https://github.com/Badger-Finance/Badger-Project-Planning/issues/91

## Requirements

- deprecate all arbitrum vaults on swapr

**Comment by gosuto-inzasheru** [comment]
discussion going on right now to deprecate all vaults on arbitrum; this ticket could be extended to include all vaults.

on hold.

**Comment by gosuto-inzasheru** [comment]
consensus has been met around deprecating arbitrum, all 8 vaults have to be demoted.

**Comment by sajanrajdev** [comment]
Deprecations through RegistryACL:
- tricrypto: https://arbiscan.io/tx/0x9c7c6a2111597f0fc310c95c067f25c79b9eb532a95fcea0f341f747c0b51291
- wbtcEthSlp: https://arbiscan.io/tx/0x7fa157e669f6b85426848b203f3acc4edeb4fa9899f88b7373f56cd3a5b2c17a
- renCrv: https://arbiscan.io/tx/0x16b9b36538dc229d85c6dca1dcdb6f7bb383919d23e6306dbc09fb8fd10c1c91
- sushiWethSlp: https://arbiscan.io/tx/0x8f94dd7d38dfc075c234927f51adf145a1363cf26f68e9d0b4402dc5cd4f5193
- swaprWethDXS: https://arbiscan.io/tx/0x7f5c8586186caa9bfa230ecbb8e13434d4a27540e2ce6dabf40844ee5fcf5ba0
- badgerWethDXS: https://arbiscan.io/tx/0x08946250202313c357632b506b1d115b71e1b6b30b32152d382554540ebb04dd
- ibBTCWethDXS: https://arbiscan.io/tx/0x1abddcf7aee3acb951685cb6abbb5fcabd1b60a25f5e02340bbcdf07dc80fa7f
- wbtcWethDXS: https://arbiscan.io/tx/0xb13361593e90aa3d85361d54648a869dc833b310088d957342ecdf7caf2d7d67
