### ISSUE TITLE
[AuraBribesProcessor] SetPricer to New V3 Pricer

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-multisig#797]
New Pricer V3 deployment address:
Deployed and verified:
https://etherscan.io/address/0x2dc7693444acd1eca1d6de5b3d0d8584f3870c49#code

Notes about test:
https://github.com/GalloDaSballo/fair-selling/pull/35#issuecomment-1237425450

**Comment by sajanrajdev** [comment]
Executed: https://etherscan.io/tx/0x0891afe07432bbffa8b9bfa86cb02e6a15d01c8621e06ee7bccf4e969d8f5854
