### ISSUE TITLE
Bridge badger to arbitrum tree

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#810]
We need to bridge [3672.8571428571427 badger](https://github.com/Badger-Finance/badger-multisig/issues/705) to arbitrum tree, it was in hold due to nitro upgrade and merge

**Comment by petrovska-petro** [comment]
when bridging add another 2 weeks, which already were posted, following usual Q2 values for each week:

- renBTC Arb receives 476/week and badger swapr receives 381/week

Adds-up 1714 on top of prev amount, totalling: **5386.857142857143**

reminder to look into #530 in case that current script to bridge thru msig have some breaking change due to nitro upgrade

**Comment by petrovska-petro** [comment]
had being debugging prev script and my understanding is that there is not changes affected in our case. had explorer another newer [tx](https://etherscan.io/tx/0x2fdd62919738082f22426c71c7bea712ad719af02aa68982159b5a53e447436a) bridging badger to arb

getting this locally when exploring the revert tx:

```
...
 L1ArbitrumGateway.createOutboundTxCustomRefund  6449:7799  [1777 / 10730302 gas]
                                                └── L1ArbitrumMessenger.sendTxToL2CustomRefund  6506:7799  [-177832 / 10728525 gas]
                                                    └── TransparentUpgradeableProxy.createRetryableTicket  [CALL]  7194:7787  [183294 / 10906357 gas]
                                                        └── Proxy._fallback  7237:7787  [45 / 10723063 gas]
                                                            ├── TransparentUpgradeableProxy._beforeFallback  7241:7276  [97 / 921 gas]
                                                            │   ├── TransparentUpgradeableProxy._admin  7245:7250  [815 gas]
                                                            │   └── Proxy._fallback  7272:7274  [9 gas]
                                                            ├── UpgradeableProxy._implementation  7281:7286  [815 gas]
                                                            └── Proxy._delegate  7289:7787  [-175443 / 10721282 gas]
                                                                └── <UnknownContract>.0x679b6ded  [DELEGATECALL]  7301:7774  [10896725 gas]
```

i think is some issue at brownie level, where the VM version somehow cannot process things such as `block.basefee`, but that it is my assumption at the moment.

can you guys confirm the same locally? @gosuto-inzasheru @jalbrekt85 

running:

```
brownie run issue/630/bridge_badger_arbitrum 
```

**Comment by petrovska-petro** [comment]
arbitrum sdk [ref](https://github.com/OffchainLabs/arbitrum-sdk/blob/main/src/lib/assetBridger/erc20Bridger.ts#L530)

**Comment by gosuto-inzasheru** [comment]
yea i get a revert on the same call; `<UnknownContract>.0x679b6ded`.

**Comment by gosuto-inzasheru** [comment]
i tried updating interface `from_explorer` but still reverts

**Comment by petrovska-petro** [comment]
will try to sim in tenderly to see if also reverts there

**Comment by petrovska-petro** [comment]
> 

to tackle this temp, loaded a tx to one of the signer wallets

https://gnosis-safe.io/app/eth:0x042B32Ac6b453485e357938bdC38e0340d4b9276/transactions/0x0687ac0553c11795052c0e7c6de402a2a7cdf50585bb637c78c7098899ec7ef5

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x8a242296ed2fe1a32268c5264c258f5bfec1d0ca6eb7448389edc45a66246241

**Comment by petrovska-petro** [comment]
bridge tx to arb: https://etherscan.io/tx/0x875982d9d330f62c326a7a9cd410e249d72537246459d8b8a2adcdfdaa7f1a1f

**Comment by petrovska-petro** [comment]
transfer to arb tree: https://arbiscan.io/tx/0x3c1f4347d508a78c32f486906c6fdff56834f61092a50c1b16b88751a0be2ca5
