### ISSUE TITLE
feat: Adjust bveCVX bribe script to allow CVX selling

### ISSUE THREAD

**Issue by SHAKOTN** [Badger-Finance/badger-multisig#832]
In order to hunt CVX bribes placed on Votium need to adjust bribe script

**Comment by gosuto-inzasheru** [comment]
python script for graviaura processor will skip a aura to weth swap but will take it into consideration for fees and proper split at a later point. the old bvecvx processor script doesnt have this, and thus doesnt allow for claiming any bribes in cvx.

can we port that logic to the bvecvx script, without needing to make changes in the solidity code of the processor itself?

**Comment by GalloDaSballo** [comment]
@gosuto-inzasheru @SHAKOTN 
Re: Code

CVX Bribes are already claimable per the code here:
https://etherscan.io/address/0x86ca553d5ae7cd0005552d6e275786d5043800bd#code#F1#L321

Just in case Tech_Ops can also call `skim` same call to avoid any rebase of shares (loss to users)
https://etherscan.io/address/0x86ca553d5ae7cd0005552d6e275786d5043800bd#code#F1#L205

As long as all CVX is claimed and processed same block, this is completely fine.

If any CVX is stuck in contract we immediately need to `skim` to rebase the pffs back
