### ISSUE TITLE
Retire ops signer

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-multisig#841]
Retire 0xcf4fF1e03830D692F52EB094c52A5A6A2181Ab3F as an operation wallet.  Stop eth topups.

**Comment by gosuto-inzasheru** [comment]
address | chain | label
-- | -- | --
0x86cbD0ce0c087b482782c181dA8d191De18C8275 | eth | techops_multisig
0x6F76C6A1059093E21D8B1C13C4e20D8335e2909F | eth | politician_multisig
0x9faA327AAF1b564B569Cb0Bc0FDAA87052e8d92c | eth | recovered_multisig
0xD4868d98849a58F743787c77738D808376210292 | eth | ops_multisig
0x042B32Ac6b453485e357938bdC38e0340d4b9276 | eth | treasury_ops_multisig
0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8 | eth | ibbtc_multisig
0x30a9c1D258F6c2D23005e6450E72bDD42C541105 | eth | payments_multisig
0x329543f0F4BB134A3f7a826DC32532398B38a3fA | bsc | dev_multisig
0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327 | poly | techops_multisig
0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C | arbitrum | techops_multisig
0xb364bAb258ad35dd83c7dd4E8AC78676b7aa1e9F | arbitrum | dev_multisig
0x781E82D5D49042baB750efac91858cB65C6b0582 | ftm | techops_multisig
0xf109c50684EFa12d4dfBF501eD4858F25A4300B3 | ftm | treasury_ops_multisig

**Comment by gosuto-inzasheru** [comment]
was removed from gas station, eth balance has been returned to ops.

now only needs to be replaced as a signer.

**Comment by SHAKOTN** [comment]
https://arbiscan.io/tx/0x57f13fcf0fb9c90d1609a5f84f846322e68bfc4ee89dd0bf7d88e64b5fb59138

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0xb75549d7b4afd16680462ae8c3f557730e12350417fb60b08aec23f9d4fa7f78

**Comment by petrovska-petro** [comment]
https://bscscan.com/tx/0xce52af54e1a378c2bffa0fa5cc6adb86576279641273788f01207e3171170515

**Comment by petrovska-petro** [comment]
remove owner in techops ftm: [safe-tx](https://safe.fantom.network/ftm:0x781E82D5D49042baB750efac91858cB65C6b0582/transactions/multisig_0x781E82D5D49042baB750efac91858cB65C6b0582_0xbf273ef1088518494b4d8134f5c0a5465ff7a6c58f85fc0707e5b2942b96fdef)

**Comment by sajanrajdev** [comment]
ETH recovered: https://etherscan.io/tx/0x554f1bae3fe36808d8113749062ec6ff7f83e507d25d6f9d92212dc40d4f8b2d

**Comment by sajanrajdev** [comment]
FTM TechOps https://ftmscan.com/tx/0x6902bb25ca5df6d14e6c57c80efa8037cf0cd61dfa7863717de3ae0d6e16985f

**Comment by gosuto-inzasheru** [comment]
ftm trops: https://ftmscan.com/tx/0x51594db3a2c22424d6fa7bacea0c00a2bb8eb210c847a78219a8245658fbbdee

**Comment by sajanrajdev** [comment]
Polygon TechOps: https://polygonscan.com/tx/0xa3d753330e5d7d65eb813f353b6dc53d97a87359528423fc9870c055d64ab124
