### ISSUE TITLE
possible bug: `proposals` in bribe_hh.py is not complete 

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#847]
https://github.com/Badger-Finance/badger-multisig/blob/0651b7c1a3536fab76a2dc94b7a63f8deacc6f79/scripts/badger/bribe_hh.py#L69-L74

on the last bribe round i had to add `+ 5` to `proposal_index` in order to generate the correct `prop`. not sure if this is due to gauge migrations, a fluke or something else.

**Comment by petrovska-petro** [comment]
seems that in total rn there are so far 20 proposals in length in aura snap space, but somehow when they initiated this proposal they summed up 5, so i guess to adapt we need that `+5` for now to make it work

latest init [tx](https://etherscan.io/tx/0x65ff41fa88a42832b2e223ac0aac00158126c606c5c1ad25edcb7dc6f210b421) from hh

**Comment by petrovska-petro** [comment]
ended up finding the cause, will push solution in pr

**Comment by gosuto-inzasheru** [comment]
fixed by #874
