### ISSUE TITLE
quarter 1: topup gas station

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#884]
prev #880

**Comment by gosuto-inzasheru** [comment]
this might also be a good oppo to unwrap the little bit of $weth there

**Comment by petrovska-petro** [comment]
tx contains the top-up of gas station with 13.6 eth: https://etherscan.io/tx/0xb5d59152d248705013e79953e23d49e7ed077c407a0574dc8c479bb4e6a10eda
