### ISSUE TITLE
week 42: voter msig chores

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#895]
Carries:

- process expired locks
- claims aurabal rewards from locked aura and sends them to trops
- wd from gravi (up to whatever is avail) and all naked aura gets locked

**Comment by gosuto-inzasheru** [comment]
why did you create a new ticket? there is already #626 no?

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0xce85833f4ab307949f1c0758b09ed3fe97571780411276f4d050f980472d99c2

**Comment by petrovska-petro** [comment]
> why did you create a new ticket? there is already #626 no?

i think was the overexcitement somehow missed the old one, but i think the other can be left open which is for next week
