### ISSUE TITLE
add Ayush as signer to techOps

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#918]
as a backup signer / reviewer
using address `0x96AC69183216074dd8CFA7A380e873380445EaDc`

**Comment by petrovska-petro** [comment]
owner has being included already via swap in mainnet: https://etherscan.io/tx/0xb75549d7b4afd16680462ae8c3f557730e12350417fb60b08aec23f9d4fa7f78#eventlog

**Comment by gosuto-inzasheru** [comment]
also needs happen for other chains:
- [ ] arb1
- [ ] poly
- [ ] ftm
- [ ] opti

**Comment by petrovska-petro** [comment]
arb safe tx: https://gnosis-safe.io/app/arb1:0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C/transactions/multisig_0x292549E6bd5a41aE4521Bb8679aDA59631B9eD4C_0x79847548a3a54d9fc1317e0adbfdc9958172d83b9c8b2560147f7ce27e389d30

poly safe tx: https://gnosis-safe.io/app/matic:0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327/transactions/multisig_0xeb7341c89ba46CC7945f75Bd5dD7a04f8FA16327_0x0164548c9deb77a0df26e64f538a964369455288c3ef1e88a801c7a6a8feab7d

ftm safe tx: https://safe.fantom.network/ftm:0x781E82D5D49042baB750efac91858cB65C6b0582/transactions/multisig_0x781E82D5D49042baB750efac91858cB65C6b0582_0xef0635531a5a60851968ea8468edbe3193cc104027fce3fc5fe5f21ed8b2f5e5

opti safe tx: https://gnosis-safe.io/app/oeth:0x8D05c5DA2a3Cb4BeB4C5EB500EE9e3Aa71670733/transactions/multisig_0x8D05c5DA2a3Cb4BeB4C5EB500EE9e3Aa71670733_0x4d181c07d934b0f460e33786892432d94aa0b32a5874221e72549db1eccbb382

**Comment by petrovska-petro** [comment]
arbitrum tx: https://arbiscan.io/tx/0xc18398bc477dc144dbcd90102d0a37260b56aff1780a57bab24dd17b2bb18bc0

**Comment by sajanrajdev** [comment]
Fantom tx: https://ftmscan.com/tx/0x5c4bedca88a56e8bc5b37ec4fd2028e32e996f5fccc248a046b47329c153558d

**Comment by sajanrajdev** [comment]
Optimism: https://optimistic.etherscan.io/tx/0x52d0d05f65f7cd3cf1f05181ee5a07ac14f4bbc8847111b712c2b36a103a105a

**Comment by sajanrajdev** [comment]
Polygon: https://polygonscan.com/tx/0x266e5a2507324b020e795dd27e5bf96931502abbfef480fc26fdf74fd1845a48
