### ISSUE TITLE
Aura avatar integration

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#925]
The latest [avatar](https://etherscan.io/address/0x8cf0ce1dcccade5377b298384b039b3b77371de5) has being deployed and seeded with [testing funds](https://etherscan.io/tx/0x6acd7a75002a3812ef9ef31e1b3ce20cebca3dddb66781b54dc3433931f88564).

The upkeep is register in [CL](https://automation.chain.link/mainnet/59486959921930224455722597486617188999324301573251826755359563951736929414056), for testing purposes the cadence is 1d and the config setup is locking all aura and selling all bal for usdc. We will track the behaviour along the week and decide to start sending over treasury funds to automatised this strategy ops.

Steps for integration:

- update admin of upkeep job to techops from deployer. if not settable a new admin, will need cancel/wd funds and open new upkeep with techops as admin 
- transfer ownership away from deployer, set to vault
- change claiming frequency, 1w
- set manager techops
- withdraw all bps from [old avatar](https://etherscan.io/address/0xfAACbfc839Bc08f3fA543936Ff237e6cDB7df52B) and claim accum rewards 
- deposit in new avatar treasury funds

Open question, should we adapt the avatar contract to simply accept a bpt/pid for doing the same strategy ops for reth/badger treasury position?

**Comment by gosuto-inzasheru** [comment]
ah great to see this live! 

indeed the new aura badgerreth position will need to be included in this as well. also, it might not be the last aura position that the avatar will need to support, so some more dynamic approach of registering bpt addresses/pool ids sounds like a good idea.

**Comment by petrovska-petro** [comment]
closing in favour of #1207
