### ISSUE TITLE
week 1: emissions schedules mainnet (2023)

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#933]
prev #913

**Comment by gosuto-inzasheru** [comment]
<img width="974" alt="Screenshot 2023-01-03 at 16 59 49" src="https://user-images.githubusercontent.com/2835259/210383049-69d93e40-9c8a-468e-9009-55ca4f3a4f61.png">

also rembadger needs to be set

**Comment by gosuto-inzasheru** [comment]
rembadger schedule q4: https://github.com/Badger-Finance/badger-multisig/issues/612

**Comment by sajanrajdev** [comment]
### remBADGER emissions
- An emission rate of 7692.307692 BADGER/week means 400,000 BADGER a year.
- The last emission [schedule](https://etherscan.io/tx/0x5513cd485f313801562d53e6ff2283bef161c730176eca474b405cd0ae41c0ef#eventlog) ended on 	Fri Dec 30 2022 00:00:00 GMT+0000, therefore there is a 2 day deficit to the beginning of the year Sun Jan 01 2023 00:00:00 GMT+0000 (1672531200)

With the above being said, the schedule should have the following parameters:
- Start time (chosen at some point in the near future to allow for execution): 1672790400 (Wed Jan 04 2023 00:00:00 GMT+0000, in 4 hrs)
- End time: 1672531200 + (365 * 24 * 60 * 60) = 1704067200
- Amount: 400,000 + (7692.307692/7) * 2 = 402197.802198

**Comment by gosuto-inzasheru** [comment]
i dont think the extra two days are necessary.

it is true the previous schedule was only until the 30th of december, however it was for the full amount. so it just ended a bit earlier, but did distribute all $badger for that quarter.

**Comment by petrovska-petro** [comment]
confirming that prev schedule was for 13w covering the whole q4, deficit is not required to add-up, initially i though the same since the end date was not 1st jan 0000 utc

**Comment by sajanrajdev** [comment]
@petrovska-petro @gosuto-inzasheru, sounds good. That means that the total amount to be emitted should be 400,000 BADGER only. Posting now..

**Comment by sajanrajdev** [comment]
For bcvxCRV, the following is the last schedule (finished 4 days ago): 
```
[0x2B5455aac8d64C14786c3a29858E43b5945819C0,0x3472A5A71965499acd81997a54BBA8D852C6E53d,12637714285714284415007,1667606400,1672531200,4924800]
```

Emitting 1552 BADGER/Week for 1 month, starting in 2 hours. A ~4days deficit must be considered given the previous schedule expiration.

Start time (same as for remBADGER): 1672855200
End time: 1672855200 + (3600 * 24 * 7 * 4) = 1675274400
Amount: (1552 * 4) + (1552 * (1672855200-1672531200)) / (3600 * 24 * 7)
Duration: (3600 * 24 * 7 * 4) = 2419200

**Comment by sajanrajdev** [comment]
remBADGER: https://etherscan.io/tx/0x59920f44665ca534736f674c17dae9dc37cbf8c9fd33bc7a23d5c4c84fb605f2
bcvxCRV: https://etherscan.io/tx/0x784a5e0bbf058eb85f1e3cfd6a23f7eb42be12166887d0cba974292bbe1095a8

**Comment by gosuto-inzasheru** [comment]
just realised we still need the tree dripper for the rembadger emissions. i will deploy one.
