### ISSUE TITLE
week 46: voter msig chores

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#937]
prev #626

**Comment by petrovska-petro** [comment]
visual aid for expired locks

<img width="379" alt="Screenshot 2022-11-09 at 02 42 41" src="https://user-images.githubusercontent.com/84875062/200659986-7ebaa32d-1818-4aee-b29a-10f2b6a40b02.png">

**Comment by petrovska-petro** [comment]
closing this chore ticket in favour of the [upkeep cl job](https://automation.chain.link/mainnet/42960818007215227498102337773007812241122867237937589685113781988946396009556)
