### ISSUE TITLE
Governance 2.0 Cleanup: Stage 1

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-multisig#944]
# Status 

- [x] Set timelock in deprecated v1 vaults
- [x] Admin cleanup for guardian & badger controller, setting dev_msig as admin
- [x] Admin Cleanup for BadgerTree and Rewards Logger (*Old Ops Multi tx*)

# Governance Cleanup
Premise: 
- Progressively set governance roles to timelock for mature code as part of the decentraliziation roadmap
- Progressively burn upgrade rights for mature code

# Timelock for governance of all deprecated v1 vaults
`governance()` should be set to `governanceTimelock` for the following contracts

(vaults only, no strategies yet, to batch review time)

```
  0xd04c48a53c111300ad41190d63681ed3dad998ec (name=renBTC/wBTC/sBTC,protocol=Convex,behavior=None)
  0xb9d076fde463dbc9f915e5392f807315bf940334 (name=tBTC/sBTC,protocol=Convex,behavior=None)
  0xaf5a1decfa95baf63e0084a35c62592b774a2a87 (name=renBTC/wBTC,protocol=Curve,behavior=None)
  0x235c9e24d3fb2fafd58a2e49d454fdcd2dbf7ff1 (name=wBTC/Badger,protocol=Uniswap,behavior=None)
  0xc17078fdd324cc473f8175dc5290fae5f2e84714 (name=wBTC/Digg,protocol=Uniswap,behavior=None)
  0x19d97d8fa813ee2f51ad4b4e04ea08baf4dffc28 (name=Badger,protocol=Badger,behavior=None)
  0x8a8ffec8f4a0c8c9585da95d9d97e8cd6de273de (name=wBTC/ibBTC,protocol=Sushiswap,behavior=None)
  0x8c76970747afd5398e958bdfada4cf0b9fca16c4 (name=hBTC,protocol=Convex,behavior=None)
  0x55912d0cf83b75c492e761932abc4db4a5cb1b17 (name=pBTC,protocol=Convex,behavior=None)
  0xf349c0faa80fc1870306ac093f75934078e28991 (name=oBTC,protocol=Convex,behavior=None)
  0x5dce29e92b1b939f8e8c60dcf15bde82a85be4a9 (name=bBTC,protocol=Convex,behavior=None)
  0xbe08ef12e4a553666291e9ffc24fccfd354f2dd2 (name=Tricrypto,protocol=Convex,behavior=None)
  0x53c8e199eb2cb7c01543c137078a038937a68e40 (name=CVX,protocol=Convex,behavior=None)
  0x599d92b453c010b1050d31c364f6ee17e819f193 (name=imBTC,protocol=mStable,behavior=None)
  0x26b8efa69603537ac8ab55768b6740b67664d518 (name=mhBTC,protocol=mStable,behavior=None)
  0x19e4d89e0cb807ea21b8cef02df5eaa99a110da5 (name=MIM/3CRV,protocol=Convex,behavior=None)
  0x15cbc4ac1e81c97667780fe6dadedd04a6eeb47b (name=FRAX/3CRV,protocol=Convex,behavior=None)
  0x88128580acdd9c04ce47afce196875747bf2a9f6 (name=wBTC/Digg,protocol=Sushiswap,behavior=None)
  0x7e7e112a68d8d2e221e11047a72ffc1065c38e1a (name=Digg,protocol=Badger,behavior=None)
  0x758a43ee2bff8230eeb784879cdcff4828f2544d (name=wBTC/wETH,protocol=Sushiswap,behavior=None)
  0x1862a18181346ebd9edaf800804f89190def24a5 (name=wBTC/Badger,protocol=Sushiswap,behavior=None)
  0x27e98fc7d05f54e544d16f58c194c2d7ba71e3b5 (name=Tricrypto2,protocol=Convex,behavior=None)
```

### How-to
```
governanceTimelock = 0x21CF9b77F88Adf8F8C98d7E33Fe601DC57bC0893
proxy.setGovernance(<governanceTimelock>)
```

# System contracts proxy admin cleanup
Some system contracts use old admins, this should be cleaned up.

## opsProxyAdmin_old
`opsProxyAdmin_old -> proxyAdminTimelock` for the following contracts

```
0x660802fc641b154aba66a62137e71f331b6d787a (badgerTree)
0x0a4f4e92c3334821ebb523324d09e321a6b0d8ec (rewardsLogger)
```

### How-to
```
opsProxyAdmin_old = 0x4599F2913a3db4E73aA77A304cCC21516dd7270D
proxyAdminTimelock = 0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
opsProxyAdmin_old.changeProxyAdmin(<proxy>, proxyAdminTimelock)
```
(opsProxyAdmin_old is owned by ops_multisig_old `0x576cD258835C529B54722F84Bb7d4170aA932C64`)

## proxyAdminDev
`proxyAdminDev -> proxyAdminTimelock` for the following contracts

```
0x6615e67b8b6b6375d38a0a3f937cd8c1a1e96386 (guardian access control)
0xdDB2dfad74F64F14bb1A1cbaB9C03bc0eed74493 (badger controller)
```

### How-to
```
proxyAdminDev = 0x9215cBDCDe25629d0e3D69ee5562d1b444Cf69F9
proxyAdminTimelock = 0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
proxyAdminDev.changeProxyAdmin(<proxy>, proxyAdminTimelock)
```

(proxyAdminDev is owned by dev multi)

**Comment by petrovska-petro** [comment]
**Note:** timelock contract is a temp setup, till veto timelock is ready/deployed

**Comment by petrovska-petro** [comment]
## set gov tx deprecated v1 vaults

list:

```
Found 22 deprecated vaults:
[
    'Badger Sett Curve.fi renBTC/wBTC/sBTC',
    'Badger Sett Curve.fi tBTC/sbtcCrv',
    'Badger SuperSett (Harvest) Curve.fi renBTC/wBTC',
    'Badger Sett Uniswap V2',
    'Badger Sett Uniswap V2',
    'Badger Sett Badger',
    'Badger Sett SushiSwap LP Token',
    'Badger Sett Curve.fi hBTC/wBTC',
    'Badger Sett Curve.fi pBTC/sbtcCRV',
    'Badger Sett Curve.fi oBTC/sbtcCRV',
    'Badger Sett Curve.fi bBTC/sbtcCRV',
    'Badger Sett Curve.fi USD-BTC-ETH',
    'Badger Sett Convex Token',
    'Badger Sett Interest bearing mStable BTC',
    'Badger Sett mBTC/HBTC Feeder Pool',
    'Badger Sett Curve.fi Factory USD Metapool: Magic Internet Money 3Pool',
    'Badger Sett Curve.fi Factory USD Metapool: Frax',
    'Badger Sett SushiSwap LP Token',
    'Badger Sett Digg',
    'Badger Sett SushiSwap LP Token',
    'Badger Sett SushiSwap LP Token',
    'Badger Sett Curve.fi USD-BTC-ETH'
]
```

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f95d95a7670>,
│   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a6600d04c48a53c111300ad41190d63681ed3dad998ec00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300b9d076fde463dbc9f915e5392f807315bf94033400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300af5a1decfa95baf63e0084a35c62592b774a2a8700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300235c9e24d3fb2fafd58a2e49d454fdcd2dbf7ff100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300c17078fdd324cc473f8175dc5290fae5f2e8471400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930019d97d8fa813ee2f51ad4b4e04ea08baf4dffc2800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893008a8ffec8f4a0c8c9585da95d9d97e8cd6de273de00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893008c76970747afd5398e958bdfada4cf0b9fca16c400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930055912d0cf83b75c492e761932abc4db4a5cb1b1700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300f349c0faa80fc1870306ac093f75934078e2899100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893005dce29e92b1b939f8e8c60dcf15bde82a85be4a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300be08ef12e4a553666291e9ffc24fccfd354f2dd200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930053c8e199eb2cb7c01543c137078a038937a68e4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300599d92b453c010b1050d31c364f6ee17e819f19300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930026b8efa69603537ac8ab55768b6740b67664d51800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930019e4d89e0cb807ea21b8cef02df5eaa99a110da500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930015cbc4ac1e81c97667780fe6dadedd04a6eeb47b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930088128580acdd9c04ce47afce196875747bf2a9f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893007e7e112a68d8d2e221e11047a72ffc1065c38e1a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300758a43ee2bff8230eeb784879cdcff4828f2544d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893001862a18181346ebd9edaf800804f89190def24a500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930027e98fc7d05f54e544d16f58c194c2d7ba71e3b500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930000000000000000000000000000000000000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 476180,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 1084,
│   '_safe_version': '1.1.1',
│   '_chain_id': None
}
```

**Comment by sajanrajdev** [comment]
## Proxy Admin Cleanup for BadgerTree and Rewards Logger (Old Ops Multi)

```
Running 'scripts/issue/944/gov_cleanup.py::change_new_proxy_admin'...
p`changing proxy admin for 0x660802Fc641b154aBA66a62137e71f331B6d787A from 0x4599F2913a3db4E73aA77A304cCC21516dd7270D to
0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
Transaction sent: 0x42db9be9c851404c4510e92b3b35a5d61edf48c0cd50530bd0396de5d5a9e19f
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
  IProxyAdmin.changeProxyAdmin confirmed   Block: 15976178   Gas used: 33097 (0.28%)

p`changing proxy admin for 0x0A4F4e92C3334821EbB523324D09E321a6B0d8ec from 0x4599F2913a3db4E73aA77A304cCC21516dd7270D to
0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
Transaction sent: 0x8ccca3e1b32b3ad92b32b671192048a396abfb93e78a9a1fb3556fa4d3c8b617
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
  IProxyAdmin.changeProxyAdmin confirmed   Block: 15976179   Gas used: 33003 (0.28%)
```

**Comment by petrovska-petro** [comment]
> ## set gov tx deprecated v1 vaults
> list:
> 
> ```
> Found 22 deprecated vaults:
> [
>     'Badger Sett Curve.fi renBTC/wBTC/sBTC',
>     'Badger Sett Curve.fi tBTC/sbtcCrv',
>     'Badger SuperSett (Harvest) Curve.fi renBTC/wBTC',
>     'Badger Sett Uniswap V2',
>     'Badger Sett Uniswap V2',
>     'Badger Sett Badger',
>     'Badger Sett SushiSwap LP Token',
>     'Badger Sett Curve.fi hBTC/wBTC',
>     'Badger Sett Curve.fi pBTC/sbtcCRV',
>     'Badger Sett Curve.fi oBTC/sbtcCRV',
>     'Badger Sett Curve.fi bBTC/sbtcCRV',
>     'Badger Sett Curve.fi USD-BTC-ETH',
>     'Badger Sett Convex Token',
>     'Badger Sett Interest bearing mStable BTC',
>     'Badger Sett mBTC/HBTC Feeder Pool',
>     'Badger Sett Curve.fi Factory USD Metapool: Magic Internet Money 3Pool',
>     'Badger Sett Curve.fi Factory USD Metapool: Frax',
>     'Badger Sett SushiSwap LP Token',
>     'Badger Sett Digg',
>     'Badger Sett SushiSwap LP Token',
>     'Badger Sett SushiSwap LP Token',
>     'Badger Sett Curve.fi USD-BTC-ETH'
> ]
> ```
> 
> ```
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f95d95a7670>,
> │   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
> │   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a6600d04c48a53c111300ad41190d63681ed3dad998ec00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300b9d076fde463dbc9f915e5392f807315bf94033400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300af5a1decfa95baf63e0084a35c62592b774a2a8700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300235c9e24d3fb2fafd58a2e49d454fdcd2dbf7ff100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300c17078fdd324cc473f8175dc5290fae5f2e8471400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930019d97d8fa813ee2f51ad4b4e04ea08baf4dffc2800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893008a8ffec8f4a0c8c9585da95d9d97e8cd6de273de00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893008c76970747afd5398e958bdfada4cf0b9fca16c400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930055912d0cf83b75c492e761932abc4db4a5cb1b1700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300f349c0faa80fc1870306ac093f75934078e2899100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893005dce29e92b1b939f8e8c60dcf15bde82a85be4a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300be08ef12e4a553666291e9ffc24fccfd354f2dd200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930053c8e199eb2cb7c01543c137078a038937a68e4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300599d92b453c010b1050d31c364f6ee17e819f19300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930026b8efa69603537ac8ab55768b6740b67664d51800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930019e4d89e0cb807ea21b8cef02df5eaa99a110da500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930015cbc4ac1e81c97667780fe6dadedd04a6eeb47b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930088128580acdd9c04ce47afce196875747bf2a9f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893007e7e112a68d8d2e221e11047a72ffc1065c38e1a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc089300758a43ee2bff8230eeb784879cdcff4828f2544d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc0893001862a18181346ebd9edaf800804f89190def24a500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930027e98fc7d05f54e544d16f58c194c2d7ba71e3b500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024ab033ea900000000000000000000000021cf9b77f88adf8f8c98d7e33fe601dc57bc08930000000000000000000000000000000000000000000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 476180,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 1084,
> │   '_safe_version': '1.1.1',
> │   '_chain_id': None
> }
> ```

https://etherscan.io/tx/0xa9d5c1bf2f339569b44c49e458f14938dedb89ee45947213730f3db619bea900

**Comment by petrovska-petro** [comment]
> ## proxy admin cleanup for guardian & badger controller
> ```
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f9b0edf8220>,
> │   'safe_address': '0xB65cef03b9B89f99517643226d76e286ee999e77',
> │   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000132009215cbdcde25629d0e3d69ee5562d1b444cf69f9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000447eff275e0000000000000000000000006615e67b8b6b6375d38a0a3f937cd8c1a1e9638600000000000000000000000020dce41acca85e8222d6861aa6d23b6c941777bf009215cbdcde25629d0e3d69ee5562d1b444cf69f9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000447eff275e000000000000000000000000ddb2dfad74f64f14bb1a1cbab9c03bc0eed7449300000000000000000000000020dce41acca85e8222d6861aa6d23b6c941777bf0000000000000000000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 0,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 1085,
> │   '_safe_version': '1.1.1',
> │   '_chain_id': None
> }
> ```

https://etherscan.io/tx/0x9c60f2187d4bd4da993782429f01dd51598e49747972f799c2470436762a3e57

**Comment by petrovska-petro** [comment]
nonce are all mess up in ops msig, tx needs reposting into nonce 80 explicitly

**Comment by petrovska-petro** [comment]
> ## Proxy Admin Cleanup for BadgerTree and Rewards Logger (Old Ops Multi)
> [SAFE](https://gnosis-safe.io/app/eth:0x576cD258835C529B54722F84Bb7d4170aA932C64/transactions/queue)
> 
> ```
> Running 'scripts/issue/944/gov_cleanup.py::change_new_proxy_admin'...
> p`changing proxy admin for 0x660802Fc641b154aBA66a62137e71f331B6d787A from 0x4599F2913a3db4E73aA77A304cCC21516dd7270D to
> 0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
> Transaction sent: 0x42db9be9c851404c4510e92b3b35a5d61edf48c0cd50530bd0396de5d5a9e19f
>   Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
>   IProxyAdmin.changeProxyAdmin confirmed   Block: 15976178   Gas used: 33097 (0.28%)
> 
> p`changing proxy admin for 0x0A4F4e92C3334821EbB523324D09E321a6B0d8ec from 0x4599F2913a3db4E73aA77A304cCC21516dd7270D to
> 0x20Dce41Acca85E8222D6861Aa6D23B6C941777bF
> Transaction sent: 0x8ccca3e1b32b3ad92b32b671192048a396abfb93e78a9a1fb3556fa4d3c8b617
>   Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
>   IProxyAdmin.changeProxyAdmin confirmed   Block: 15976179   Gas used: 33003 (0.28%)
> 
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f5d6aee0f70>,
> │   'safe_address': '0x576cD258835C529B54722F84Bb7d4170aA932C64',
> │   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000132004599f2913a3db4e73aa77a304ccc21516dd7270d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000447eff275e000000000000000000000000660802fc641b154aba66a62137e71f331b6d787a00000000000000000000000020dce41acca85e8222d6861aa6d23b6c941777bf004599f2913a3db4e73aa77a304ccc21516dd7270d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000447eff275e0000000000000000000000000a4f4e92c3334821ebb523324d09e321a6b0d8ec00000000000000000000000020dce41acca85e8222d6861aa6d23b6c941777bf0000000000000000000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 0,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 692,
> │   '_safe_version': '1.1.1',
> │   '_chain_id': None
> }
> ```

tx was reposted into nonce 79 to be trigger before #1114

**Comment by gosuto-inzasheru** [comment]
correction: before #1115

**Comment by gosuto-inzasheru** [comment]
https://etherscan.io/tx/0x0065d1bb6eda25068cf5b06480561e985324caf747c56c0dc5dd35731911a82b#eventlog

**Comment by gosuto-inzasheru** [comment]
rewardslogger: https://etherscan.io/tx/0xe9cc5abe41ec0414b9a5cff007dec22485d7878df83e59dcefef49516e07975a#eventlog
