### ISSUE TITLE
Aura Birbs 2022-11-09 through 11-14

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#955]
https://vote.aura.finance/#/proposal/0x965fb50ce65ca8ee973e8d00e896c70e5a78de075b8703bc43079bbf27191301
option "50/50 BADGER/rETH"
10k $BADGER

![image](https://user-images.githubusercontent.com/113713830/201362370-32c1241a-a88f-4b45-8cc3-bf755e71a4c2.png)

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x5150e0452e1bc44aaedaecc76a2c5b5f67793f5bb4506b4ab7b2e7402f82aa34
