### ISSUE TITLE
Convex Birbs 2022-11-09 through 11-14

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-multisig#956]
https://snapshot.org/#/cvx.eth/proposal/0xd7db40d1ca142cb5ca24bce5d0f78f3b037fde6c7ebb3c3650a317e910278b1f
Option: BADGER+FRAXBP
6k $BADGER

![image](https://user-images.githubusercontent.com/113713830/201363171-17dc91a8-e657-41a9-b509-24f83ece611e.png)

**Comment by petrovska-petro** [comment]
https://etherscan.io/tx/0x5150e0452e1bc44aaedaecc76a2c5b5f67793f5bb4506b4ab7b2e7402f82aa34
