### ISSUE TITLE
port curve swap function

### ISSUE THREAD

**Issue by jorijnsmit** [Badger-Finance/badger-multisig#96]
old source code:
```
    def _swap(self, registry, pool_address, asset_in, asset_out, mantissa):
        # helper for common functionalities despite of the registry/pool route
        initial_asset_out_balance = asset_out.balanceOf(self.safe)
        asset_in.approve(pool_address, mantissa)
        i, j, underlying_coin_boolean = registry.get_coin_indices(
            pool_address, asset_in, asset_out
        )
        pool = self.safe.contract(pool_address)
        expected = pool.get_dy(i, j, mantissa) * (1 - self.max_slippage_and_fees)
        # L139 docs ref
        pool.exchange(i, j, mantissa, expected)
        assert asset_out.balanceOf(self.safe) >= initial_asset_out_balance + expected


    def swap(self, asset_in, asset_out, mantissa):
        # swap `asset_in` (amount: `mantissa`) for `asset_out`
        # https://curve.readthedocs.io/factory-pools.html?highlight=exchange#StableSwap.exchange
        # https://curve.readthedocs.io/registry-exchanges.html?highlight=get_best_rate#finding-pools-and-swap-rates
        pool = self.generalised_rates_info.get_best_rate(asset_in, asset_out, mantissa)[0]
        registry = self._get_registry(self.safe.contract(pool))
        self._swap(registry, pool, asset_in, asset_out, mantissa)
```

**Comment by jorijnsmit** [comment]
@jalbrekt85 you mind seeing how easy it is to pr this into the current class? will have to happen after merge of #89 .

also i think changes to curve class in that pr will allow you to clean up calls such as `pool.add_liquidity[f'uint[{len(mantissas)}],uint']` since the pool interface will be correctly set automatically.

have a look, maybe you can help review #89 as well.

**Comment by jalbrekt85** [comment]
> @jalbrekt85 you mind seeing how easy it is to pr this into the current class? will have to happen after merge of #89 .
> 
> also i think the pending changes to the curve class in that pr will allow you to clean up calls such as `pool.add_liquidity[f'uint[{len(mantissas)}],uint']` since the pool interface will be correctly set automatically.
> 
> have a look, maybe you can help review #89 as well.

 👍
