### ISSUE TITLE
withdraw 50 weth to eth and fund payments msig

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-multisig#981]
this to enable payments in eth directly, instead of buying eth using usdc.

**Comment by petrovska-petro** [comment]
wd weth -> eth step

```
{
│   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f985a4fbf10>,
│   'safe_address': '0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e',
│   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
│   'value': 0,
│   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000007900c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000242e1a7d4d000000000000000000000000000000000000000000000002b5e3af16b188000000000000000000'),
│   'operation': 1,
│   'safe_tx_gas': 0,
│   'base_gas': 0,
│   'gas_price': 0,
│   'gas_token': '0x0000000000000000000000000000000000000000',
│   'refund_receiver': '0x0000000000000000000000000000000000000000',
│   'signatures': b'',
│   '_safe_nonce': 87,
│   '_safe_version': '1.3.0',
│   '_chain_id': None
}
```

**Comment by petrovska-petro** [comment]
> wd weth -> eth step
> 
> ```
> {
> │   'ethereum_client': <gnosis.eth.ethereum_client.EthereumClient object at 0x7f985a4fbf10>,
> │   'safe_address': '0xD0A7A8B98957b9CD3cFB9c0425AbE44551158e9e',
> │   'to': '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
> │   'value': 0,
> │   'data': HexBytes('0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000007900c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000242e1a7d4d000000000000000000000000000000000000000000000002b5e3af16b188000000000000000000'),
> │   'operation': 1,
> │   'safe_tx_gas': 0,
> │   'base_gas': 0,
> │   'gas_price': 0,
> │   'gas_token': '0x0000000000000000000000000000000000000000',
> │   'refund_receiver': '0x0000000000000000000000000000000000000000',
> │   'signatures': b'',
> │   '_safe_nonce': 87,
> │   '_safe_version': '1.3.0',
> │   '_chain_id': None
> }
> ```

https://etherscan.io/tx/0xad60489dcd1c0010d6e341d4f379a46cfbc578d6b09ee55cee4b4a6736ff8874

**Comment by gosuto-inzasheru** [comment]
eth to payments msig: https://etherscan.io/tx/0x8cbe6dae86e2f8526505792e0ec621a9c83e7d9532d80291baa333cccbd9287c
